### ISSUE TITLE
[All multiplayer source games] Add new vote kick reasons for Racism and Sexism.

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/Source-1-Games#6817] opened 2024-12-03 14:10 UTC
I am asking for this on the behalf of my younger sibling and any individual out there who has been harrashed online for being themselves. In a day and age where anyone can play the online videogames they like I sincerely believe a simple change like this could be a benefit to thoses out there who are suffering from cyber bullying online by inidivuals who believe they can cause herendous harm without consequence.

As a simple exemple: I regularly play Tf2 with my little sister and once she was nearly votekicked out of a casual match because she was a woman. It really hurts her that everytime people figure out who she is (Her steam profile says she is a woman) she is instantly targeted for no reasons besides hatred and getting a few kicks out of being a genuine asshole.

This simple change may not be must, but I would really like to see something like this implemented, just to say "We don't support hatred"

Or you could vote for bad people to be turned onto a frog or a Spycrab like in Deadlocks. I would say it's rightfully deserved.

**Comment by kisak-valve** [comment] 2024-12-03 14:19
Hello @condor00fr, this is functionally a duplicate of #3957. Closing in favor of the older feature request.

**Closed as not planned by kisak-valve** 2024-12-03 14:19 UTC
