### ISSUE TITLE
l4d2 linux audio speakers don't saving

### ISSUE THREAD

**Issue by steamlinux** [ValveSoftware/Source-1-Games#1906] opened 2015-07-06 17:50 UTC
after re-launch game. setting "speaker type" set to "headphones", I have speakers 5.1

**Comment by Tele42** [comment] 2015-07-09 00:36
Left 4 dead 2 currently only supports stereo on linux, pulseaudio can expand this a bit, but it is still stereo.

**Comment by steamlinux** [comment] 2015-07-09 11:02
no! l4d2 normal support surround sound! I go to take screenshot

**Comment by steamlinux** [comment] 2015-07-09 11:08
![2015-07-09 14-06-49](https://cloud.githubusercontent.com/assets/11569159/8593831/e6cd0582-2643-11e5-9a26-f01b0e95ea9c.png)

**Comment by steamlinux** [comment] 2015-07-09 11:08
look at screenshot, surround sound normally support and work!

**Comment by s0r00t** [comment] 2015-07-10 00:34
Duplicate of #1881.

**Comment by steamlinux** [comment] 2015-07-10 09:26
the problem because no one reacts

**Comment by s0r00t** [comment] 2015-07-10 10:16
Duplicating the issue here won't help.

**Comment by steamlinux** [comment] 2015-07-11 09:56
I am ready to create 100 such topics, just to have corrected this trouble

**Comment by Tele42** [comment] 2015-07-11 12:15
"Do not intentionally multi-post an issue." from the <a href="https://github.com/ValveSoftware/Source-1-Games#conduct">code of conduct</a> for this issue tracker. Spamming issue reports will _not_ end well.

**Comment by steamlinux** [comment] 2015-07-12 18:56
I understand. but the developers did not react. and the CS:GO this problem fixed in a couple of days

**Comment by steamlinux** [comment] 2015-07-16 21:11
someone fix this bug?

**Comment by kisak-valve** [comment] 2016-12-30 00:43
Closing as this appears to have been fixed.

**Closed by kisak-valve** 2016-12-30 00:43 UTC

**Comment by steamlinux** [comment] 2017-01-14 14:44
anwer #1881
