### ISSUE TITLE
[TF2] [Feature request] Increase max fov_desired (default_fov) in official matchmaking to 120

### ISSUE THREAD

**Issue by pitbullnamed1** [ValveSoftware/Source-1-Games#5969] opened 2024-05-04 15:35 UTC
Team Fortress 2 is a 3-dimensional high-pace movement shooter that demands its players to see as much as possible. Playing certain classes (heavy, scout, engineer, medic) is extremely uncomfortable given the fact that they depend on seeing more but they can't because of a server-restricted client cheat fov_default that defines a value of fov_desired players can use, which ranges from 75-90, but it should go as high as 120. Many players that face the issue of not seeing enough of what happens in the game world, override their screen resolution to have a higher aspect ratio (24:9 mostly, as it does provide higher field of view equal to ~130 rounding up to tf2's numbers when fov_desired is set to 90). However, setting a higher aspect ratio only provides horizontal increase in field of view, not vertical, which makes the method significantly worse than using a console command that's just restricted to use outside of 75-90. In a similar valve game, Left 4 Dead 2, 120 fov is supported. Both TF2 and L4D2 are 3-dimensional high-pace movement shooters, TF2 is even more demanding in terms of looking around and being able to observe as more space as possible, given the chaotic nature of its gameplay, than that of L4D2, where players need 120 fov to be able to see special infected players from chokes, and having more time to react to their actions.

**Comment by NULLYUKI** [comment] 2024-05-04 15:36
Duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/4043

**Comment by kisak-valve** [comment] 2024-05-04 15:39
Hello @pitbullnamed1, as @NULLYUKI noted, this issue is already being tracked at #4043.

Closing as a duplicate.

**Closed as not planned by kisak-valve** 2024-05-04 15:39 UTC
