### ISSUE TITLE
The game closes when I open settings or load maps.

### ISSUE THREAD

**Issue by Avagut2024** [ValveSoftware/Source-1-Games#5847] opened 2024-04-21 05:22 UTC
The game closes when I open settings or load maps, so I can't play at all. This happens to me on Windows 7 64bits since your last update.

**Comment by jh34ghu43gu** [comment] 2024-04-21 10:50
Duplicate of #5728 and #5674

**Comment by kisak-valve** [comment] 2024-04-21 13:49
Hello @Avagut2024, as @jh34ghu43gu noted, this issue is already being tracked at #5728 and #5674. Closing as a duplicate.

**Closed by kisak-valve** 2024-04-21 13:49 UTC

**Comment by Ariel190293** [comment] 2024-04-23 03:31
Experiencing frequent game crashes when trying to open settings <a href="https://pokerogue.io/">Pokerogue</a> or load maps on Windows 7 64-bit after the latest update. This issue prevents me from playing the game at all.
