### ISSUE TITLE
[LFD2][Windows 10]Endless game without ending

### ISSUE THREAD

**Issue by TannicArcher** [ValveSoftware/Source-1-Games#5919] opened 2024-04-26 12:40 UTC
To play before entering the Atrium map, enter in the console
sv_cheats 1
z_ difficulty impossible
map and select Atrium
After you have entered the game, turn on god 1 and go to the elevator and grab it, at this moment canisters appear, turn on the noclip and collect them and fill them into the car as quickly as possible, in total there should be 13 pieces and after that, as you fill up the tank, it lights up red and so on for more than 30 minutes then I left the game I think the problem is in the game function.
The console displayed something like delay early and the like many times

**Comment by Tsuey** [comment] 2024-04-29 07:22
@kisak-valve Should probably mark this as wontfix considering it requires noclip?

I wrote a [full analysis](https://steamcommunity.com/app/550/discussions/0/1639788130274252869/?l=italian#c1639788130274253658) of Dead Center 4's map I/O a few years ago, which demonstrates that noclip in this case is bypassing a crucial trigger. There was a bug that was fixed on April 14 2022 [as documented later in that same thread](https://steamcommunity.com/app/550/discussions/0/1639788130274252869/?l=italian&ctp=2#c5287797783033242662) and the fix [documented in the TF2 VScript issue](https://github.com/ValveSoftware/Source-1-Games/issues/4481#issuecomment-1304553207) which would cause this "endless game" outcome through normal play, but we can 100% confirm that is fixed -- and requires noclip to break anything, which is unsupported.

**Comment by Shadowysn** [comment] 2024-04-29 08:12
What you're doing is using developer tools locked behind **sv_cheats**. These tools are never meant to be used in normal gameplay, thus there's no benefit to fixing these errors when the only way to cause them is cheat-marked console commands.

This would be a more fitting issue if you can reproduce this _without_ **sv_cheats** and the cheat-marked console commands.

**Comment by NULLYUKI** [comment] 2024-04-29 19:45
Since this issue requires the use of `noclip` to reproduce a issue that cannot be reproduced without the usage of cheat commands like `noclip` that will most likely not affect the gameplay of a player, the issue can be closed.

**Closed** 2024-04-30 12:41 UTC
Labels: Left 4 Dead 2
