### ISSUE TITLE
[HL:S] Tentacles deal no damage.

### ISSUE THREAD

**Issue by MarioGuy3** [ValveSoftware/Source-1-Games#1355] opened 2013-09-21 19:23 UTC
Hey, i only have to say that i am really proud of you finally converting this game to SteamPipe. I have read that many people are now having issues with this game, i only had a few which were mostly minor.

However, i just ran into so far the only major issue for me so far. I am in Blast Pit where you have to sneak past the Tentacles. The problem is that somehow the tentacles cannot deal any damage to any npcs or to me. Thus i am able to just walk past them without taking any damage, which eliminates the use of grenades to distract them. This completely takes out the challenge.

This also happens in one of the background maps.

If you could fix this i would be happy (i can wait).

Sorry if this already has been posted, i didn't have time to look that up.

Screenshot here: http://steamcommunity.com/sharedfiles/filedetails/?id=180305372

**Comment by kisak-valve** [comment] 2016-12-26 19:07
Closing as a duplicate of #1193.

**Closed by kisak-valve** 2016-12-26 19:07 UTC
Labels: Half-Life: Source, Reviewed
