### ISSUE TITLE
unlock mat_picmip (allow mat_picmip -10)

### ISSUE THREAD

**Issue by memmam** [ValveSoftware/Source-1-Games#3962] opened 2022-06-24 22:31 UTC
Surfacing this again since someone is actually working on TF2 again, main ticket is here: https://github.com/ValveSoftware/Source-1-Games/issues/699

**Comment by kisak-valve** [comment] 2022-06-24 22:41
Hello @memmam, please do not intentionally open duplicate issue reports. Closing as a duplicate of #699.

**Closed by kisak-valve** 2022-06-24 22:41 UTC

**Comment by memmam** [comment] 2022-06-24 23:32
Understood, I thought with 2,000 open issues and that one being opened in 2013 and not touched since 2019 it'd go unnoticed if I didn't surface it somehow, and it's something I think a lot of people would like to see fixed.
