### ISSUE TITLE
FastDL L4D

### ISSUE THREAD

**Issue by RaptorRU** [ValveSoftware/Source-1-Games#6311] opened 2024-08-27 15:47 UTC
Hello, can someone explain why the game client ignores loading bsp, nav files, namely maps from the web hosting? Although as far as I understand everything should work. Was Valve blocked or broken?
https://developer.valvesoftware.com/wiki/FastDL

**Comment by kisak-valve** [comment] 2024-08-27 15:55
Hello @RaptorRU, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #5099.

**Closed as not planned by kisak-valve** 2024-08-27 15:55 UTC
