### ISSUE TITLE
TF2 stutter Textures High + and HDR Full

### ISSUE THREAD

**Issue by PootisSpencer** [ValveSoftware/Source-1-Games#1928] opened 2015-10-28 19:31 UTC
I am having performance problems when I am using Source recommended settings. My framerate stays around 30 and I am expiriencing lag-like stuttering. Only game restart with settings set to not triggering my issue help.

My usual framerate is around 80+ @ 1080p.

Nvidia 355.11
Core i3 2100
8 GB RAM without swap partition
GTX 550 Ti 1GB (gf116/nvcf)
Any DE
Arch Linux/Ubuntu/Manjaro - I can bet it would be triggered on any distro.

Steps to reproduce:
1. Fire up tf2
2. Make sure that Textures are set to High or more.
3. Set HDR to full.
4. Launch for example pl_frontier_final
5. Watch stutter fest.

Textures set to medium will not trigger mentioned issue, same with HDR set to Bloom with Textures set to High and up.

Any suggestions ? I've been redirected from Steam support as it seemed more reasonable way to approach devs in Steam Support guy's mind ;)

https://gist.github.com/PootisSpencer/658544f8cf77a58c0449#file-console-log
https://gist.github.com/PootisSpencer/31615ebd4e9c756e3827
https://gist.github.com/PootisSpencer/a72444e43ce46adba0ef

console.log is month old but should be still relevant

**Comment by kisak-valve** [comment] 2016-12-30 16:00
Closing as a duplicate of #23.

**Closed by kisak-valve** 2016-12-30 16:00 UTC
