### ISSUE TITLE
L4D2 closes when try to connect to a server on Linux

### ISSUE THREAD

**Issue by bkdwt** [ValveSoftware/Source-1-Games#5571] opened 2024-03-16 22:46 UTC
I am facing an issue with L4D2 on Ubuntu 23.10.1. When I try to connect to a server, the game automatically closes when the connection progress bar fills up completely. Regardless of whether mods are active or not, the same error occurs. This problem does not happen on Windows.

I have reinstalled the game, but the problem persists. I have tested both the Flatpak version and the native Steam version, and the issue occurs in both. This problem does not happen in single player mode.

Here the dump bellow:

[crash_20240316193029_3.zip](https://github.com/ValveSoftware/Source-1-Games/files/14625471/crash_20240316193029_3.zip)

**Comment by Tsuey** [comment] 2024-03-17 03:59
Hey, think this report could be related? https://github.com/Tsuey/L4D2-Community-Update/issues/490

Single player working makes me wonder if it's a SourceMod plugin running on the server causing the issue?

**Comment by bkdwt** [comment] 2024-03-17 19:24
> Hey, think this report could be related? [Tsuey/L4D2-Community-Update#490](https://github.com/Tsuey/L4D2-Community-Update/issues/490)
> 
> Single player working makes me wonder if it's a SourceMod plugin running on the server causing the issue?

I think this is related. Also, I have tried to connect in another server and works like a charm but there's another server (not the first) when I tried to connect, the same problem happened.

The worst of all is that there is no way of knowing what these servers have to cause this problem in the Linux version of the game. Maybe this a thing to Valve investigate.

**Comment by Tsuey** [comment] 2024-03-18 01:25
> The worst of all is that there is no way of knowing what these servers have to cause this problem in the Linux version of the game. Maybe this a thing to Valve investigate.

I'd have to guess it's a plugin related to entity spawning or file handling, given the full progress bar / Linux being paranoid; so `cl_allowdownload 0` `cl_downloadfilter none` would help rule out file stuff.

Unfortunately I think the only way to go about this would be to join a few dozen servers and document which IP's cause the Linux crash, and which don't. Then on Windows, join them again and use `sm plugins all` to copy the listing of all plugins active on each server. Then those can be compared to find the outliers, and narrowed down to the offending plugin from there.

**Comment by kisak-valve** [comment] 2024-03-18 02:46
(Responding to https://github.com/ValveSoftware/Source-1-Games/issues/5504#issuecomment-2002718784) Hello @Tsuey, re-reading this issue report and #5504, this is a duplicate of the older issue report, not the other way around. Since the discussion here adds a bit of value, I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Source-1-Games/issues/5504#issuecomment-2002776003.

Closing in favor of the older issue report.

**Closed by kisak-valve** 2024-03-18 02:46 UTC
Labels: Linux, Left 4 Dead 2
