### ISSUE TITLE
[TF2] War Paint Albedo Tint Bug

### ISSUE THREAD

**Issue by bobatealee** [ValveSoftware/Source-1-Games#3951] opened 2022-06-24 07:15 UTC
There's a long-standing bug in TF2 regarding Strange Stat Clocks and War Paints (as well as Decorated weapons) that have albedo tints, such as the somewhat-recently-added Broken Bones War Paint. If a War Painted weapon has a shiny skin and a Strange Stat Clock, the shininess will fail to show on the weapon's view model. However, the shininess displays as normal on the weapon's world model. Attached is an image that outlines this issue.

Normal War Painted weapons use a material like this:
`materials/models/weapons/c_models/c_rocketlauncher/c_rocketlauncher.vmt`

When a War Paint is shiny, the game overrides that material with a material that has self-illumination properties that let it shine:
`materials/models/paintkits/macaw/c_rocketlauncher.vmt`

Due to some code bug, this material override for shiny War Paints does not function correctly on the weapon's view model when a Strange Stat Clock is attached. Instead, the game will fall back on the normal, non-shiny counterpart.

![albedotintbug](https://user-images.githubusercontent.com/44716190/175483214-388de92a-1dbc-4ad8-891e-6678861453ce.png)

**Comment by agrastiOs** [comment] 2022-06-24 08:50
It's not just albedo tint. First-person viewmodels with a stat clock get their entire special skin materials overwritten.

**Comment by kisak-valve** [comment] 2022-06-24 12:39
Hello @bobatealee, this reads like a duplicate of #3278. Closing in favor of the older issue report.

**Closed by kisak-valve** 2022-06-24 12:39 UTC
