### ISSUE TITLE
[Linux] [Portal] Cannot use xbox360 gamepad

### ISSUE THREAD

**Issue by ribalda** [ValveSoftware/Source-1-Games#1931] opened 2015-11-02 10:06 UTC
have used with no problem the gamepad on other games: LFD2, big picture, truck simulator...., but it not detected by Portal.
- If I cat /dev/js0 and move the pad I see raw data moving
- going to the game console and execute run 360controller, or 360controller-linux does nothing.

How can I debug this? Why other steam source (LFD2) games work and this doesn't. What library are you using to handle the js?

**Comment by kisak-valve** [comment] 2016-12-30 16:09
Closing as a duplicate of #1842.

**Closed by kisak-valve** 2016-12-30 16:09 UTC
