### ISSUE TITLE
[HLDMS]Trigger_push- on "snarkpit" level disabled (no push)

### ISSUE THREAD

**Issue by 1157** [ValveSoftware/Source-1-Games#1488] opened 2013-10-18 13:52 UTC
Trigger_push- on "snarkpit" level disabled (no push)

**Comment by kisak-valve** [comment] 2016-12-27 19:43
Closing do to lack of information, possibly a duplicate of #1368.

**Closed by kisak-valve** 2016-12-27 19:43 UTC
Labels: Half-Life Deathmatch: Source

**Comment by 1157** [comment] 2016-12-27 23:19
My bad, the fan @ 1086 -555 -1500  when you press func_button on wall it turns on a fan and activates
a trigger_push at same co-ords
