### ISSUE TITLE
some maps have their lighting broken going through all the updates of tf2, lets fix that

### ISSUE THREAD

**Issue by hourai-branch** [ValveSoftware/Source-1-Games#6256] opened 2024-08-07 11:41 UTC
Updates broke Team fortress 2's lighting in some maps, and i fixed it for 2Fort at least.

Basically i want to let the Dev team know via this GitHub page because the workshop isn't gonna get this done I've seen. its such a minor QOL fix that the mass voting system wouldn't make sense. people would go for the new shiny maps anyways because a graphics fix hardly changes up any gameplay.
I like having some graphics fixed into tf2.

### 2fort fix
Here is my fix: https://steamcommunity.com/sharedfiles/filedetails/?id=3304530685
(This is the fix on GitHub as an alternative to using the steam workshop (GitHub doesn't support .BSP uploads): [ctf_2fort fixed.zip](https://github.com/user-attachments/files/16522726/ctf_2fort.fixed.zip))
![steamuserimages-a akamaihd2](https://github.com/user-attachments/assets/8bc16abc-cfb7-43de-ab57-be5253938a09)
![steamuserimages-a akamaihd3](https://github.com/user-attachments/assets/d1b0125a-19db-4bbd-bf81-deac3254d7af)

I hope this will get implemented into tf2.

### This is how i fixed 2fort's lighting:

1. Downloaded a steam depot of tf2 from before 2fort's lighting broke.
2. Used [compilepal](https://github.com/ruarai/CompilePal) to rebuild the pre-steampipe 2fort version's cubemaps to work post steampipe.
3. Bam, lighting fixed.

### Nice things about using this approach:

1. It can be done as a batch process
### Drawbacks using this approach:

1. Map must be unmodified after the update that broke it, or else you will get an old fixed version.
2. This doesnt really fix the .VTFs, i just hope valve has a decompilation tool for making edits after fixing. (or an old / original unbroken vtf idk)

### Final word (for now)
Please list all maps that have broken lighting, and I'll hope i can fix them if drawback #1 isn't applicable. If you have better approach please post it as a reply.

**Comment by NULLYUKI** [comment] 2024-08-07 11:43
Possible duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/6250 ?

**Comment by kisak-valve** [comment] 2024-08-07 11:48
Hello @BlazingRush, as @NULLYUKI noted, this looks like a duplicate of #6250. Closing in favor of the older issue report.

**Closed as not planned by kisak-valve** 2024-08-07 11:48 UTC
