### ISSUE TITLE
Bluetooth Earbuds with no Audio after reconnect

### ISSUE THREAD

**Issue by davidcc73** [ValveSoftware/Source-1-Games#5880] opened 2024-04-22 21:52 UTC
When using Bluetooth earbuds on Windows 11 to play the game they work fine, if the earbuds disconnect and then reconnect to the PC the game's audio does not go back to the earbuds until the game is restarted with the earbuds already connected, instead the audio will come out of the PC's default speakers.

**Comment by NULLYUKI** [comment] 2024-04-22 21:54
In case this issue occurs in TF2, then this is a duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/5864

**Comment by davidcc73** [comment] 2024-04-22 22:43
yes it is tf2, but the problem persists after the last update, it started with the 64-bit update.

**Comment by kisak-valve** [comment] 2024-04-22 22:48
Hello @davidcc73, this issue is already being tracked at #5694 / #5864. Closing as a duplicate.

**Closed by kisak-valve** 2024-04-22 22:48 UTC
Labels: Audio, Windows
