### ISSUE TITLE
[TF2] sv_pure 1/2 custom sound issues

### ISSUE THREAD

**Issue by Wasmanr2** [ValveSoftware/Source-1-Games#2171] opened 2017-02-24 06:19 UTC
Playing on a sv_pure 1/2 server while using custom sounds causing horrible scratch sounds ingame.

Example:

Using custom sounds: 
- for demopipes or rocketlauncher causes when the projectiles getting fired a scratch sound.
- for medipacks/ammopacks causes scratch sound

its related to #2078 where i suggested that the stock models/textures should load instead of the custom ones without breaking custom user content and crashing on sv_pure 1/2.

If wanted i can provide a proof with the sound problem and the crash with custom models/textures.

**Comment by kisak-valve** [comment] 2017-02-24 14:47
Closing as a duplicate of #1635.

**Closed by kisak-valve** 2017-02-24 14:47 UTC

**Comment by Ashetf2** [comment] 2023-10-17 22:37
This issue was not a duplicate. OP probably refers to this

I have a custom footstep sounds mod, and when joining a sv_pure 1 server (Casual), footstep sounds don't play at all. Some sounds may or not be played, it seems to be random

https://github.com/ValveSoftware/Source-1-Games/assets/63692647/bb79a57c-5b0f-4f7a-9bd5-211570d03c1f

After using snd_restart, the scratch sounds play for some footsteps, again, it seems to be random

https://github.com/ValveSoftware/Source-1-Games/assets/63692647/0d979eee-f386-4fa8-9d39-e08f2b84d76d

This is surely an issue with sound cache.
