### ISSUE TITLE
[TF2] Disconnect command triggers rejoin dialog for casual matches

### ISSUE THREAD

**Issue by echaskaris** [ValveSoftware/Source-1-Games#4500] opened 2022-11-08 20:42 UTC

**Comment by kisak-valve** [comment] 2022-11-08 22:13
Hello @echaskaris, without a better description, this issue reads like a duplicate of #2821. Closing in favor of the older issue report.

**Closed by kisak-valve** 2022-11-08 22:13 UTC

**Comment by echaskaris** [comment] 2022-11-09 11:48
Yes it's duplicate
