### ISSUE TITLE
Pelican peak VSH glitch

### ISSUE THREAD

**Issue by Turbogrease** [ValveSoftware/Source-1-Games#5029] opened 2023-07-13 02:43 UTC
When you load of a map of pelican peak or any of the new maps it has the ready up system of the VSH Gamemode

![image_2023-07-12_224310703](https://github.com/ValveSoftware/Source-1-Games/assets/139408805/aaf2472b-fc9a-4806-94f5-a7c6829515dd)

**Comment by rabscootle** [comment] 2023-07-13 03:24
Duplicate of #5027 

Bug is normal behavior after user has played a match on official servers. It's a side effect from their use of tournament mode features.

**Comment by kisak-valve** [comment] 2023-07-13 12:20
Closing as a duplicate.

**Closed by kisak-valve** 2023-07-13 12:20 UTC
