### ISSUE TITLE
[FEATURE REQUEST] Source SDK tools for Mac/Linux users?

### ISSUE THREAD

**Issue by Popo12a** [ValveSoftware/Source-1-Games#3261] opened 2020-05-14 12:34 UTC
I used to make skins and maps for gmod, csgo, and a bunch of other source games. Unfortunately, I switched to Mac OS because my old windows laptop broke. I’ve seen threads about wine skin or dual boots for the sdk but that would mean redownloading the same game files, taking up a lot of space. I’m sure there are a lot of modders who’d be happy to see a properly ported sdk tools for Linux/Mac without having to use emulators or partition a part of their drives for windows os.

**Comment by kisak-valve** [comment] 2020-05-14 12:38
Hello @Popo12a, this is a duplicate of https://github.com/ValveSoftware/source-sdk-2013/issues/141, which was effectively answered at https://github.com/ValveSoftware/source-sdk-2013/issues/141#issuecomment-22062601.

**Closed by kisak-valve** 2020-05-14 12:38 UTC
