### ISSUE TITLE
[TF2] 64 bit - Duck journal only quacks half the time its used.

### ISSUE THREAD

**Issue by Xilekai** [ValveSoftware/Source-1-Games#5927] opened 2024-04-27 07:08 UTC
The console will usually say something along the lines of 
*** Invalid sample rate (0) for sound ')ambient_mp3\bumper_car_quack2.mp3'.
and it'll just be pure silence. I don't know how it broke with the update but it definitely did.

additionally, there's a lot of 
*** Invalid sample rate (0) for sound 'vo\null.mp3'.
in my console too since the update. No clue why.

![wtf](https://github.com/ValveSoftware/Source-1-Games/assets/163775739/abcdb03e-fc83-4d43-acaf-bcf8f8769071)

**Comment by JoriKos** [comment] 2024-04-27 09:43
Duplicate of #5685

**Comment by kisak-valve** [comment] 2024-04-27 12:24
Hello @Xilekai, as @JoriKos noted, this issue is already being tracked at #5685. Closing as a duplicate.

**Closed by kisak-valve** 2024-04-27 12:24 UTC
