### ISSUE TITLE
[TF2] Various lines for Spy's Kazotsky Kick are mislabeled/broken

### ISSUE THREAD

**Issue by Bumbo-Walrusoni** [ValveSoftware/Source-1-Games#5418] opened 2024-01-17 21:39 UTC
Currently, when doing the Kazotsky Kick as Spy, the game sometimes pumps out an error into the console saying that it cannot find a specific line. Found in game_sounds_vo_taunts, it also shows that there are approximately 3 lines that are unused.

For one of them, the incorrect file location is used. It is mistakenly mislabeled as "vo/taunts/spy/spy_laughhappy02.mp3", instead of where it actually is, which is "vo/spy_laughhappy02.mp3". Fixing this allows the line to properly play.

For the last two, the game doesn't seem to properly register "spy_taunt_russian_rand", as both lines either just don't play entirely or spews out an error into the console. Despite this error, one of the lines is still inlined (hopefully that's the right term) incorrectly. To fix this, simply hit Tab 2 times to align it with the line above it.
Even though that error is corrected, the line still refuses to play properly. I don't know why, so I just made all four lines available for each of them, the fix I did is pasted below for easy copy-pasting. Doing this not only fixes the errors from showing, but also makes two unused lines that are intended to be heard during this play properly. If you're able to see why it's not being received in the code itself, see the above two solutions and disregard the lazy copy and paste route.

```
"spy_taunt_russian_rand"
{
	"channel" 			"CHAN_VOICE"
	"volume" 			"VOL_NORM"
	"pitch" 			"PITCH_NORM"
	"soundlevel" 		"SNDLVL_95dB"
	"rndwave"
	{
		"wave"			"vo/taunts/spy/spy_tnt_dosido_init04.mp3"
    		"wave"			"vo/taunts/spy/spy_tnt_nutkick_kick04.mp3"
		"wave"			"vo/taunts/spy/spy_tnt_nutkick_kick03.mp3"
    		"wave"			"vo/spy_laughhappy02.mp3"
	}
}

"spy_taunt_russian_rand2"
{
	"channel" 			"CHAN_VOICE"
	"volume" 			"VOL_NORM"
	"pitch" 			"PITCH_NORM"
	"soundlevel" 		"SNDLVL_95dB"
	"rndwave"
	{
		"wave"			"vo/taunts/spy/spy_tnt_dosido_init04.mp3"
    		"wave"			"vo/taunts/spy/spy_tnt_nutkick_kick04.mp3"
		"wave"			"vo/taunts/spy/spy_tnt_nutkick_kick03.mp3"
    		"wave"			"vo/spy_laughhappy02.mp3"
	}
}
```
For reference, here is what it currently looks like:

```
"spy_taunt_russian_rand"
{
	"channel" 			"CHAN_VOICE"
	"volume" 			"VOL_NORM"
	"pitch" 			"PITCH_NORM"
	"soundlevel" 		"SNDLVL_95dB"
	"rndwave"
	{
		"wave"			"vo/taunts/spy/spy_tnt_dosido_init04.mp3"
    "wave"			"vo/taunts/spy/spy_tnt_nutkick_kick04.mp3"
	}
}

"spy_taunt_russian_rand2"
{
	"channel" 			"CHAN_VOICE"
	"volume" 			"VOL_NORM"
	"pitch" 			"PITCH_NORM"
	"soundlevel" 		"SNDLVL_95dB"
	"rndwave"
	{
	  "wave"			"vo/taunts/spy/spy_tnt_nutkick_kick03.mp3"
    "wave"			"vo/taunts/spy/spy_laughhappy02.mp3"
	}
}
```

**Comment by NULLYUKI** [comment] 2024-07-18 19:15
According to patch [223066](https://www.teamfortress.com/post.php?id=223066)
>Fixed missing Spy audio when using the Taunt: Kazotsky Kick

This needs to be retested.

**Comment by Sae35** [comment] 2024-07-19 05:04
> According to patch [223066](https://www.teamfortress.com/post.php?id=223066)
> 
> > Fixed missing Spy audio when using the Taunt: Kazotsky Kick
> 
> This needs to be retested.

I just tested it, seems to be working as intended on my end at least.

**Comment by kisak-valve** [comment] 2024-08-23 21:18
Closing per the last couple comments.

**Closed by kisak-valve** 2024-08-23 21:18 UTC
Labels: Team Fortress 2, Audio, Need Retest
