### ISSUE TITLE
[Portal-Linux] Language problem in Linux 

### ISSUE THREAD

**Issue by queenmedley** [ValveSoftware/Source-1-Games#1958] opened 2016-02-10 16:27 UTC
Steam is working on Archlinux and steam interface language is set to Korean.
When start portal, there is no menu button to start or click... even '[]', completly no letter.
So tried to change steam interface langange from Korean to English, then I can see menu and start game.
But when setting portal game language to korean, still can't see korean menu and subtitel.. only show English. not chanage game language.
It seems that locale setting on linux is not related, but steam interface language setting is.
I saw other screen caputer in korean languge in windows.
Steam portal doesn't support other language on Linux??
It is annoying  to change steam language set from Korean to English every time play portal
and to read English in Game. I am not good at English to read English quickly in Game.
- I installed steam font and  wqy-zenhei font, so can see korean other steam game, ex, CS or LF4D2

![portal](https://cloud.githubusercontent.com/assets/16573046/12953410/b08eeebc-d05d-11e5-8e5c-e467ac98c3ed.png)

**Comment by queenmedley** [comment] 2016-02-11 06:11
I got anwser from steam community.
http://steamcommunity.com/app/400/discussions/0/412446292775908119/

**Comment by kisak-valve** [comment] 2016-12-30 18:47
Closing as a duplicate of #153.

**Closed by kisak-valve** 2016-12-30 18:47 UTC
