### ISSUE TITLE
TF2 | Desk engineer shirt becomes black on certain angles/positions

### ISSUE THREAD

**Issue by BurntRanch** [ValveSoftware/Source-1-Games#6213] opened 2024-07-27 09:26 UTC
If an Engineer wears the Desk Engineer, and turn to specific angles infront of a viewer, the viewer sees their shirt to be black.
I should note, I am a Linux player, running on NVIDIA (GTX 1650) driver version 555.58.02

Video: 

https://github.com/user-attachments/assets/eaec3586-86e0-4880-ab46-d981517e1c84

Demo: 
[demo.zip](https://github.com/user-attachments/files/16398832/demo.zip) (highlight starts at tick 32000)

I haven't tested different video settings, these are my settings:
![image](https://github.com/user-attachments/assets/87a83dac-7bee-48c0-8738-a655a4daaa26)

**Comment by BurntRanch** [comment] 2024-07-27 09:26
* I didn't look closely into the shirt, I know it's not a jacket.

**Comment by JoriKos** [comment] 2024-07-27 10:31
Duplicate of #4220

**Comment by kisak-valve** [comment] 2024-07-27 12:42
Hello @BurntRanch, as @JoriKos noted, this looks like a duplicate of #4220. Since your issue report adds some more details, I've gone ahead and transferred it to https://github.com/ValveSoftware/Source-1-Games/issues/4220#issuecomment-2254139235.

**Closed as not planned by kisak-valve** 2024-07-27 12:42 UTC
