### ISSUE TITLE
[TF2] [Bug] Reflect rollers do fully critical damage to the Pyro

### ISSUE THREAD

**Issue by aeoncleanse** [ValveSoftware/Source-1-Games#2394] opened 2017-11-02 01:27 UTC
Confirmed working with Grenade Launcher and Iron Bomber. If a Pyro reflects a roller from either weapon, it changes colour and won't affect the team, but it deals fully critical damage and knockback to the Pyro. This makes it extremely dangerous to help your team by clearing rollers, as it usually results in heavy damage to or death of the Pyro. 

This bug was introduced some years ago in (I think) the same patch which nerfed the Powerjack heal from 75 to 25.

**Comment by aeoncleanse** [comment] 2017-11-02 01:32
@kisak-valve - Github moderator. Does this mean you're a Valve employee paid to focus on their github projects, are you a volunteer, or does this form just a part of your usual duties?

**Comment by mastercoms** [comment] 2023-04-10 06:43
Duplicate of #4298 which is more accurate about the problem

**Comment by kisak-valve** [comment] 2023-04-10 12:18
Closing in favor of #4298.

**Closed by kisak-valve** 2023-04-10 12:18 UTC
Labels: Team Fortress 2
