### ISSUE TITLE
[TF2] Strange Count Transfer Tools don't let you transfer scores onto or from Botkiller weapons

### ISSUE THREAD

**Issue by IronFoxGaming** [ValveSoftware/Source-1-Games#6881] opened 2024-12-17 00:19 UTC
For some reason, the Strange Count Transfer Tool does not behave right for Botkiller weapons. Transferring kills between two botkillers of the exact same weapon doesn't work, as the game apparently treats every different form of botkiller (Diamond, Carbonado, Gold, Blood, Rust, and Silver) as its own type of weapon. It might possibly allow transferring between the same weapon and same botkiller tier, but it should realistically work with all versions of the same weapon.

**Comment by kisak-valve** [comment] 2024-12-17 01:06
Hello @IronFoxGaming, this issue looks like a duplicate of #2017. Closing in favor of the older issue report.

**Closed as not planned by kisak-valve** 2024-12-17 01:06 UTC

**Comment by jh34ghu43gu** [comment] 2024-12-17 03:35
@kisak-valve this is a new issue, #2017 seems to request a new item that does something like

Scattergun 1 has 20 kills and strange part snipers killed with a count of 3
Scattergun 2 has 10 kills no parts
Use tool to transfer 1 -> 2
Scattergun 1 becomes a 0 kill strange
Scattergun 2 now has 30 kills and a strange part snipers killed with a count of 3

Or they are requesting if both scatterguns have sniper kill parts that the 3 would be added to scattergun 2 but that's already what the transfer tool does so I think they are asking for the example I gave.


This issue is asking that different botkillers can be used with the transfer tool, but that appears to already be the case so I don't think it needs reopened anyway? @IronFoxGaming elaborate if possible.

![image](https://github.com/user-attachments/assets/d428b8fa-b712-4b2c-83cc-b3b45edddb25)

If this did need fixed they would need to use the same xifier_class_remap attribute but they already have that attribute:
![image](https://github.com/user-attachments/assets/c76b25e1-5517-49bd-be2f-dc528ff93a0d)

**Comment by IronFoxGaming** [comment] 2024-12-19 01:05
My apologies, my partner was having trouble trying to move kills from a carbonado botkiller scattergun to a golden botkiller scattergun, as whenever they opened the menu for it, it would have the "Yep, I'm sure!" button grayed out and both weapon slots empty. Turns out neither of us knew we had to click on the boxes on either side to select a weapon for them, as it doesn't have any labels or hints telling you to do so. We just found out while I was trying to get them to send me a screenshot of what was happening on their end. The feature works perfectly fine, so this issue doesn't have any reason to stay open. Sorry for the trouble with this.
