### ISSUE TITLE
[CS:S] [Request] Enable game_text & env_message

### ISSUE THREAD

**Issue by Cx1** [ValveSoftware/Source-1-Games#868] opened 2013-06-03 09:29 UTC
Hello, I realized that game_text & env_message can be re-enabled by a simple line in the file <i>resource/clientscheme.res</i>. Everything is already there and well implemented but is missing the following lines under <b>fonts</b>:

```
        "CenterPrintText"
        {
            // note that this scales with the screen resolution
            "1"
            {
                "name"      "Trebuchet MS"
                "tall"      "18"
                "weight"    "900"
                "antialias" "1"
                "additive"  "1"
            }
        }
```

Taken directly from Portal. I am not the one to discover this as doing a search leads to a [thread on the steam forums](http://forums.steampowered.com/forums/showthread.php?p=22516267) dating back from May, 2011. An example map can be downloaded from the thread with further details. 

I am including [my own example map and latest clientscheme.res](http://www.mediafire.com/download/m3fp0oexy3leaxe/game_text_example.zip) with the CenterPrintText line added along with the Valve Map File. It's really just that line that needs to be added for all this to work.

![2013-06-03_00003](https://f.cloud.github.com/assets/4202270/598485/afc5fa9c-cc2e-11e2-904e-8d85cbf0b153.jpg)
![2013-06-03_00004](https://f.cloud.github.com/assets/4202270/598487/afcc6a8a-cc2e-11e2-9b58-d18f43b48dde.jpg)
![2013-06-03_00005](https://f.cloud.github.com/assets/4202270/598486/afc6d462-cc2e-11e2-8827-8508be52b6c4.jpg)

**Comment by kisak-valve** [comment] 2016-12-23 18:12
Closing as a duplicate of #2.

**Closed by kisak-valve** 2016-12-23 18:12 UTC
Labels: Counter-Strike: Source, Feature Request, Reviewed
