### ISSUE TITLE
[Source-1 games] Brightness slider does nothing

### ISSUE THREAD

**Issue by pizzadox11** [ValveSoftware/Source-1-Games#3767] opened 2021-12-23 16:27 UTC
This issue still exists im on AMD 270X
https://github.com/ValveSoftware/Source-1-Games/issues/3371

I noticed only on some very rare occasions the slider actually works

**Comment by kisak-valve** [comment] 2021-12-23 16:52
Hello @pizzadox11, please do not intentionally open duplicate issue reports. Closing as a duplicate of #3371.

**Closed by kisak-valve** 2021-12-23 16:52 UTC
