### ISSUE TITLE
[L4D1] DDOS Attack to official servers

### ISSUE THREAD

**Issue by axelnieves2012** [ValveSoftware/Source-1-Games#5595] opened 2024-04-06 04:16 UTC
Somebody is DDOS-ing Left 4 Dead 1 official servers 24/7.
Everytime somebody tries to play on any server, a DDOS attack is triggered within 30 seconds - 2 minutes.
It occurs on Chile, Peru and US East servers. I have not tested more locations, i am from Argentina, I play on chile servers.

Host locally does not work always because of "No Steam Logon" bug which is from 2008 and has been  never fixed.

I cannot do anything because I dont own Valve Left 4 Dead Dedicated Servers.
Please, install an anti DDOS system or something. Hackers don't let us play.
I have already reported this on Steam and they told me to post it here.

**Comment by gaelcoral** [comment] 2024-04-08 16:16
I can confirm that it also happens on the US West servers.

**Comment by Diggingwolf2605** [comment] 2024-05-03 10:47
This issue seems to be fixed for now. I haven't noticed any new attacks since the latest update.

**Comment by kisak-valve** [comment] 2024-06-08 01:09
Closing per the last comment.

**Closed by kisak-valve** 2024-06-08 01:09 UTC
Labels: Need Retest
