### ISSUE TITLE
[Portal] Portal 1 's font could not display properly on Linux 

### ISSUE THREAD

**Issue by imsuwj** [ValveSoftware/Source-1-Games#1939] opened 2015-11-29 06:06 UTC
OS: ArchLinux
I have installed ttf-liberation,wqy-microhei and wqy-zenhei.
No matter what language I set , the problem still.
Even English display as a square symbol.
![Language](https://cloud.githubusercontent.com/assets/2463831/11455419/8ea4494e-9699-11e5-8910-f1a402aab383.png)

![Snapshot screen](https://cloud.githubusercontent.com/assets/2463831/11455406/ea83452c-9698-11e5-9d92-dc2cf834423f.png)

Dota2 Reborn and TF2 do not have any problems with font on my system.

Do I need any other font ?

**Comment by MRebhan** [comment] 2016-03-08 19:45
I have the following "ttf-*" fonts installed:
ttf-arphic-uming 0.2.20080216.1-5
ttf-dejavu 2.34-2
ttf-droid 20121017-4
ttf-liberation 2.00.1-6
ttf-oxygen 1:5.4.3-1
Try installing ttf-dejavu and ttf-droid and if that does not work, maybe ttf-oxygen

**Comment by kisak-valve** [comment] 2016-12-30 18:46
Hello @imsuwj, 
```
1.) Make sure to install libfontconfig:i386
2.)
rm $HOME/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libfontconfig.so.1

ln -s /usr/lib/i386-linux-gnu/libfontconfig.so.1 $HOME/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libfontconfig.so.1

3.)
rm $HOME/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libfontconfig.so.1

ln -s /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 $HOME/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libfontconfig.so.1

4.) Re-start Steam!
```
from http://steamcommunity.com/app/400/discussions/0/412446292775908119/#c412446890548360625 should workaround the issue.

Closing as a duplicate of #153.

**Closed by kisak-valve** 2016-12-30 18:46 UTC
Labels: Font, Linux, Localization, Portal
