### ISSUE TITLE
[SDK 2013 SP/MP] increase entities limits. (PLEASE READ)

### ISSUE THREAD

**Issue by Unusuario2** [ValveSoftware/Source-1-Games#5462] opened 2024-01-30 14:35 UTC
Nowadays what limits modders the most is the entity limits, it would be very nice if these are high up (8192). 
A lot of branches in the source engine have done this like, gmod, portal 2, strata source engine, blackmesa, ect..
Also increase the entities limti would be very esay and does not break the bsp or the engine it self.
how to increase the entite limit it self.   
Go to (fullsource code)/public and open const.h then find :

```
// How many bits to use to encode an edict.
#define	MAX_EDICT_BITS				11			// # of bits needed to represent max edicts
// Max # of edicts in a level
#define	MAX_EDICTS					(1<<MAX_EDICT_BITS)
```

reewrite to:
` #define	MAX_EDICT_BITS				11`	(these defines 4096 entities in binary) (original)
` #define	MAX_EDICT_BITS				12`	(these defines 8192 entities in binary) (new)

And thats it, compile it and upload to steam. (the build will be stable, you should not raise more than 8192 entites from my own tests) 

If possible also update these limits (public/bspfile.h):
`#define	MAX_MAP_MODELS					1024` (original)
`#define	MAX_MAP_BRUSHES					8192` (original)
`#define MAX_MAP_DISPINFO				                2048` (original)
update to:
`#define	MAX_MAP_MODELS					2048 or 4096` (less stable) (new limit)
`#define	MAX_MAP_BRUSHES					16384` (new limit)
`#define MAX_MAP_DISPINFO				                8192` (new limit)

If increased these limits, those don't break the compatibility of the bsp in the engine, so they are fine to increase. 
It would make job of the modders MUCH MUCH EASIER.

**Comment by kisak-valve** [comment] 2024-01-30 14:52
Hello @Unusuario2, please do not intentionally open duplicate issue reports.

Closing as a duplicate of https://github.com/ValveSoftware/source-sdk-2013/issues/573.

**Closed by kisak-valve** 2024-01-30 14:52 UTC

**Comment by Unusuario2** [comment] 2024-01-30 14:55
Sorry because the sdk 2013 repository does not receive updates, I thought putting it here would be seen. 
Is it posible to do it? at least the entitie limit increase
