### ISSUE TITLE
TF2 disables py primary monitor in linux everytime I try to launch

### ISSUE THREAD

**Issue by SteamRex25** [ValveSoftware/Source-1-Games#5933] opened 2024-04-28 02:06 UTC
I am using opensuse linux with proton 8 and TF2 seems to always disable my primary monitor and then crash whenever I try to play it, please help.

**Comment by NULLYUKI** [comment] 2024-04-28 02:07
Duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/5704

**Comment by kisak-valve** [comment] 2024-04-28 12:59
Hello @SteamRex25, running Team Fortress 2 with Proton is not supported on this issue tracker. You can use the compatibility report at https://github.com/ValveSoftware/Proton/issues/3150 to discuss in an unofficial capacity how the game behaves with Proton.

As @NULLYUKI noted, the Linux native variant of this issue is being tracked at #5704.

**Closed by kisak-valve** 2024-04-28 12:59 UTC
