### ISSUE TITLE
[TF2] classic_rocket_trail.pcf not in particles manifest.

### ISSUE THREAD

**Issue by StrikerMan780** [ValveSoftware/Source-1-Games#2606] opened 2018-05-27 23:05 UTC
Seems classic_rocket_trail.pcf isn't in the particles manifest. It should be added, and those effects used for the Quake Original rocket launcher. If you decide to not use them for the original, add them to the manifest anyway, because modders like myself can use them to great effect.

Simply add
```
"file"		"!particles/classic_rocket_trail.pcf"
```
To particles_manifest.txt

**Comment by kisak-valve** [comment] 2018-05-28 12:52
Closing as a duplicate of #1615.

**Closed by kisak-valve** 2018-05-28 12:52 UTC
Labels: Feature Request, Team Fortress 2
