### ISSUE TITLE
[HL2] Major Lighting bug

### ISSUE THREAD

**Issue by kilbith** [ValveSoftware/Source-1-Games#1887] opened 2015-05-19 18:02 UTC
I play Half-Life 2 through Steam, Lubuntu 15.04 64 bits, with an integrated GPU Intel GMA 4500 and 4 GB RAM.
Frequently, the "ambient lighting" just got disabled.

Screenshots speak better than 1000 words...
#### Ravenholm

![2015-05-19_00003](https://cloud.githubusercontent.com/assets/7883281/7710044/720b1ee6-fe61-11e4-92ff-2f7b0ec34760.jpg)
#### Nova Prospekt

![2015-05-19_00002](https://cloud.githubusercontent.com/assets/7883281/7710056/8078fffc-fe61-11e4-82a4-fcd35674d02a.jpg)
#### Our Benefactors

![2015-05-19_00001](https://cloud.githubusercontent.com/assets/7883281/7710065/909d5f9a-fe61-11e4-8eed-d19af18f1656.jpg)

Thanks to consider it.

**Comment by dscharrer** [comment] 2015-05-19 19:27
Do you have HDR turned off?

Looks like a dupe of issue #577

**Comment by kilbith** [comment] 2015-05-19 19:58
@dscharrer Yes, HDR is turned off.

**Comment by kisak-valve** [comment] 2016-12-22 19:24
Closing as a duplicate of #577.

**Closed by kisak-valve** 2016-12-22 19:24 UTC
