### ISSUE TITLE
[TF2] [Feature Request] Remove all code related to -textmode in TF2

### ISSUE THREAD

**Issue by Ashetf2** [ValveSoftware/Source-1-Games#4475] opened 2022-11-02 19:35 UTC
This issue was closed before for no reason, so I'm creating this new issue. `-textmode` allows clients to run Source games without rendering any graphics to save memory. CS:GO used to have textmode compatibility, but it was removed at some point to stop users from abusing it. The same should be done to TF2.

There is no legit reason to use this parameter, not even for debugging. If you find "textmode" in Google you will only find cheat repos and forums.

Also, there may be some other parameters that needs to be revised. 
`-noshaderapi`: Effectively disables shader and texture loading completely. Doesn't let you open CS:GO directly. 
`-small`: Allows for resolutions smaller than 640x480. Very small values crashes the game.

**Comment by AzureAzel** [comment] 2022-11-02 22:25
I removed the previous issue as I became aware that removing textmode will not stop people from hosting bots in TF2. There will always be another way. Removing it won't really change much in the long run.

**Comment by Doclic** [comment] 2022-11-03 01:20
> I closed the previous issue as I became aware that removing textmode will not stop people from hosting bots in TF2. There will always be another way. Removing it won't really change much in the long run.

The main issue is likely just-disable-vac-tf (which apparently works on other games too)
And if cheats do use textmode, removing it will at least prevent bots from running for some time, which is always nice.

**Comment by TF2CutContentWiki** [comment] 2022-11-08 12:05
It may also prevent legitimate trade site bots from working, but hey, at least someone heard [my suggestion about removing textmode](https://twitter.com/TF2CCWiki/status/1530310298380521473?t=wL09BpA8fo_mTdsBvXZ0FQ&s=19).

**Comment by Ashetf2** [comment] 2022-11-10 00:36
@TF2CutContentWiki CS:GO also has trade bots and it doesn't support -textmode

**Comment by TF2CutContentWiki** [comment] 2022-11-10 06:13
> @TF2CutContentWiki CS:GO also has trade bots and it doesn't support -textmode

Ah, beauty, so it shouldn't affect the TF2 item selling bots then.

**Comment by someone58198186911** [comment] 2024-01-04 21:58
legitfags crying clip: Number 6900.

you know you can literally host bots without fuckin textmode? and cathook doesnt even use the "-textmode" flag, it uses a fuckin' signature. Even if you remove the flag, it wont work :)

**Comment by someone58198186911** [comment] 2024-01-04 22:11
> > I closed the previous issue as I became aware that removing textmode will not stop people from hosting bots in TF2. There will always be another way. Removing it won't really change much in the long run.
> 
> The main issue is likely just-disable-vac-tf (which apparently works on other games too) And if cheats do use textmode, removing it will at least prevent bots from running for some time, which is always nice.

just disable vac tf gets injected/preloaded into Steam. So it will work on **ANY** source game, or anything that uses VAC

**Comment by Kacey2k** [comment] 2024-02-27 20:15
> legitfags crying clip: Number 6900.
> 
> you know you can literally host bots without fuckin textmode? and cathook doesnt even use the "-textmode" flag, it uses a fuckin' signature. Even if you remove the flag, it wont work :)

Its not a problem of whether or not bots can exist with/without textmode. It's the resources required to achieve the numbers bot hosts get when running without graphics. Forcing bot hosts to switch to hosting with graphics would be like Windows users trying to run 30 instances of TF2 in Sandboxie for bots. - Not too friendly for the CPU.

**Comment by wgetJane** [comment] 2024-03-01 06:20
this suggestion isn't going to achieve what you think it will achieve

**Comment by erickoid** [comment] 2024-04-21 23:44
> this suggestion isn't going to achieve what you think it will achieve

why are you so vague and obtuse

**Comment by compromisable** [comment] 2024-04-22 03:15
We have from @erickoid "Remove the -textmode launch parameter that just about every bot uses and no regular human I've ever come across has used", a very good suggestion indeed! This increases the cost of botting enormously, far beyond the price tag of the typical third world hoster! 

I suggest a captcha or phone verification, certainly not ideal already implemented into steams framework, thus very easy to pass along into TF2. Trust me, captcha verification automation AND renting phone numbers to verify accounts? Sheesh! What is this, Mr. Robot Academy? No way! 

We have @wgetJane  who suggests a cvar that detects cheaters, I believe? A very interesting notion, albeit, needs some elaboration! 

Another popular suggestion is to A) Updated the anti-cheat or B) Replace with functional anti-cheat. We've established that having even the most pathetic of anti-cheats (minimally functional - unlike present TF2 VAC) is infinitely better than nonfunctional anti-cheats, #GarrysModLuaAntiCheats. 


@kisak-valve , @pd-valve  @jeffmvalve  @bdeen-valve  @cboyd-valve  - **The floor is yours!**

**Comment by Doclic** [comment] 2024-04-22 08:35
@compromisable Please learn about how game development works before sending childish comments in an issue tracker.
If you think it's so easy to do, do it yourself then.

**Comment by wgetJane** [comment] 2024-04-22 13:47
> > this suggestion isn't going to achieve what you think it will achieve
> 
> why are you so vague and obtuse

i already explained this

updating the game to remove features from it doesn't forcibly remove previous versions of the game from existing machines

like a common suggestion is removing linux support, but linux binaries will still exist and will still work fine even if valve stops officially serving them

textmode is also such a trivial feature for cheaters to replicate, it's literally just running the game without graphics, this is not the silver bullet that you think it is

**Comment by erickoid** [comment] 2024-04-22 14:17
> > > this suggestion isn't going to achieve what you think it will achieve
> > 
> > 
> > why are you so vague and obtuse
> 
> i already explained this
> 
> updating the game to remove features from it doesn't forcibly remove previous versions of the game from existing machines
> 
> like a common suggestion is removing linux support, but linux binaries will still exist and will still work fine even if valve stops officially serving them
> 
... But you can't play on newer servers with an older build version of the game. You have 8000 hours in gmod, shouldn't you know this?
> textmode is also such a trivial feature for cheaters to replicate, it's literally just running the game without graphics, this is not the silver bullet that you think it is
If it's trivial give me an example on how it would be done

**Comment by erickoid** [comment] 2024-04-22 14:19
> @compromisable Please learn about how game development works before sending childish comments in an issue tracker. If you think it's so easy to do, do it yourself then.

You need to learn how game development works before complaining about an issue that has needed attention for 6 years?

**Comment by Doclic** [comment] 2024-04-22 14:20
> If it's trivial give me an example on how it would be done

Running the game without Vulkan presentation extensions, running the game without a display server, running the game with a modified DXVK, or your own DirectX/libX11/libwayland/etc implementation that just ignores any calls to it…

**Comment by Doclic** [comment] 2024-04-22 14:25
> You need to learn how game development works before complaining about an issue that has needed attention for 6 years?

This person clearly does not know what they're talking about (suggesting solutions that make no sense or that are infeasible) and are continuing to do so after being told by a Valve employee to stop (see #5686)

They're even pinging the Valve issue tracker moderator on this after being told that they don't work on anti-cheat (again see #5686)

**Comment by erickoid** [comment] 2024-04-22 14:31
> > If it's trivial give me an example on how it would be done
> 
> Running the game without Vulkan presentation extensions, running the game without a display server, running the game with a modified DXVK, or your own DirectX/libX11/libwayland/etc implementation that just ignores any calls to it…

Sounds like it raises the bar for botters still. Which is a good thing.

**Comment by erickoid** [comment] 2024-04-22 14:37
> > Sounds like it raises the bar for botters still. Which is a good thing.
> 
> Yeah, it would make the bot makers have to work for like a good hour or two.

It took botters more than a day to get back up and running after 64 bit was released, something tells me it will be a little bit more than just an hour or two for them.

**Comment by Doclic** [comment] 2024-04-22 14:45
> It took botters more than a day to get back up and running after 64 bit was released, something tells me it will be a little bit more than just an hour or two for them of _trivially_ do anything

Patching cheats up to work with a whole new binary is way more work intensive than creating a script that goes through every DirectX or Vulkan functions no-ops and fixing it up to make TF2 think the functions actually worked. (that might even already exist, I didn't look into it)
Also, we don't even know if botters do use `-textmode`.
Yes maybe that people running the bots took a day to update, but I'm sure most botters aren't actually developing them.
Furthermore, patching up cheats to work with 64-bit is way more work intensive than the solutions provided.

> Sounds like a bug valve would need to fix then

Why? It doesn't affect anyone.

**Comment by erickoid** [comment] 2024-04-22 15:28
> if you're even admitting that your proposed solution is very temporary, i don't understand why you still think it'd be a good solution

Oh, I didn't know I was competing with so many better solutions here. Anyway, My solution is very easy to implement, and will take away resources from botters.

https://github.com/nullworks/cathook/blob/master/src/textmode.cpp#L16C91-L16C102
Here is a very popular botting software that supports textmode, for doubters earlier
https://github.com/nullworks/catbot-setup/blob/master/install-catbots#L71
Here it is being used in helper scripts

>Yes my options are untested. I still know they will work, because they literally consist of just preventing the game from rendering to anything.

Yeah because knowing is everything...

**Comment by Doclic** [comment] 2024-04-22 15:35
> > if you're even admitting that your proposed solution is very temporary, i don't understand why you still think it'd be a good solution
> 
> Oh, I didn't know I was competing with so many better solutions here. Anyway, My solution is very easy to implement, and will take away resources from botters.

That's not what they were saying?

> Here is a very popular botting software that supports textmode

Great, you've shown that a bot software uses it, now what?
You know botters can just not use it right? They only use it because it reduces the load on the GPU, but if Valve removes it they can again just reimplement themselves easily.

> > Yes my options are untested. I still know they will work, because they literally consist of just preventing the game from rendering to anything.
> 
> Yeah because knowing is everything...

Go ahead, explain why they wouldn't work.

**Comment by compromisable** [comment] 2024-04-22 16:03
> @compromisable Please learn about how game development works before sending childish comments in an issue tracker. If you think it's so easy to do, do it yourself then.

Ah, a game developer arrives at the scene, oh thank heavens! I am hurt by your comment, but am immensely grateful to have your help. I do want to note that as a company with billions of dollars of resources and probably more developers under their belt then any other PC gaming company - I think it would indeed be very easy to do! I would do it myself if I had the power of hypnosis and a Valve employee in my armchair!  

Any ideas would be great, feel free to pitch in. 

> if you're even admitting that your proposed solution is very temporary, i don't understand why you still think it'd be a good solution

You'd rather no solution then a mildly effective one? Sounds like a bot hoster to me! Wait... aren't you the one who proposed a "Cheat detecting Cvar"...? 
![image](https://github.com/ValveSoftware/Source-1-Games/assets/147524755/be31c15e-a0eb-41b0-acca-60ac0d02801b)

**Comment by compromisable** [comment] 2024-04-22 16:06
Anyone else find it strange how much resistance there is to finding an ideal solution to this bot crisis?

**Comment by Doclic** [comment] 2024-04-22 16:06
> > @compromisable Please learn about how game development works before sending childish comments in an issue tracker. If you think it's so easy to do, do it yourself then.
> 
> Ah, a game developer arrives at the scene, oh thank heavens! I am hurt by your comment, but am immensely grateful to have your help. I do want to note that as a company with billions of dollars of resources and probably more developers under their belt then any other PC gaming company - I think it would indeed be very easy to do! I would do it myself if I had the power of hypnosis and a Valve employee in my armchair!
> 
> Any ideas would be great, feel free to pitch in.

Well as I see you're not willing to answer to me, I'll stop talking here.
Goodbye!

**Comment by compromisable** [comment] 2024-04-22 16:09
> > > @compromisable Please learn about how game development works before sending childish comments in an issue tracker. If you think it's so easy to do, do it yourself then.
> > 
> > 
> > Ah, a game developer arrives at the scene, oh thank heavens! I am hurt by your comment, but am immensely grateful to have your help. I do want to note that as a company with billions of dollars of resources and probably more developers under their belt then any other PC gaming company - I think it would indeed be very easy to do! I would do it myself if I had the power of hypnosis and a Valve employee in my armchair!
> > Any ideas would be great, feel free to pitch in.
> 
> Well as I see you're not willing to answer to me, I'll stop talking here. Goodbye!

Thank you for dropping bye! Goodnight!

**Comment by Doclic** [comment] 2024-04-22 16:09
> > @compromisable Please learn about how game development works before sending childish comments in an issue tracker. If you think it's so easy to do, do it yourself then.
> 
> Ah, a game developer arrives at the scene, oh thank heavens! I am hurt by your comment, but am immensely grateful to have your help. I do want to note that as a company with billions of dollars of resources and probably more developers under their belt then any other PC gaming company - I think it would indeed be very easy to do! I would do it myself if I had the power of hypnosis and a Valve employee in my armchair!

Well what would you do if you had the billions of dollars of resources, because even for massive companies, writing good anti-cheat isn't easy (see Counter-Strike 2).

> Anyone else find it strange how much resistance there is to finding an ideal solution to this bot crisis?

Well go ahead, give us one.

**Comment by wgetJane** [comment] 2024-04-22 16:09
> > if you're even admitting that your proposed solution is very temporary, i don't understand why you still think it'd be a good solution
> 
> Oh, I didn't know I was competing with so many better solutions here. Anyway, My solution is very easy to implement, and will take away resources from botters.

i am getting the impression that all you're interested in is scoring a short-term "victory" against bot hosters, so that the tf2 community can do its little celebration like what they do for every update that temporarily breaks bots as a side-effect

personally, i don't think sacrificing features, no matter how niche, is worth it just for scoring ultimately meaningless little victories

**Comment by compromisable** [comment] 2024-04-22 16:12
> > > if you're even admitting that your proposed solution is very temporary, i don't understand why you still think it'd be a good solution
> > 
> > 
> > Oh, I didn't know I was competing with so many better solutions here. Anyway, My solution is very easy to implement, and will take away resources from botters.
> 
> i am getting the impression that all you're interested in is scoring a short-term "victory" against bot hosters, so that the tf2 community can do its little celebration like what they do for every update that temporarily breaks bots as a side-effect
> 
> personally, i don't think sacrificing features, no matter how niche, is worth it just for scoring ultimately meaningless little victories

"They Won The Battle.. Not The War...", I like it. Yes. perhaps we need to think bigger.

![image](https://github.com/ValveSoftware/Source-1-Games/assets/147524755/f379e8ce-55f9-46e5-8b2a-a76bd260bd59)

**Comment by Doclic** [comment] 2024-04-22 16:15
> Wait... aren't you the one who proposed a "Cheat detecting Cvar"...?

I think you should stop holding this against them, as the following clearly isn't a serious suggestion:

> i have come up with the ideal solution:
> 
> valve should simply add a userinfo cvar on the client called cl_cheating which defaults to a value of 0
> 
> then, cheat developers can just change its value to 1 to identify the client as non-legit
> 
> when a client with a cl_cheating value of 1 joins a vac-secured server, they will be promptly vac-banned

**Comment by compromisable** [comment] 2024-04-22 16:16
> > > @compromisable Please learn about how game development works before sending childish comments in an issue tracker. If you think it's so easy to do, do it yourself then.
> > 
> > 
> > Ah, a game developer arrives at the scene, oh thank heavens! I am hurt by your comment, but am immensely grateful to have your help. I do want to note that as a company with billions of dollars of resources and probably more developers under their belt then any other PC gaming company - I think it would indeed be very easy to do! I would do it myself if I had the power of hypnosis and a Valve employee in my armchair!
> 
> Well what would you do if you had the billions of dollars of resources, because even for massive companies, writing good anti-cheat isn't easy (see Counter-Strike 2).
> 
> > Anyone else find it strange how much resistance there is to finding an ideal solution to this bot crisis?
> 
> Well go ahead, give us one.

Welcome back, my little contrarian, as you know there are already several on the table

1. Update anti-cheat - perhaps Hardware/IP tracking?
2. Replace anti-cheat -  perhaps Hardware/IP tracking?
3. Phone verification
4. Captcha verification
5. Remove -textmode
6. Enhance community power, perhaps after so many votekicks - a cooldown ban period? 


If you have better ideas, please feel free to contribute rather than bog us down!

**Comment by wgetJane** [comment] 2024-04-22 16:18
>     1. Update anti-cheat - perhaps Hardware/IP tracking?
> 
>     2. Replace anti-cheat -  perhaps Hardware/IP tracking?
> 
>     3. Phone verification
> 
>     4. Captcha verification
> 
>     5. Remove -textmode
> 
>     6. Enhance community power, perhaps after so many votekicks - a cooldown ban period?

these are out of scope of this issue, which is focused on the -textmode launch option

**Comment by kisak-valve** [comment] 2024-04-22 16:19
@compromisable, you were warned and have chosen to digress into name calling again. This has earned you a one day timeout.

**Comment by erickoid** [comment] 2024-04-22 16:19
> @compromisable, you were warned and have chosen to digress into name calling again. This has earned you a one day timeout.

Thats what should be happening to the bots.

**Comment by wgetJane** [comment] 2024-04-22 16:27
> > @compromisable, you were warned and have chosen to digress into name calling again. This has earned you a one day timeout.
> 
> Thats what should be happening to the bots.

personally, i would prefer them to be gone for longer than one day

**Comment by Doclic** [comment] 2024-04-22 16:27
Let's explain why each one of the solutions  you proposed don't work:

> 1. Update anti-cheat

Easier said than done, Valve has trouble doing it with CS2, which has higher priority than TF2

> perhaps Hardware/IP tracking?

1. You can spoof hardware, or just change it
2. Dynamic IPs

> 2. Replace anti-cheat

With what?

> 3. Phone verification

Not effective, you can buy cheap phone numbers on dark markets for a few cents each, and use Android emulators.
Also, do you really want to have to get your phone each time you join a casual server?

> 4. Captcha verification

There are also services that allow you to hire people to solve CAPTCHAs for a few cents per thousand.
And same thing as with phone verification, do you really want to have to solve a CAPTCHA each time you join a casual server?

> 5. Remove -textmode

I think I've talked about this one enough already, and this is the only one you should be mentioning here, as the issue is about removing `-textmode`.

>6. Enhance community power, perhaps after so many votekicks - a cooldown ban period

Do you know how many Steam accounts botters can create in a single day?
Most of them are thrown away after a week when they longer have access to the Hitman's Heatmaker trial from the Mann Co. store.
Perhaps making Steam accounts harder to create would be a good place to start, but solving spam (because that's basically the same problem) is easier said than done.

**Comment by gaelcoral** [comment] 2024-04-22 17:56
I believe that the Overwatch system should be implemented, at least in Competitive mode for testing purposes. I know many would be against my idea because it is considered a dead mode, but compared to Casual mode, Competitive requires certain criteria for access, which would be ideal for identifying and ban cheaters, helping to clean up this mode.

As for bots, which btw, I have not encountered in Competitive mode (at least in my region), it would be even harder for them to access, and it could even become the best way to play without the influence of bots.
(although this is just my opinion, the Competitive Matchmaking Pass should be removed if the Overwatch system were to be implemented)

Surprisingly, at least in the US-WEST, I rarely encounter cheaters in Competitive mode, unlike in Casual mode, where cheaters are becoming increasingly common.

**Comment by Doclic** [comment] 2024-04-22 17:59
A port of CS:GO's trust factor system could also be a good addition.

**Comment by ethanholt1** [comment] 2024-04-23 04:07
@compromisable You've been told multiple times that your behavior is inappropriate and that your hostility isn't welcome here. While I don't work at Valve (yet, my dms are open Gaben) and cannot ban you from these discussions, I would strongly recommend that you tone down the harsh remarks before someone who _can_ ban you gets sick of it.

Anyways, I believe a mix of both CS:GO's Trust Factor, the neural network powered bot detector I discussed in #3477 and Overwatch could work to remove a sizable portion of bots, enough to discourage any future bot hosters and to make casual semi playable, while still chipping away at the existing bot population.

**Comment by compromisable** [comment] 2024-04-24 01:55
### Wakes Up Without The Velcros

> > > @compromisable, you were warned and have chosen to digress into name calling again. This has earned you a one day timeout.
> > 
> > 
> > Thats what should be happening to the bots.
> 
> personally, i would prefer the bots to be gone for longer than a day

Pitiful! 

> @compromisable, you were warned and have chosen to digress into name calling again. This has earned you a one day timeout.

The devils advocate is necessary, lest we be complacent! It wasn't ordinary name calling, merely an observation!  

> @compromisable You've been told multiple times that your behavior is inappropriate and that your hostility isn't welcome here. While I don't work at Valve (yet, my dms are open Gaben) and cannot ban you from these discussions, I would strongly recommend that you tone down the harsh remarks before someone who _can_ ban you gets sick of it.
> 
> Anyways, I believe a mix of both CS:GO's Trust Factor, the neural network powered bot detector I discussed in #3477 and Overwatch could work to remove a sizable portion of bots, enough to discourage any future bot hosters and to make casual semi playable, while still chipping away at the existing bot population.

It seems to me that my behavior has brought a lot of attention to this issue, very capable minds I'd say, I'll happily be the martyr if it means uniting everybody to solve the bot crisis!  
________

Remember, CAPTCHA solvers arn't as effective nor cheap as they used to be in 2012 @doclic- nor are **non**-VOIP phone numbers, no sir! That would add up to a **LOT** more money then the typical bot hoster has in their washed ashore plastic bags! We aren't dealing with the Cartel of Internet Rage Hackers here! 
![image](https://github.com/ValveSoftware/Source-1-Games/assets/147524755/462bd65e-d9ec-4851-8905-f50f445ac67a)

**Comment by ethanholt1** [comment] 2024-04-24 02:03
> Remember, CAPTCHA solvers arn't as effective nor cheap as they used to be in 2012 @doclic- nor are **non**-VOIP phone numbers, no sir! That would add up to a **LOT** more money then the typical bot hoster has in their washed ashore plastic bags! We aren't dealing with the Cartel of Internet Rage Hackers here!

I went ahead and ran the numbers on this. The first site that came up when I looked for single use virtual cell numbers priced them at around 25 cents for single use numbers. The CAPTCHAs, can cost you around 3 dollars for 3,000 solved CAPTCHAs. 

> It seems to me that my behavior has brought a lot of attention to this issue, very capable minds I'd say, I'll happily be the martyr if it means uniting everybody to solve the bot crisis!

You are not a "martyr," you are being intentionally difficult to talk to and outwardly hostile. I for one have gotten sick of your behavior and decided to contact Valve directly at their email posted by Kisak for VAC related issues.

**Comment by kisak-valve** [comment] 2024-04-24 02:15
@compromisable, it's fairly clear that you're far more interested in wasting people's time bickering than anything else and spamming the same screenshot repeatedly. Your timeout has been extended to 1 month. If I need to step in again it will be permanent.

**Comment by compromisable** [comment] 2024-05-28 14:31
Interesting how when I got suppressed, all activity regarding solving this crisis came to a complete halt.

Now, where was I?

![image](https://github.com/ValveSoftware/Source-1-Games/assets/147524755/5d39c6ce-c06f-4aef-9f38-c86cfc98fdda)

**Comment by compromisable** [comment] 2024-05-28 14:34
![image](https://github.com/ValveSoftware/Source-1-Games/assets/147524755/a53f16fb-4a1f-4496-b4f0-8266bdd244a1)

This one was particularly striking to me. They are using your game to spread dox information. Perhaps we should take this more seriously? 

For anyone who'd like some inspiration, check out this suppressed thread for ideas:

https://github.com/ValveSoftware/Source-1-Games/issues/3477

**Comment by userNULL404** [comment] 2024-06-04 23:50
> This one was particularly striking to me. They are using your game to spread dox information. Perhaps we should take this more seriously?

Dude, I get it, but you are not saying anything of relevance to this discussion. This is not a forum or a Twitter thread. This is an issue tracker. If you don't have anything to say regarding textmode, don't say it here.

**Comment by doclic** [comment] 2024-06-04 23:55
> Interesting how when I got suppressed, all activity regarding solving this crisis came to a complete halt.

Interesting how when you got "suppressed", you've been explicitly told that:
> it's fairly clear that you're far more interested in wasting people's time bickering than anything else and spamming the same screenshot repeatedly. […] If I need to step in again it will be permanent.

@kisak-valve

**Closed** 2024-06-05 06:05 UTC
Labels: Feature Request, Team Fortress 2

**Comment by compromisable** [comment] 2024-06-05 20:16
> > Interesting how when I got suppressed, all activity regarding solving this crisis came to a complete halt.
> 
> Interesting how when you got "suppressed", you've been explicitly told that:
> 
> > it's fairly clear that you're far more interested in wasting people's time bickering than anything else and spamming the same screenshot repeatedly. […] If I need to step in again it will be permanent.
> 
> @kisak-valve
Good work Randal, keep up the implicit anti-bot-cure behavior 
![image](https://github.com/ValveSoftware/Source-1-Games/assets/147524755/77c9593d-9f19-4604-bb95-d8817971aa07)
