### ISSUE TITLE
[TF2] Strange weapons accrue points when serverside sv_cheats is 1.

### ISSUE THREAD

**Issue by suchipi** [ValveSoftware/Source-1-Games#1754] opened 2014-06-19 19:37 UTC
Yesterday I had set `sv_cheats` to 1 on my server and found that my Strange Jarate was still tracking sodden victims. I set `sv_cheats` via `rcon` while using the server because I wanted to change the value of `host_timescale` (which I did).

Server is running on Debian 7.1 64-bit, as a Xen PV guest (through a VPS service). My connected client was running Windows 8.1 64-bit - not sure about all other clients, but one of them was running Windows 7 64-bit.

**Comment by kisak-valve** [comment] 2016-12-29 14:42
Closing as a duplicate of #1176.

**Closed by kisak-valve** 2016-12-29 14:42 UTC
