### ISSUE TITLE
Alien Swarm on Linux?

### ISSUE THREAD

**Issue by terzag** [ValveSoftware/Source-1-Games#1748] opened 2014-06-12 05:44 UTC
In the list of missing Valve titles on Linux, there is a notable missing one: Alien Swarm. It would be a neat addition, the game is fun and there are not a lot of similar games on Linux. Do the devs plan to port it?

**Comment by kisak-valve** [comment] 2016-12-29 01:19
Closing as a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/2254.

**Closed by kisak-valve** 2016-12-29 01:19 UTC
Labels: Feature Request
