### ISSUE TITLE
[HL2DM] Game keeps forcing the combine_soldier model after the SteamPipe update

### ISSUE THREAD

**Issue by dwmtz** [ValveSoftware/Source-1-Games#263] opened 2013-04-03 20:18 UTC
![2013-04-03_00005](https://f.cloud.github.com/assets/4052560/335960/f3da2d48-9c9a-11e2-81ef-b973ff9731e5.jpg)
The game keeps switching back to the combine_soldier model whenever I try to change the player model.
Running on Windows 7 x64.

**Comment by StrikerMan780** [comment] 2016-04-06 00:18
FIX THIS YOU GODDAMN FAGGOTS. How many fucking years do we need to wait for this crap?

**Comment by MrSchism** [comment] 2016-04-06 21:32
That's not really any way to approach this issue. This repo has been for documentation purposes only for quite some time now.

Their aware of the issue, but have been otherwise preoccupied.

Please try to be respectful on future comments. Thank you.

**Comment by StrikerMan780** [comment] 2016-04-16 01:34
The cause seems to be outside of the Source SDK, so I can't fix it myself. Seems to be in the VGUI system for the multiplayer submenu. It sets cl_playermodel to "models" instead of the name of the model. Seems to be parsing the string incorrectly (likely due to the slashes).

**Comment by AfaaGames** [comment] 2016-09-17 19:23
Does ANYONE have a fix on this yet?
Not a stupid workaround, A REAL FIX?

**Comment by 100Worries** [comment] 2019-12-31 16:54
I've been looking at this issue recently along with a few others related to team selection. I've managed to create a proper selection menu so far, but nothing pretty yet. 

Also had some luck getting a bit of a class selection implemented along with a selection menu. Will post updates as soon as I've got something worth looking at.

Hello HL2DM 2020!

**Comment by Ethorbit** [comment] 2020-01-01 11:05
> I've been looking at this issue recently along with a few others related to team selection. I've managed to create a proper selection menu so far, but nothing pretty yet.
> 
> Also had some luck getting a bit of a class selection implemented along with a selection menu. Will post updates as soon as I've got something worth looking at.
> 
> Hello HL2DM 2020!

Thankfully this plugin has completely fixed the model change menu bug: https://gamebanana.com/gamefiles/7747

**Comment by Yetoo1** [comment] 2020-05-05 23:39
For me this issue seems fixed, although I'm testing on linux. Though the spray selection still seems broken as, spraying will only spray spray_canned regardless of the selection and the selection in the menu will reset to spray_canned if the game is exited and started again. 

HL2DM Version:
Build Label:           5394425   # Uniquely identifies each build
Network PatchVersion:  5394425   # Determines client and server compatibility
Protocol version:           24   # High level network protocol version
Server version:        5394425
Server AppID:           232370
Client version:        5394425
Client AppID:              320

System information:
https://pastebin.com/qzzJSxfV

**Comment by Yushe** [comment] 2021-04-06 11:36
@StrikerMan780 is right though, I'm an amature programmer and I even figured out how to fix this issue.

In _src/game/server/hl2mp/hl2mp_player.cpp_
change line 250 to this:
```cpp 
Q_snprintf( szReturnString, sizeof (szReturnString ), "cl_playermodel %s\n" );
```
For some reason Valve made the game deliberately change the players model to the combine model.
This doesn't seem to fix the selection menu on options but it will keep your player model consistent with the last one that you set.

I think that the options menu is probably sending incorrect console commands which is why its just printing the the last model you selected.
Trying to set your playermodel to one that isn't set in the source code like `models/kleiner.mdl` will result in your model not getting changed and the console printing your current model.

If anyone knows how to modify the options menu please let me know, I'm still getting used to modifying the source code and I'm not sure where everything is.

I hope this information has helped someone.

**Comment by StrikerMan780** [comment] 2022-01-14 02:50
`Q_snprintf( szReturnString, sizeof (szReturnString ), "cl_playermodel %s\n" );`
This looks like undefined behaviour to me. Where is it getting the value of %s from? I see no format parameters.

**Comment by Yushe** [comment] 2022-01-14 09:06
@StrikerMan780 If you search for %s in hl2mp_player.cpp you will find three cases of Valve using it for the cl_playermodel console command.
combine_soldier.mdl is getting set whenever hl2mp_player.cpp fails to validate the playermodels (ValidatePlayerModel( szModelName ) == false).

After messing around with this issue a lot its just clear that you need to completely rewrite how playermodels are handled in hl2mp_player.cpp.
It's how I eventually fixed them in my game.

**Comment by Yetoo1** [comment] 2022-01-16 07:10
@fletcherdvalve You're assigned to this, what's your progress on it?

**Comment by Yushe** [comment] 2022-01-17 18:00
lmao

**Comment by shyguy85** [comment] 2022-08-25 14:40
how have you guys not fixed this yet?!! its been a decade!!!

**Comment by dwmtz** [comment] 2022-08-27 11:54
So, after a while I installed the game again (on GNU/Linux), aaaaaaand it still happens. 

Set model to `female_01`, join a random Team Deathmatch server, it automatically changes to `combine_soldier`. Every time, without fail.

**Comment by Adrianilloo** [comment] 2022-09-21 13:59
This is not fixed, and still a basic annoying issue towards user experience. As someone explained in the past, this has to do with some command parsing change in the engine, making it to stop at the slash (/) and thus affecting cl_playermodel inputs, causing the game code to read and associate "models" path to the Combine team, and setting a Combine model as a fallback.

**Comment by Adrianilloo** [comment] 2022-09-21 14:01
This is not fixed, and still a basic annoying issue towards user experience. As someone explained in the past, this has to do with some command parsing change in the engine, making it to stop at the slash (`/`) and thus affecting `cl_playermodel` inputs, causing the game code to read and associate `"models"` path to the Combine team, and setting a Combine model as a fallback.

**Comment by Adrianilloo** [comment] 2022-12-03 17:14
@TEAMJBMOD Althought I won't replace a client DLL file to check due to it's own inconveniences, I couldn't relate your explanation to the problem. In fact, it looks as opposite to it. If the "path is already normalized before it" (assuming you mean the derived UI command after saving/applyong settings -i.e. `cl_playermodel models/humans/.../XXX.mdl`-) sent to the engine and server, why would such `strcmp` related logic need to "replace the slash at all", if the command is already correct and would be handled correctly once reaching `ClientSettingsChanged` at the server DLL? When, what seems to be happening (first slash being replaced by a null terminator, given such function always receives exact `cl_playermodel models` inputs as we know) looks pretty much orthogonal to your explanation.

**Comment by PF94** [comment] 2023-01-19 20:09
``COptionsSubMultiplayer::OnApplyChanges()`` gets the active selected item from ``m_pModelList`` with a forward slash embedded into it for some reason. As such, it changes ``cl_playermodel`` to ``models//[selected model].mdl``, which somewhere along the line becomes ``models``.

**Comment by brannanz** [comment] 2024-01-04 11:28
Still waiting.... Almost 11 year old bug still not fixed

**Comment by WhatDidYouExpect** [comment] 2024-01-05 00:44
literally forces my mod to be a combine.. yippie

**Comment by brannanz** [comment] 2024-01-10 10:15
if valve fix this i will be a very happy person

**Comment by conneath** [comment] 2024-11-26 16:36
this has been seemingly fixed in the latest HL2DM beta branch update

**Comment by kisak-valve** [comment] 2024-12-27 23:53
Closing per the last comment.

**Closed by kisak-valve** 2024-12-27 23:53 UTC
Labels: Reviewed, Half-Life 2: Deathmatch, Need Retest
