### ISSUE TITLE
War Paint Materials - fixes and improvements

### ISSUE THREAD

**Issue by CrazyHappy** [ValveSoftware/Source-1-Games#4704] opened 2023-01-14 06:22 UTC
please add this much needed bug fix https://gamebanana.com/mods/389672
https://imgur.com/a/Ak3k9Gn
the developers will approve these fixes, which warpaint will become more popular for players, the developer will pocket extra money

**Comment by condor00fr** [comment] 2023-01-14 10:15
This fix was also uploaded on the Workshop and is very well made, the jungle inferno war paints suffers from a lack of polish and lots of missing details, so I am all for it:)

**Comment by Ashetf2** [comment] 2023-01-14 15:51
Duplicate of #4261?

**Comment by kisak-valve** [comment] 2023-01-14 15:55
Closing in favor of the older issue report.

**Closed by kisak-valve** 2023-01-14 15:55 UTC
Labels: Feature Request, Team Fortress 2, Art, Texture

**Comment by CrazyHappy** [comment] 2023-01-15 08:51
> Closing in favor of the older issue report.

ok please add this product for game
