### ISSUE TITLE
[TF2] Loadout changes via shortcuts A/B/C/D are not taken into account

### ISSUE THREAD

**Issue by Gnurfos** [ValveSoftware/Source-1-Games#1667] opened 2014-02-21 18:15 UTC
For example, wanting to switch from loadout A to loadout B, from in game:
- press M to bring up loadout screen
- click on B. Items are correctly changed on the loadout screen (assuming no item server slowdown)
- press Escape or click twice on Back, to return to game

Expected: new items from loadout B are immediately equipped (option "automatically respawn after loadout changes..." is active).

Actual behavior: new items are not equipped (no respawn happens), until a resupply cabinet is approached, and/or maybe after death/respawn

A workaround that seems to work (to get immediate loadout change, at the cost of some additional clicks):
- press M
- click on B
- click on any of the equipped weapons (from loadout B, since change is effective on the inventory screen), as if to change this weapond for another one, but re-select the same weapon
- press Escape or click twice on Back, to return to game
  -> In this case, respawn and correctly equipment seems to happen automatically.

This problem is not new (more than a few monthes), but I think it was not there from the beginning either (of the linux version).

**Comment by kisak-valve** [comment] 2016-12-27 15:32
Closing as a duplicate of #1472.

**Closed by kisak-valve** 2016-12-27 15:32 UTC
Labels: Team Fortress 2
