### ISSUE TITLE
[TF2] pl_barnblitz payload turntable is completely black

### ISSUE THREAD

**Issue by occune** [ValveSoftware/Source-1-Games#4024] opened 2022-07-09 07:37 UTC
![hl2_dBTHH0sEpP](https://user-images.githubusercontent.com/9035722/178096590-1c2fb009-489b-44c3-96bc-d8504cff1ede.jpg)

Here's the screenshot of what it is supposed to look like (taken from tf2 wiki)

![Barnblitz-cp2entrance](https://user-images.githubusercontent.com/9035722/178096665-37393078-fcbb-4c42-a9a4-ef2297d9b33b.png)
setpos 2341.567139 -1864.963501 -61.333939;setang 25.079950 175.910904 0.000000

**Comment by TF2CutContentWiki** [comment] 2022-07-11 02:45
Do you by chance have mat_phong set to 0? This can cause several models in the game to go pitch black like that.

**Comment by occune** [comment] 2022-07-11 09:44
I never disable phong

**Comment by TF2CutContentWiki** [comment] 2022-07-11 09:53
Very interesting then.

**Comment by agrastiOs** [comment] 2022-07-14 12:54
Looks like it's set to an incorrect texture.

**Comment by FrozenDragon0** [comment] 2022-07-17 03:46
It seems that this problem occurred with the last update.

**Comment by Ashetf2** [comment] 2022-07-18 22:57
Confirmed by changing the lighting origin to this info_target for example
![image](https://user-images.githubusercontent.com/63692647/179630717-bcdc642a-6df4-46b1-9ae2-a70d516d0795.png)
![image](https://user-images.githubusercontent.com/63692647/179630762-1a42efdc-fa1a-4a9d-90c9-75614c02c0bb.png)

**Comment by Thespikedballofdoom** [comment] 2022-07-21 17:56
![cap_20-07-2022_12 27 44PM_x](https://user-images.githubusercontent.com/43627353/180281726-9a8b109f-06d9-45f4-b454-07e85483c1ce.gif) Custom maps have been negatively affected by the change visually too, point_spotlights cant be moved around

**Comment by Ashetf2** [comment] 2022-07-29 19:42
Prop lighting fixed in the July 29 Patch

**Comment by agrastiOs** [comment] 2022-07-29 20:03
Spotlight issue also. 
![paveikslas](https://user-images.githubusercontent.com/15906773/181835171-0056f154-8dac-4434-8526-4375343693dc.png)

**Comment by occune** [comment] 2022-07-30 09:07
Can confirm, latest patch has fixed the bug

![Team Fortress 2 7_30_2022 12_07_10 PM](https://user-images.githubusercontent.com/9035722/181903565-2dbfeea0-4fdd-4c04-b89b-7abea762572a.png)

**Comment by agrastiOs** [comment] 2022-07-31 11:21
Likewise, it's fixed for me. @occune might be worth closing the issue now.

@Thespikedballofdoom What is that map?

**Closed** 2022-08-01 09:29 UTC
Labels: Team Fortress 2, Need Retest
