### ISSUE TITLE
[TF2] Consolidated Dead Ringer bugs

### ISSUE THREAD

**Issue by Exaeta** [ValveSoftware/Source-1-Games#2548] opened 2018-04-01 20:46 UTC
@kisak-valve 
I'm writing this issue illustrating most bugs with the dead ringer. I'm making a consolidated thread because I realised all of the bugs I reported could be fixed via the same method.

https://github.com/ValveSoftware/Source-1-Games/issues/2463
https://github.com/ValveSoftware/Source-1-Games/issues/2464
https://github.com/ValveSoftware/Source-1-Games/issues/2467

All of these bugs can be fixed by doing the following:

Create a new entity "spy faux rendering entity", attached to the spy/player. The enemy team does not render the spy but instead renders the "spy faux rendering entity", which will share the same variables as the spy except when the spy feigns death, during which the spy does not update the faux render entity. Things like medic bubbles, overhead effects, and gibs, would all be rendered from the faux entity instead of the real spy. Disguise smoke should also follow the faux entity instead of the real spy.

Death cam should follow the faux render entity and show "the late spy" instead of the real spy.

If the spy calls medic or is crit before a feign the bubble would stay on the feiggn instead of following the spy around. If the spy does afterwards the enemy player should hear but not see the bubble.

I think these bugs need to be fixed because it makes it too easy to give away the spy's position.

**Comment by kisak-valve** [comment] 2018-04-01 22:06
Hello @Exaeta, this counts as a duplicate of your existing issue reports. It's best to track the issues separately and if there is a single fix that closes multiple issues, then we can handle that when it happens.

Feel free to add your hypothesis that the issues may be related to the existing issue reports, but there's little benefit to have this info in a separate issue report so I'm going to close this issue report as a duplicate.

As a side note, I'm a moderator for the ValveSoftware issue trackers and not a TF2 dev. Directly addressing me in your issue reports will not make a difference.

**Closed by kisak-valve** 2018-04-01 22:06 UTC
