### ISSUE TITLE
[HL2 Ep2] Paint on displacement is inverted in game versus in Hammer

### ISSUE THREAD

**Issue by Riomaki81** [ValveSoftware/Source-1-Games#991] opened 2013-06-29 03:39 UTC
Using Steampipe Beta and the Hammer.exe in Half-Life 2's /bin folder.

When you create a displacement with a blend texture applied to it, the two textures are swapped between Hammer and Episode 2 itself.  This problem does NOT seem to exist in the Source SDK 2013 Hammer.

This example is using concrete/blendbunk_conc01 on a displacement with a power of 2.

This is how it appears in Hammer:

![disphammer](https://f.cloud.github.com/assets/4877436/725474/4a7d531c-e06d-11e2-9195-acdd2327127f.jpg)

This is how it appears in-game:

![dispgame](https://f.cloud.github.com/assets/4877436/725476/552c5bdc-e06d-11e2-809a-a398930d989f.jpg)

Windows Vista x64, Nvidia 550 Ti.

**Comment by kisak-valve** [comment] 2016-12-23 20:13
Hello @marnamai, are you still experiencing this issue?

**Comment by marnamai** [comment] 2016-12-23 22:58
retested the 2 scenario's
1) compiled in Hammer from hl2/bin +ep2's config, loaded the map in ep2 => works as intended
2) setup a Source 2013 mod, used Source SDK Base 2013 Singleplayer/bin Hammer to compile and the mod to load the map => works as intended

So this issue can be considered fixed, feel free to close it.

**Comment by kisak-valve** [comment] 2016-12-24 01:20
Thanks for retesting, closing.

**Closed by kisak-valve** 2016-12-24 01:20 UTC
Labels: Half-Life 2: Episode Two, Need Retest, Reviewed, SDK
