### ISSUE TITLE
[TF2] "vaccinator_heal.wav" will continue to play upon death

### ISSUE THREAD

**Issue by angiepawing** [ValveSoftware/Source-1-Games#6068] opened 2024-06-11 09:21 UTC
Upon death, the Vaccinators healing sound "vaccinator_heal.wav" will continue to play without input from the player. This audio will play at the characters camera, and follow the camera playing in a loop. However, if the player switches loadouts to any loadout containing a secondary that is NOT the Vaccinator, the audio will continue to loop at the point which the player executed a loadout change, or occasionally teleport to map origin.

### How to reproduce:

If the player dies while healing with the Vaccinator:
* "vaccinator_heal.wav" will continue to play at the players camera height
* The audio will not end until any player on the map heals with the Vaccinator, or `snd_restart` is executed.

If the player changes loadouts while the above bug is active:
* "vaccinator_heal.wav" will loop in the position the player executed a loadout change
* The sound may occasionally teleport to map origin (0, 0, 0) and continue looping.
* The sound can only be stopped by executing `snd_restart` or leaving the server

[System Information](https://gist.github.com/colepaws/39c171dd3234923ebd91970f4c2348e7)

https://github.com/ValveSoftware/Source-1-Games/assets/118927649/65fd882e-6df8-46b9-9b9a-3e9e2df05b92

**Comment by NULLYUKI** [comment] 2024-07-18 19:08
According to patch [223066](https://www.teamfortress.com/post.php?id=223066)
>Fixed Vaccinator heal sound continuing to play after Medic's death 

This needs to be retested.

**Comment by JoriKos** [comment] 2024-07-19 12:03
Cannot reproduce this issue anymore, it's fixed

**Comment by kisak-valve** [comment] 2024-08-23 21:21
Closing per the last couple comments.

**Closed as completed by kisak-valve** 2024-08-23 21:21 UTC
Labels: Team Fortress 2, Audio
