### ISSUE TITLE
[TF2] Soldier weapons visual bug

### ISSUE THREAD

**Issue by perkoz323** [ValveSoftware/Source-1-Games#5997] opened 2024-05-12 11:24 UTC
The game still has a visual bug known for years related to the soldier class and their protruding hand during gameplay and when inspecting weapon. I play on a 21:9 monitor, and the bug is more visible also i use viewmodel_fov 90 and fov_desired 90
Examples of weapons on which the bug occurs and screenshots:
-The Buff Banner
-The Concheror
-The Battalion's Backup
-The Original
-The Ham Shank
-The Frying Pan
-The Pain Train
-The Conscientious Objector
-The Market Gardener

<details><summary>Screenshots:</summary>

![The Concheror](https://github.com/ValveSoftware/Source-1-Games/assets/71722873/132f775b-31af-4875-81b2-ca5752ee56e4)
![The Conscientious Objector](https://github.com/ValveSoftware/Source-1-Games/assets/71722873/8426f506-37ea-40c6-bbe6-da18f647d91e)
![The Frying Pan Inspection](https://github.com/ValveSoftware/Source-1-Games/assets/71722873/18a10ba3-ae08-495f-b95e-82893ae16887)
![The Frying Pan](https://github.com/ValveSoftware/Source-1-Games/assets/71722873/e6310cbd-7f13-4678-8c5a-9993058467da)
![The Ham Shank Inspection](https://github.com/ValveSoftware/Source-1-Games/assets/71722873/4a79f2b3-2ab5-4834-9776-80222b0662d7)
![The Ham Shank](https://github.com/ValveSoftware/Source-1-Games/assets/71722873/5f2aae86-cf20-4753-ad03-9e7bc1bf265c)
![The Market Gardener Inspection](https://github.com/ValveSoftware/Source-1-Games/assets/71722873/c00f4934-c918-44bb-a4cf-1b3b33548c48)
![The Original](https://github.com/ValveSoftware/Source-1-Games/assets/71722873/547ca3a6-fc7f-4bbb-a435-9acf7d99c2a1)
![The Pain Train Insception](https://github.com/ValveSoftware/Source-1-Games/assets/71722873/e92a0991-5b50-46d3-a6cf-04c834665695)
![The Battalion's Backup](https://github.com/ValveSoftware/Source-1-Games/assets/71722873/c3199140-f2c8-4fbb-8462-9cce99acde41)
![The Buff Banner](https://github.com/ValveSoftware/Source-1-Games/assets/71722873/991ec2da-3206-4219-b3fa-504b8a40d54d)
![The Pain Train](https://github.com/ValveSoftware/Source-1-Games/assets/71722873/9fb495e2-0364-4f67-942e-5dc1db6c8327)

</details>

**Comment by JoriKos** [comment] 2024-05-12 12:33
Duplicate of #5759

Also not really a bug, the options menu limits viewmodel fov to a max of 70 for a reason. These issues are going to be present on higher FOVs a lot, because they weren't made for those FOVs.

**Comment by kisak-valve** [comment] 2024-05-12 12:54
Closing as a duplicate.

**Closed as not planned by kisak-valve** 2024-05-12 12:54 UTC
Labels: Team Fortress 2, Animation
