### ISSUE TITLE
Objector option

### ISSUE THREAD

**Issue by zzDeathGodzz** [ValveSoftware/Source-1-Games#5716] opened 2024-04-19 09:13 UTC
Could we have a setting to disable/enable seeing custom conscientious objector signs?

I don't want to be forced seeing non-TOS content on signs, especially as a streamer.

**Comment by JoriKos** [comment] 2024-04-19 09:21
Duplicate of #4249

**Comment by gdfsgdfg** [comment] 2024-04-19 12:01
Yes please, we really need an option to hide decals.

**Comment by kisak-valve** [comment] 2024-04-19 12:06
Hello @zzDeathGodzz, as @JoriKos noted, this issue is already being tracked at #4249.

Closing as a duplicate.

**Closed by kisak-valve** 2024-04-19 12:06 UTC
