### ISSUE TITLE
[TF2] [Bug] Loch-N-Load grenades disappearing or exploding midair

### ISSUE THREAD

**Issue by Haze33E** [ValveSoftware/Source-1-Games#2068] opened 2017-01-09 16:03 UTC
I was just in a game and it reminded me about this bug. When fired over long distances the Loch-N-Load pills either disappear or detonate in the air. I noticed when they were disappearing it was playing the animation as if the grenades were hitting a surface. Other times I've fired them long distance but with no line of sight and was hearing explosions from my grenades but no hit sounds would play.

**Comment by agrastiOs** [comment] 2017-01-09 16:09
That's not a bug. It isn't stated in the description that Loch-N-Load doesn't detonate if it's not a direct hit

**Comment by Haze33E** [comment] 2017-01-09 16:21
I'm talking about them poofing in the air not them hitting something.

**Comment by agrastiOs** [comment] 2017-01-09 16:23
Like it doesn't explode, but just disappear?

**Comment by Haze33E** [comment] 2017-01-09 16:23
Yes it just disappears in the air or sometimes explodes without hitting anything.

**Comment by agrastiOs** [comment] 2017-01-09 16:24
But they shouldn't explode when hitting something. As you know, the grenades shatter.

**Comment by Haze33E** [comment] 2017-01-09 16:30
Let me explain slowly and simply. 

Scenario 1. I fire long range to hit a sentry. The pills disappear before reaching the sentry and I can see them play the animation as if they hit a wall or the ground. Yet I know they should have hit the sentry but they just decide to disappear.

Scenario 2. I haven't seen it with my eyes. But I fire over rocks long range then could hear my grenades exploding in the air. But I never got a hit sound as confirmation that I was hitting a building or player. So the grenades were detonating in the air by themselves without hitting anything.

**Comment by agrastiOs** [comment] 2017-01-09 16:30
You know all grenades have timers right? Thus, the Loch-N-Load's grenades timer ends and they blow up. About them dissappearing sometimes, they probably go to a non-solid prop, or smash into the invisible wall.

**Comment by agrastiOs** [comment] 2017-01-09 16:31
Scenario 1 is probably weird prop collisions

**Comment by Haze33E** [comment] 2017-01-09 16:31
They didn't have timers for Loch-N-Load in the past I used to be able to fired it as far as it would go before it collided with something.

**Comment by agrastiOs** [comment] 2017-01-09 16:32
Maybe, they added it. But I don't see that as a bug

**Comment by agrastiOs** [comment] 2017-01-09 16:33
You could change this to a feature request to remove Loch-N-Load timers to perform very long range shots

**Comment by agrastiOs** [comment] 2017-01-09 16:34
Or at least, that the timers could be made longer to correlate with faster speed.

**Comment by Haze33E** [comment] 2017-01-09 16:35
As far I can find the Loch-N-Load doesn't have a fuse timer and has always been detonation on impact (with people/buildings) like a rocket. So this must be a bug.

**Comment by agrastiOs** [comment] 2017-01-09 16:37
It certainly has the fuse timer. I sometimes fire it to the sky and it blows up after a bit.

**Comment by Haze33E** [comment] 2017-01-09 16:43
Can't find mention of it anywhere online. I can find the timers for the other grenades launchers easily. I'm guessing this was an accidental change when they updated the firing sounds.

**Comment by agrastiOs** [comment] 2017-01-09 17:33
Might be. But it could be also an intentional change. I wonder, if Valve removed the timers, would they add that to the description?

**Comment by hahagoni** [comment] 2017-01-09 18:29
@Haze33E could you provide footage (preferably a .demo file) of this happening?

If not, what maps are you experiencing in on and what position? Might have to do with invisible map geometry, but I never noticed this occuring

**Comment by agrastiOs** [comment] 2017-01-09 18:33
I'm also curious with Scenario 1

**Comment by Haze33E** [comment] 2017-01-09 18:51
Well I tested it alone on a server @agrastiOs is right about them exploding after a set distance. The only thing I can figure is that I was shooting at a wrangled sentry so maybe the pills were colliding with the sentry shield and not detonating. As for footage I've never messed with recording demos so I don't have the first clue how to do any of that. But still the pills are exploding in the air without colliding with anything. Doesn't matter if you're shooting into the sky or down a long corridor. From what I remember they never had fuse timers. I only noticed this issue after they updated the firing sounds.

**Comment by agrastiOs** [comment] 2017-01-09 18:59
Well, there's no proof about them having no fuse timers or that the developers intended to not have them

**Comment by Wasmanr2** [comment] 2017-03-28 05:37
Cant confirm that grenades disappearing from L&L.
For me they hit their target if sentrys on rocks or if its a spy from miles away.
Any chance that you guys playing with 33 ticks and high lerp because im playing always with 66.7 ticks/s and 15.5ms lerp (for demoman)?

**Comment by Bradasparky** [comment] 2024-04-24 08:29
> They didn't have timers for Loch-N-Load in the past I used to be able to fire it as far as it would go before it collided with something.

> From what I remember they never had fuse timers. I only noticed this issue after they updated the firing sounds.

The Loch-n-Load has had a fuse time equivalent to stock ever since it was put into the game. The only way fuse time can be modified is via attribute 787 "fuse time", which it never had. This is the oldest footage on [Youtube from 12 years ago](https://youtu.be/u8P7MAW81AU?si=l-b3dE4OdskKosmt&t=7) that I could find of the Loch-n-Load where it exploded mid air after ~2.3 seconds. Grenades will shatter when colliding with any solid map geometry otherwise including clip brushes and block bullets.

> The only thing I can figure is that I was shooting at a wrangled sentry so maybe the pills were colliding with the sentry shield and not detonating.

The wrangler's shield is a non-solid model so it's impossible for the grenade to have collided with it and shattered or bounced off.

@kisak-valve This issue can be closed. No such behavior explained by OP is evident in the old footage I provided of Scenario 2, nor in my testing as of the current TF2 update when testing scenarios described by OP.

**Comment by agrastiOs** [comment] 2024-04-24 08:41
Yeah I'd agree that this should be closed

**Comment by wgetJane** [comment] 2024-04-24 08:45
LnL grenades will shatter when hitting the skybox, which is probably where this whole confusion came from

**Comment by kisak-valve** [comment] 2024-06-01 01:00
Closing per the last handful of comments.

**Closed by kisak-valve** 2024-06-01 01:00 UTC
Labels: Team Fortress 2, Need Retest
