### ISSUE TITLE
[TF2] PLR Bonesaw using wrong gamemode logic

### ISSUE THREAD

**Issue by SirBlockles** [ValveSoftware/Source-1-Games#4366] opened 2022-10-05 20:51 UTC
the map Bonesaw is supposed to be PLR, yet uses normal PL logic. RED can't push their cart, and there is no round timer, so BLU has infinite time to always win.

additionally, the HHH's model is broken, leaving him as a floating axe, and there's missing textures in the resupply cabinet's model.

![image](https://user-images.githubusercontent.com/3620019/194161027-89fd0e35-58b3-47b1-981c-21368e1c80d6.png)

**Comment by AzureAzel** [comment] 2022-10-05 23:04
Ah yes, the Horseless Headless Horsemannless.

Jokes aside, this is pretty bad.

**Comment by treacherousfiend** [comment] 2022-10-06 01:28
Regarding the logic, Bonesaw actually does use PLR logic. According to one of the map devs, Valve made a simple mistake when preparing the map for launch, which broke the red cart. The lack of round timer is normal for PLR maps.

**Comment by kisak-valve** [comment] 2022-10-06 23:48
Hello, per "Updated plr_hacksaw_event > Fixed not being able to push the Red cart" in the [2022-10-06](https://www.teamfortress.com/post.php?id=144094) Team Fortress 2 update, please retest this issue.

**Comment by treacherousfiend** [comment] 2022-10-06 23:51
Funny you should mention this right now, I was in the process of cutting down clips of myself showing these issues were fixed!
First video: shows off missing textures in resupply fixed and Red can push the cart
https://user-images.githubusercontent.com/46549454/194438298-ce0e56e8-96cb-4497-9701-ffc2914221a4.mp4
Second video: shows Horsemann spawning and being visible with his custom model
https://user-images.githubusercontent.com/46549454/194438303-46d15b4c-0cd1-4a93-aabe-5bf386a5e2d2.mp4

**Comment by Wasmanr2** [comment] 2022-10-17 10:11
Update from 6th October fixed the issue
(played the map and it worked as intended) 
+ see previous comment

issue can be closed

**Comment by agrastiOs** [comment] 2022-10-17 17:57
Can also confirm that it's fixed

**Comment by MikhailaTF** [comment] 2022-10-22 16:39
can confirm its fixed, issue can be closed

**Comment by kisak-valve** [comment] 2022-11-25 21:15
Closing as fixed.

**Closed by kisak-valve** 2022-11-25 21:15 UTC
Labels: Team Fortress 2, Need Retest
