### ISSUE TITLE
team fortress 2 requests.

### ISSUE THREAD

**Issue by EthanTheCool** [ValveSoftware/Source-1-Games#6767] opened 2024-11-27 13:19 UTC
ik I said this before, but tf2 needs a great amount of new major updates. major updates must include one or more weapons, some balance changes to any weapon, cosmetics, and maps. the last update was on October 20th, 2017. and its been more than 7 years since last major update. remember the Heavy vs. Pyro? well the first NEW major update must be surrounding the heavy since he is yet to recive his own class pack. more than 50,000 of people are playing tf2, and It would be a shame if we did not get any major updates. the community has weapons being made and please can we get another major update?

**Comment by kisak-valve** [comment] 2024-11-27 13:45
Hello @EthanTheCool, similar to #6340, this is not an actionable request.

Please do not intentionally open duplicates.

Closing as a duplicate of #6340 / not a specific, actionable issue report.

**Closed as not planned by kisak-valve** 2024-11-27 13:45 UTC
