### ISSUE TITLE
[TF2 64-BIT] Bug detected. Eye bugs

### ISSUE THREAD

**Issue by KissyWuggy** [ValveSoftware/Source-1-Games#5815] opened 2024-04-20 08:32 UTC
I found eye bugs all classes.
![Снимок экрана 2024-04-20 112258](https://github.com/ValveSoftware/Source-1-Games/assets/167605412/06fc1078-9604-4619-b866-5ab45da64553)
![Снимок экрана 2024-04-20 112948](https://github.com/ValveSoftware/Source-1-Games/assets/167605412/a00172e7-7581-4faa-99ae-317bea336e9d)

**Comment by JoriKos** [comment] 2024-04-20 08:39
Duplicate of #5717

**Comment by kisak-valve** [comment] 2024-04-20 13:07
Hello @KissyWuggy, as @JoriKos noted, this issue is already being tracked at #5717.

Closing as a duplicate.

**Closed by kisak-valve** 2024-04-20 13:07 UTC
