### ISSUE TITLE
L4D2 Missing UI Images

### ISSUE THREAD

**Issue by Vash63** [ValveSoftware/Source-1-Games#1500] opened 2013-10-20 23:27 UTC
The up and down arrows in all scrolling text boxes show up as 't' and 'u', checkboxes show up as 'b' and unchecked ones as another letter. Verified on two separate machines, one running Archlinux and one running Fedora 19, both with Nvidia drivers. Specs for my primary Arch machine:

``` specs
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2d
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  5700 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.11.5-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11403000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2013-09-28

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 680/PCIe/SSE2

    Driver Version:  4.3.0 NVIDIA 325.15
    OpenGL Version: 4.3
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1180
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 3760 x 1920
    Primary Display Size: 23.50" x 13.23"  (26.97" diag)
                                            59.7cm x 33.6cm  (68.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: AV200

Memory:
    RAM:  15997 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  111420 Mb
    Largest Free Hard Disk Block:  33523 Mb

Installed software:

Recent Failure Reports:
```

![2013-10-20_00001](https://f.cloud.github.com/assets/3086017/1369248/12f34e44-39df-11e3-9aff-cedda1bd82e3.jpg)

**Comment by kisak-valve** [comment] 2016-12-27 19:59
Closing as a duplicate of #554.

**Closed by kisak-valve** 2016-12-27 19:59 UTC
