### ISSUE TITLE
[TF2 Linux Legacy OpenGL] Launching TF2 Causes Full System Freeze From Launching the Game Again After Exiting and Reentering Steam; Forced Shutdown Required

### ISSUE THREAD

**Issue by BugsyReportsy** [ValveSoftware/Source-1-Games#6697] opened 2024-11-20 18:26 UTC
When I launch TF2 Legacy OpenGL again after previously playing the game and then exiting Steam, it would cause a full system freeze a few seconds after the main menu loaded. The whole system would be frozen except for my mouse cursor, with my system seemingly more likely to freeze when I'm either only using my laptop display without an external monitor, when I have multiple programs open in the background despite having enough free RAM space, and when I have my Bluetooth headphones are connected. It was just today that I had this problem and only with TF2 specifically; I'm not even entirely sure if the possible culprits I listed have anything to do with this bug. 
UPDATE: Full system freezes still occurred even when no other programs were opened, when Bluetooth was not connected, and when setting vm.max_map_count back to the distro default.

Failed Solutions:
- I tried using TF2 Vulkan, but it just ended up freezing the system immediately like it always had for me. 
- The issue seemingly resolved itself after a few reboots, but that was only because it took more time and relaunches of Steam for it to freeze my system again.
- Reinstalling Steam according to this post https://steamcommunity.com/sharedfiles/filedetails/?id=2307584451 didn't seem to change anything.

Specs:
System: Thinkpad X1 Extreme Gen 5
CPU: I9-12900H
GPU: RTX 3080 Ti, 560.35.03
RAM: 64GB DDR5 4800 MT
OS: Linux Mint 22 Cinnamon, 6.8.0-49-generic, vm.max_map_count = 2147483642

**Comment by BugsyReportsy** [comment] 2024-11-20 20:12
The closest thing I've found to a solution is launching and running the game in windowed mode.

**Comment by NULLYUKI** [comment] 2024-11-20 21:46
Possible duplicate of #6370 ?

**Comment by BugsyReportsy** [comment] 2024-11-20 22:15
> Possible duplicate of #6370 ? 

Probably?

**Comment by kisak-valve** [comment] 2024-11-20 22:25
Closing as a duplicate.

**Closed as not planned by kisak-valve** 2024-11-20 22:25 UTC
Labels: Team Fortress 2, Linux
