### ISSUE TITLE
Tf2 crashes without any log after 64bit update by joining a server/clicking on the "options" button

### ISSUE THREAD

**Issue by kawasakinnn** [ValveSoftware/Source-1-Games#5852] opened 2024-04-21 09:38 UTC
So, i installed 64bit update. Tried to join a server, it told me i was in insecure mode. Restarted the game, yet again tried joining a server-it crashed. Got in a call with a couple of friends, we all tried to fix it. I heard that the problem might be caused by messing up the whole cfg (especially cuz autoexec if it got -dxlevel 80 typed innit), so i deleted all custom files and made my game "naked", but it still got the same problem. Tried changing -dxlevel to 90, 91, 95 and 98, but is still crashes. Even tried -vulkan, but the game itself didn't even launch lol (maybe it's not supported on my pc) Then i launched the old 32bit version, but it was working well surprisingly! Even created my own server with the itemtest map, everything was fine. Got back in 64bit, clicked on the options button and it crashed again. But the advanced options button works as usual, idk what to do in this situation

Windows 8.1 x64 (i know it's not supported this day but who cares if it still works, right)

**Comment by JoriKos** [comment] 2024-04-21 09:44
Duplicate of #5728 and #5674

**Comment by Joshua-Ashton** [comment] 2024-04-21 12:33
Please give more specs on your setup

**Comment by kisak-valve** [comment] 2024-04-21 13:00
Hello @kawasakinnn, as @JoriKos noted, this issue is already being tracked at #5728 and #5674.

Closing as a duplicate.

**Closed by kisak-valve** 2024-04-21 13:00 UTC
