### ISSUE TITLE
[TF2] Most weapons with skins have a broken lightwarp.

### ISSUE THREAD

**Issue by Zadrave** [ValveSoftware/Source-1-Games#4021] opened 2022-07-08 23:30 UTC
A lot of guns, namely the stock ones and ones with war paints, have an issue with their lightwarp where it is softer and flatter than what it is supposed to be. The solution I believe to be a simple vmt edit. You can compare them with certain weapons.

How to reproduce:
Equip a weapon or war painted weapon and check the lighting.

Some image examples.

Rocket launcher has broken lighting.
![5b5ijdf](https://user-images.githubusercontent.com/88107721/178081653-44f0e55a-84c8-444c-a07d-9d978d947879.png)

Rocket jumper with correct harsh lighting.
![IiOY5Jo](https://user-images.githubusercontent.com/88107721/178081750-bb951e81-a3ad-426e-b1e7-ba4044bd5c93.jpg)

Minigun with broken lighting.
![TVzKrYZ](https://user-images.githubusercontent.com/88107721/178081846-ffdaea87-bafb-4950-aa43-629cb51d8808.png)

Natascha with correct harsh lighting.
![MD7uJU7](https://user-images.githubusercontent.com/88107721/178081854-f05fb9e9-7206-4a2b-92b5-d2ff15d0b55e.png)

**Comment by kisak-valve** [comment] 2022-07-08 23:35
Possible duplicate of #2321.

**Comment by Zadrave** [comment] 2022-07-08 23:41
whoops, it is a duplicate indeed.

**Closed** 2022-07-08 23:41 UTC
Labels: Team Fortress 2, Art

**Comment by agrastiOs** [comment] 2022-07-09 12:23
@Zadrave mind reposting the screenshots to #2321?

**Comment by kisak-valve** [comment] 2022-07-09 12:49
Hello @agrastiOs, sure, since this issue report adds some more detail, I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Source-1-Games/issues/2321#issuecomment-1179432161.
