### ISSUE TITLE
launch option -tools not working

### ISSUE THREAD

**Issue by Trakmer** [ValveSoftware/Source-1-Games#5705] opened 2024-04-19 07:52 UTC
After the change to 64 bit the launch option -tools no longer works, the game recognizes the launch option is active because it doesnt let you interact with anything on the main menu outside the console (thats how it used to work) and the short cuts of F10 and F11 that would let you change modes also doesnt work and counts it as normal tf2 inputs.
This option is mostly used for the particle editor in tf2 and i asked some other people if it worked for them but got the same issue.

**Comment by JoriKos** [comment] 2024-04-19 07:56
Duplicate of #5513

**Closed** 2024-04-19 08:26 UTC
