### ISSUE TITLE
[L4D2] [Linux] Survivors are silent

### ISSUE THREAD

**Issue by drakon64** [ValveSoftware/Source-1-Games#6103] opened 2024-06-25 19:48 UTC
When running Left 4 Dead 2 on Linux, the Survivors have no dialogue. Subtitles do not show them talking either.

Infected 'talk' as normal.

I have reproduced this with all Workshop add-ons disabled.

This does not occur when running the game in Proton Experimental.

OS: NixOS 24.05

**Comment by NULLYUKI** [comment] 2024-06-25 23:38
Possible duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/3263 ?

**Comment by drakon64** [comment] 2024-06-26 08:05
Closing as duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/3263

**Closed as not planned** 2024-06-26 08:06 UTC
Labels: Linux, Left 4 Dead 2

**Comment by NULLYUKI** [comment] 2024-06-26 08:55
You can share your own provided information to the other issue, as you shared on which Linux distribution it occurs for you.
