### ISSUE TITLE
DX81 causing game to literally not open

### ISSUE THREAD

**Issue by lithospheree** [ValveSoftware/Source-1-Games#5631] opened 2024-04-19 00:10 UTC
I use dx81 for fps and because I'm a sniper main. The update has forced me to use dx95 as dx81 does not open. I am seeing minimal fps gain (110-120 in combat to 120-125 in combat) while on dx81 i could get 180 in combat no problem. Also, sniper is better to play on dx81 due to the lack of the fisheye effect (hurts my eyes less). Please fix!

**Comment by ChillrendVN** [comment] 2024-04-20 22:02
confirmed problem - dx8 really doesn't work or does it incorrectly! after devs upgraded game to 64 bit it got much worse for me, now there are fps drops in pvp and horrible freezes every second in mvm on dx9, that's why i decided to try dx8, but when i put -dxlevel 80 / -dxlevel 81 in launch options the game simply won't start. there is a way to use a console command to change the dx level while in the game, in this case it would be the mat_dxlevel 81 command, however if you do that, it seems that (at least for me) the graphics settings are reset and configurations like mastercomfig are not read anymore, so no fps gain (i didn't have all these problems before)

**Comment by NULLYUKI** [comment] 2024-04-22 22:12
According to patch [220641](https://www.teamfortress.com/post.php?id=220641)
`Fixed a crash caused by using -dxlevel commands`

This issue requires retesting.

**Comment by kisak-valve** [comment] 2024-06-01 00:39
Closing pending feedback.

**Closed by kisak-valve** 2024-06-01 00:39 UTC
Labels: Team Fortress 2, Windows, Need Retest
