### ISSUE TITLE
[TF2] The Phlogistinator Crits Glitch

### ISSUE THREAD

**Issue by pavUed000** [ValveSoftware/Source-1-Games#5860] opened 2024-04-21 18:16 UTC
There is a new glitch that allows you to get fully critical shots when picking up a Dragon's Fury while using a fully charged Phlogistinator.

**To replicate:**

1. Use the Phlogistinator until you charge the "Mmmph" meter
2. Make sure to have in sight a Dragon's Fury dropped on death by another Pyro, now, without dying, use the alt-fire and as soon as finishing taunting and having crits on on the Phlogistinator, pick up the Dragon's Fury.
3. If done correctly the Dragon's Fury will now shoot Critical Hits only, and it will do so until you die.

**Comment by Bradasparky** [comment] 2024-04-21 19:48
Duplicate of #4070

**Comment by kisak-valve** [comment] 2024-04-21 19:54
Closing as a duplicate.

**Closed by kisak-valve** 2024-04-21 19:54 UTC
Labels: Team Fortress 2
