### ISSUE TITLE
Model doesn't have attachment.

### ISSUE THREAD

**Issue by JoinedSenses** [ValveSoftware/Source-1-Games#2555] opened 2018-04-07 19:45 UTC
Console spam. Reported online in tons of places. Occurs a ton, especially on rocket jump servers. Unknown solution.

"Model '(null)' doesn't have attachment 'backblast' to attach particle system 'rocketbackblast' to."

https://i.imgur.com/M1AIciO.png

**Comment by Combine900** [comment] 2021-11-29 23:08
Can we get a fix for that? It would be a nice thing for the Smissmas 2021 update :)

**Comment by mastercoms** [comment] 2021-12-03 01:53
This seems to be fixed in the Smissmas 2021 update.

![image](https://user-images.githubusercontent.com/2672245/144531245-2ec11769-44c5-4146-89d5-60747344099e.png)

**Comment by Combine900** [comment] 2021-12-03 17:18
> This seems to be fixed in the Smissmas 2021 update.
> 
> ![image](https://user-images.githubusercontent.com/2672245/144531245-2ec11769-44c5-4146-89d5-60747344099e.png)

Indeed, i hope they didnt just hide that problem from the dev-console. However @kisak-valve look like this thread can be closed.

**Comment by mastercoms** [comment] 2021-12-08 22:39
I can confirm that the error message no longer shows in game.

**Comment by JoinedSenses** [comment] 2021-12-08 22:48
id wager all they did was comment out the print statement rather than fixin the actual issue. anyways, nice to know it doesnt spam console any more.

**Comment by mastercoms** [comment] 2021-12-09 02:48
It wasn't a meaningful error afaik

**Comment by Combine900** [comment] 2022-01-02 13:55
Well, can be closed?

**Closed** 2022-02-11 20:05 UTC
Labels: Team Fortress 2, Need Retest
