### ISSUE TITLE
Missing textures in Heavy's eyes

### ISSUE THREAD

**Issue by ArtemUrNeighbor** [ValveSoftware/Source-1-Games#5732] opened 2024-04-19 12:47 UTC
There are missing textures in Heavy's eyes. That's it! His eyes are pink
![Снимок экрана 2024-04-19 154735](https://github.com/ValveSoftware/Source-1-Games/assets/167536615/7b03a67a-5078-43fc-9748-e5fbe388d398)

**Comment by JoriKos** [comment] 2024-04-19 13:18
Dupe of #5717

**Closed** 2024-04-19 13:20 UTC
