### ISSUE TITLE
[TF2] Decorated Weapon icons drawing incorrectly in UI on higher resolutions (fix included)

### ISSUE THREAD

**Issue by rabscootle** [ValveSoftware/Source-1-Games#5593] opened 2024-04-05 06:17 UTC
Hello!

The current version of the stock TF2 HUD has issues with drawing the live icons generated for Decorated Weapons when playing at a higher resolution (1440p or greater):
![image](https://github.com/ValveSoftware/Source-1-Games/assets/108029512/bdb819e7-ddef-4621-a295-fc14d8a7b519)

This affects the killcam, spectate, and inspect UI.

This can be fixed by changing the following params in the "itempanel" class for "ui/hudinspectpanel.res",  "ui/spectator.res", and  "ui/spectatortournament.res" HUD files:
		"model_ypos"		"15"
		"model_center_x"	"1"
		"model_wide"		"82"
		"model_tall"		"55"

Aside from the model_ypos (necessary change for vertical adjustment), the parameter values are identical to those found in the Loadout UI (Resource/UI/FullLoadoutPanel.res), where the issue does not occur.

![image](https://github.com/ValveSoftware/Source-1-Games/assets/108029512/4d61cde6-89da-4de1-872f-a88a6908edd9)

Thanks!

**Comment by kisak-valve** [comment] 2024-04-05 12:57
Hello @rabscootle, please do not intentionally open duplicate issue reports. Closing as a duplicate of #4604.

**Closed by kisak-valve** 2024-04-05 12:57 UTC
