### ISSUE TITLE
[TF2] [LINUX] Corrupted libtcmalloc.so.4  shipped with game

### ISSUE THREAD

**Issue by pnelego** [ValveSoftware/Source-1-Games#5572] opened 2024-03-17 18:29 UTC
libtcmalloc.so.4 corrupted/mislinked/improperly compiled on current release. Replacing it with a fresh version from gperf, allows game to start and run but makes connecting to matches very unreliable, or causes VAC errors.

Here are the calculated MD5 Checksums for each file.

aa027daf22e46fbd3b35bfc5509338f7 libtcmalloc_minimal.so.4 - from gperftools-devel.i686
1c08b62ffa6baffb76e9f0832f930b17 libtcmalloc_minimal.so.4 - from TF2/bin

Steps Taken:
Validating game cache -  (actively replaces the library with the broken one)
Reinstalling the game completely -  (actively replaces the library with the broken one)
Reinstalling operating system - no effect.

This vaguely seems like it could be a Mesa thing, but its still weird that the runtime is shipped with a broken binary

**Comment by kisak-valve** [comment] 2024-03-17 18:48
Hello @pnelego, this issue was tracked upstream at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113258. Closing as a duplicate of #5043.

**Closed by kisak-valve** 2024-03-17 18:48 UTC
