### ISSUE TITLE
[Source 2013] Decals that are supposed to fade, do not fade. 

### ISSUE THREAD

**Issue by StrikerMan780** [ValveSoftware/Source-1-Games#1983] opened 2016-05-19 02:24 UTC
Decals, such as decals/redglowfade.vmt, and decals/combineballfade.vmt, do not fade anymore. If you put those decals up on a wall with UTIL_DecalTrace or straight-up DecalTrace, you'll immediately notice they do not fade away, they'll stay on the wall... glowing... permanently.

I'd fix this myself, but I'd need full source access, which I don't have.

**Comment by kisak-valve** [comment] 2016-12-30 19:57
Closing as a duplicate of #1848.

**Closed by kisak-valve** 2016-12-30 19:57 UTC
