### ISSUE TITLE
[TF2] Re-entering Halloween Karts forces players into an incorrect view angle

### ISSUE THREAD

**Issue by DivaDan** [ValveSoftware/Source-1-Games#4035] opened 2022-07-11 01:45 UTC
Right now, you can give players the halloween kart with condition 82 `(TF_COND_HALLOWEEN_KART)` and control it just fine. The condition overrides your pitch and roll angles to provide a locked over-the-shoulder angle in third person, which is intended. However,  your yaw view angle can be set to unpredictable and unintended values.

From testing, It seems karts have a variable in memory for last stored yaw angle of the kart. By default this value is 0, snapping the player into yaw 0 when they first gain condition 82. This is viewable when using the `cl_showpos 1` command in console. Every time after this though, this default yaw value will be set to whatever angle the player last had when _losing_ condition 82. 

For example, if you give yourself condition 82 (`addcond 82` in console), you'll be set to yaw 0. Turn 90 degrees, and remove condition 82 (`removecond 82` in console.) You'll lose the bumper kart, but preserve your view angles. Now, turn until facing, say, 270, and give yourself condition 82 again. You'll see that your view angle has been snapped back to 90 degrees, completely irrelevant of what angle you had as a player. You also cannot use the `setang` command to fix this, since condition 82 actively overwrites your view angle at all times.

This leads to having extremely little control over what direction a player faces when repeatedly granting them a bumper kart for things such as race tracks, minigames, or otherwise. The ideal function of this condition should still overwrite your pitch and roll angles, but the yaw angle should be whatever yaw angle the player itself had before gaining the condition, rather than whatever the last stored yaw of the kart itself was. 

I recorded a video here of how to reproduce, and what the ideal fix should be-

[![Re-entering Halloween Karts forces players into an incorrect view angle](https://i.imgur.com/UUDBi4X.png)](https://www.youtube.com/watch?v=2ysZRb38KYI "[TF2] Re-entering Halloween Karts forces players into an incorrect view angle")

**Comment by FlaminSarge** [comment] 2022-07-16 09:59
The Halloween Kart cond seems to expect a followup `ForcePlayerViewAngles` usermessage to set the player's pitch/yaw/roll after getting in the kart, for some reason.

The Halloween Kart Cage crash may be due to the relevant models (the cage?) not being precached, so I don't believe that's related to this.

**Comment by TF2CutContentWiki** [comment] 2022-07-16 13:48
Sarge, you are an absolute beauty, bud ✌️

**Comment by DivaDan** [comment] 2022-07-16 17:09
Somehow reworking `ForcePlayerViewAngles` to only force the yaw once you start moving the kart (so your initial yaw is transferred from your unconditioned player state) would be perfect for fixing this particular issue. I don't have access to the code but that 100% sounds like the culprit.

**Comment by TF2CutContentWiki** [comment] 2022-07-17 00:52
> I don't have access to the code but that 100% sounds like the culprit.
My first comment response to this linked to a repo with the code.

[https://github.com/OthmanAba/TeamFortress2/search?q=ForcePlayerViewAngles&type=Code](https://github.com/OthmanAba/TeamFortress2/search?q=ForcePlayerViewAngles&type=Code)

**Comment by FlaminSarge** [comment] 2022-07-17 01:05
It's mentioned in a comment somewhere in CTFPlayerShared's behavior for OnAddHalloweenKart, and Github's search isn't finding it in that repo (but it probably is in that repo somewhere).

**Comment by kisak-valve** [comment] 2022-09-26 20:24
Hello, per "Fixed not preserving the player's current angles when the map has applied the TF_COND_HALLOWEEN_KART condition" in the [2022-09-26](https://www.teamfortress.com/post.php?id=143572) Team Fortress 2 update, please retest this issue.

**Comment by DivaDan** [comment] 2022-09-26 20:27
Just retested, works absolutely flawlessly now!

**Comment by MikhailaTF** [comment] 2022-10-22 16:39
can confirm this works as intended now! ticket can be closed :)

**Comment by Ashetf2** [comment] 2022-10-28 05:13
@DivaDan please close the issue.

**Closed** 2022-10-28 06:23 UTC
Labels: Team Fortress 2, Need Retest
