### ISSUE TITLE
[TF2] many models lack LOD's (Level of details)

### ISSUE THREAD

**Issue by condor00fr** [ValveSoftware/Source-1-Games#5564] opened 2024-03-11 14:15 UTC
LOD's (Level of details) are a set of lower models  used for the purpose of optimisation by reducing RAM and the amout of ressources needed to render a 3D model by your computer, depending on how further or closer you stand from a 3D model, it will change into lesser detailed models with low polygons, in tf2 all models usually have three to four lods to maximise performance.

However, tf2 has encountered many issues regarding this feature such as:

-Many models converted from the old Viewmodel/Worldmodel system into the currently used C_models have seen theirs lods either removed, broken in some ways, wrongly copypasted, left unused or are being used in an incorrect order, meaning that sometimes certain models that should appear with a higher polygone count that they currently do at certain distance, simply don't.

-Many communuty contributed models (including weapons, items, cosmetics and props) as well as certains Valve made Items weren't conceived with LOD's in mind and by extention never got any, meaning that they always render at the highest resolution as they can regardless of how far you actually are from them, and that impacts your client performance a lot!

I made a list here of all 3D models that suffer theses issues that I could find thanks to community findings, with the issues that they suffer froms (and by extention make our computer wanna commit self-termination)

- Medic (Broken strap)
- Demoman (Missing eye)
- Pretty machete (Missing lods)
- Big Earner (Missing lods)
- Vaccinator (Missing Lods + Broken hose)
- Phlogistinator (Lods completely broken and twisted beyon human understanding + Lack proper bone on trigger)
- Rainblower (Missing lods)
- LV2 and LV3 Dispenser (Missing lods)
- Chargin' Targe (Missing lods)
- Destruction PDA (Missing lods)
- Festive Bonesaw (Missing lods) 
- Festive Chargin' Targe (Missing lods)
- Festive Eyelander (Missing lods)
- Festive Jarate (Missing lods)
- Festive Wrangler (Missing lods)
- Fishcake (Missing lods)
- Frying Pan (Missing lods)
- Razorback (Missing lods)
- Sapper (Missing lods)
- Sapper Xmas (Missing lods)
- Snack Attack (Missing lods)
- Wrangler (Missing lods)
- Atomizer (Missing lods)
- Battalion's Backup BackPack (Missing lods)
- Battalion's Backup Banner (Missing lods)
- Big Kill (Missing lods)
- Black Rose (Missing lods)
- Bonk! Atomic Punch & Crit-a-Cola (Missing lods)
- Buff Banner Backpack (Missing lods)
- Buffalo Steak Sandvich (Missing lods)
- Buffalo Steak Sandvich Bitten (Missing lods)
- Bushwacka (Missing lods)
- Candy Cane (Missing lods)
- Diamondback (Missing lods)
- Festive Black Box (Missing lods)
- Festive Bonk! Atomic Punch (Missing lods)
- Festive Buff Banner Backpack (Missing lods)
- Festive Force-A-Nature (Missing lods)
- Festive Holy Mackerel (Missing lods)
- Festive Knife (Missing lods)
- Force-A-Nature (Missing lods)
- Fortified Compound (Missing lods)
- The Bow's Arrow (Missing lods)
- L'Etranger (Missing lods)
- Mad Milk (Missing lods)
- Nessie's Nine Iron (Missing lods) 
- Quick-Fix Backpack (Missing lods)
- Red-Tape Recorder (Missing lods)
- Short Circuit (Missing lods)
 - Thermal Thruster (Missing lods)
- Vaccinator (Missing lods)
- Your Eternal Reward (Missing lods)
- Enforcer (Missing lods + using the Stock Revolver's speed loader model by mistake instead of it's actual custom made one, wich is why said speedloader appears in game with mismatched textures)
- Stock Sniper Rifle (Broken reflective scope effect)
- Iron Bomber (Lods are actually copypasted versions of the highest lod, rendering them useless)

Anyone feel free to uptate this list as to track any other model missing from it, or to remove from said list if issue is addressed in a future uptate.

**Comment by kisak-valve** [comment] 2024-03-11 14:37
Hello @condor00fr, the majority of this issue report is a duplicate of #2470.

Closing in favor of the older issue report.

**Closed by kisak-valve** 2024-03-11 14:37 UTC
