### ISSUE TITLE
How to solve the problem that tf2 should not be launched

### ISSUE THREAD

**Issue by sharkisa** [ValveSoftware/Source-1-Games#5766] opened 2024-04-19 17:54 UTC
i just fixed it on my end, i removed all the launch options under propreties, it works, i had this -novid -noipx -threads 4 -nod3d9ex -nojoy -console
![Captura de pantalla 2024-04-19 125401](https://github.com/ValveSoftware/Source-1-Games/assets/167569105/8e79f3e2-d948-4f26-a840-709c47556f16)
![Captura de pantalla 2024-04-19 125418](https://github.com/ValveSoftware/Source-1-Games/assets/167569105/5e8c322a-402b-4313-89d6-27d854e7faf0)

**Comment by NULLYUKI** [comment] 2024-04-19 17:56
Please use this platform to only report issues.
https://github.com/ValveSoftware/Source-1-Games?tab=readme-ov-file#reporting-issues

**Comment by JoriKos** [comment] 2024-04-19 17:56
Issues should be created for bug reports or feature requests, this is not a general form.

**Comment by ethanholt1** [comment] 2024-04-19 17:57
As others have said; this is a forum for issues, not a general help forum. However, this information may be useful and I would recommend posting it in the r/tf2 subreddit or any other community group.

**Comment by kisak-valve** [comment] 2024-04-19 18:02
Closing as a duplicate of #5631.

**Closed** 2024-04-19 18:01 UTC
