### ISSUE TITLE
[TF2]cant Queue for casual 

### ISSUE THREAD

**Issue by demopan-gaming** [ValveSoftware/Source-1-Games#6079] opened 2024-06-13 20:49 UTC
i have this issue recently that evry time i try to queue for casual it just stops after sometime it does not put me in a server and just stops queueing after about 30 seconds

**Comment by NULLYUKI** [comment] 2024-06-13 20:51
Duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/2820

**Comment by kisak-valve** [comment] 2024-06-13 20:55
Hello @demopan-gaming, as @NULLYUKI noted, this issue is already being tracked at #2820.

Closing as a duplicate.

**Comment by demopan-gaming** [comment] 2024-06-13 20:55
why is this not fixed yet ?

**Closed as not planned by kisak-valve** 2024-06-13 20:55 UTC
