### ISSUE TITLE
My tf2 now has downtimes due to the 64-bit update

### ISSUE THREAD

**Issue by TainPaint** [ValveSoftware/Source-1-Games#5827] opened 2024-04-20 15:10 UTC
It happened to me that while I'm playing my fps was normal before the update but now it's better but there are many drops in fps it bothers me a lot and I can't play my favorite game for some reason I can't do anything until they fix it please help me

**Comment by NULLYUKI** [comment] 2024-04-20 15:11
What OS are you running?
Might be related to https://github.com/ValveSoftware/Source-1-Games/issues/5809

**Comment by TainPaint** [comment] 2024-04-20 15:12
In windows 10

**Comment by TainPaint** [comment] 2024-04-20 15:13
And what can I do to solve it?

**Comment by kisak-valve** [comment] 2024-04-20 15:18
Hello @TainPaint, feel free to continue discussing this issue on the older issue report.

Closing as a duplicate of #5809.

**Closed by kisak-valve** 2024-04-20 15:18 UTC

**Comment by TainPaint** [comment] 2024-04-20 15:24
Thank you
