### ISSUE TITLE
[CS:S] Demo playback is still almost unusable

### ISSUE THREAD

**Issue by hzn01** [ValveSoftware/Source-1-Games#6279] opened 2024-08-16 00:40 UTC
This issue, which is still open, pretty much describes the problem pretty well: https://github.com/ValveSoftware/Source-1-Games/issues/3112

The 'demo_gototick' command is defective and not working which makes demo playback unusable since this command is extremely important. The demo playback suddenly stops and you get one of these two error messages in the console:

Host_Error: CL_PreserveExistingEntity: missing client entity X.
Host_Error: CL_CopyExistingEntity: missing client entity X.

Please push an update to fix this

**Comment by kisak-valve** [comment] 2024-08-16 00:50
Hello @hzn01, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #3112.

**Closed as not planned by kisak-valve** 2024-08-16 00:50 UTC
