### ISSUE TITLE
[HL2DM] Make game free to play

### ISSUE THREAD

**Issue by TF2274** [ValveSoftware/Source-1-Games#2729] opened 2019-01-08 01:03 UTC
The game keeps dying. Valve probably isn't going to make anymore money off of the game (there will always be the few odd players who buy the game, but there will never be a respectable income from it).

There are many people who have played this game for a long time. We miss the days when there were many unique players. On a hl2dm roleplay server, we had to have two servers just to handle the player population. Same for co-op and puzzle servers. There were many DM servers you could join and engage with 10+ players.

Now every DM server left has 0 players except for killbox, there is a single hl2 rp server that has survived, and there is 1 co-op server that still lingers on.

I bought the game, and I am so glad I did because it's one of the most fun games I've played (despite there being a number of bugs and outdated aspects).

Please consider making the game free to play.

**Comment by kisak-valve** [comment] 2019-01-08 01:05
Duplicate of #1697.

**Closed by kisak-valve** 2019-01-08 01:05 UTC

**Comment by TF2274** [comment] 2019-01-08 01:06
Valve just ignores all of the players, and the other "issue" is super old.
