### ISSUE TITLE
[All Source 1 Games] Official WebM video format support in Source 1 beyond TF2

### ISSUE THREAD

**Issue by BreakinBenny** [ValveSoftware/Source-1-Games#6361] opened 2024-09-19 10:54 UTC
https://github.com/ValveSoftware/Source-1-Games/issues/4968

You folks previously implemented WebM support to Team Fortress 2 after gutting out the Bink video format, which was a good move. Can we get this treatment with the other Source games as well? It'd even help cut down the required money upfront for modders who'd otherwise have to license the Bink video tools if they prefer to skip licensing the Source engine.

**Comment by BreakinBenny** [comment] 2024-09-19 10:58
> install this https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw I put the necessary dlls in the archive

What is this? I'm trying to view the contents of it online, for safety's sake.

**Comment by BreakinBenny** [comment] 2024-09-19 11:09
Whatever it was @emadellaloggia tried to send me, I'm not falling for it.

**Comment by kisak-valve** [comment] 2024-09-19 13:24
Hello @BreakinBenny, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #4968.

**Closed as not planned by kisak-valve** 2024-09-19 13:24 UTC
