### ISSUE TITLE
[Linux] TF2 causes system to freeze, computer must be restarted

### ISSUE THREAD

**Issue by JelloMonster118** [ValveSoftware/Source-1-Games#1991] opened 2016-06-19 16:37 UTC
Ubuntu 16.04 LTS, output of sudo lshw ----> http://pastebin.com/DVnW2ESZ
I'm 99% sure it's not my computer and it's the client. I wouldn't be surprised if TF2 wasn't optimized for Linux, wouldn't be the first game.
I'll play for any amount of time (could be 5 minutes, could be 15) on any graphical settings (no difference that I can notice), then my system just... freezes. Doesn't do this with any other games (I can play Bioshock Infinite on the ultra settings but not TF2 on the lowest?) HL2 didn't crash when I try it, I forget what settings I'm playing CSGO on but I'm not surprised it works fine (more support, all not very demanding graphic-wise). So it's just TF2. I'm using an i3-6100 (4-thread skylake).

When I put TF2 in windowed mode with system monitor, hl2_osx reliably uses 30-40% of my CPU and less than 2 gigs of memory on low and medium model/textures (didn't test high, I expect to have minimal increase in CPU use)
Everything works fine until randomly, BAM. Frozen. Audio looping. Never unfreezes. 
BuildID is 1157195, if that matters.

This is a 10 year old game running on a 2 month old build. Anyone else getting an issue like this?

**Comment by Tele42** [comment] 2016-06-19 18:39
Full system freezes are by definition a system issue as no opengl application should be capable of doing this, even if there is a quirk in an individual game, the video stack should handle it gracefully or kill the non-compliant application. For the sake of completeness, you should also include your video driver version in this issue report.

**Comment by JelloMonster118** [comment] 2016-06-19 21:03
@Tele42 If it's a system issue, you can just close the issue. I'm upgrading to Windows soon anyway, and it doesn't look like a lot of people are having full system freezes, so it's not worth enough to look into.

regardless, this is my graphics driver according to my system details: Gallium 0.4 on AMD TONGA (DRM 3.1.0, LLVM 3.8.0)

**Comment by JelloMonster118** [comment] 2016-07-04 23:03
I think I may have found something more actionable.
I've been doing some record-keeping to see if this is really random, and I've found something that may be of interest:
Playing with sheens, skins, or medi-beams I'll get maybe 4 or 5 minutes. (r_drawviewmodels 0 and mat_phong 0 don't change this)
Without a sheen or skin on my weapons, I can get 10-15 minutes before freezing. In some cases I will play long enough I'll change server and class on my own and not freeze. Sometimes I get the freeze while waiting to respawn, but I still think it may be an issue with skins and sheens on OpenGL.
I've actually been able to get 20 minutes with sniper both occasions I've tried it. 
I'll darned if there's no correlation. Let me know what you think about this and if it's really something to be looked into by the devs.


(Also, whenever I turn mat_phong to 0 I get these errors
Error: Material "___fillrate_0" uses unknown shader "FillRate"
Error: Material "___debugnormalmap_1" uses unknown shader "DebugNormalMap"
Error: Material "___debugdrawenvmapmask_2" uses unknown shader "DebugDrawEnvmapMask"
Error: Material "___debugdepth_3" uses unknown shader "DebugDepth"
Error: Material "___debugdepth_4" uses unknown shader "DebugDepth"
Error: Material "debug/debugluxels" uses unknown shader "DebugLuxels"
just thought the devs might like to know because errors are errors for a reason)

**Comment by BMWDriver** [comment] 2016-08-11 00:48
I'm late on this thread here, but I run Mint 18 which is based on Ubuntu 16.04, and I get that very issue, but I'm not sure what folder to pull out a log for TF2. 

I can't recover a TF2 crash, which is surprising considering it's Linux based, so I must shut down hard to restart the PC. I can only mute the sound and after that nothing happens, not even un-muting. Nothing happens no matter what I try to get out of this predicament: ctrl+alt+F1, or ctrl+atl+backspace... Bupkis

I'm now installing HL2 to see if I get the same results. I have an AMD R7 265 which should by default run the radeonsi driver. I understand there is an issue with AMD and their Linux drivers anyhow, until they get a new generation of open drivers to replace the now unsupported fglrx.

**Comment by BMWDriver** [comment] 2016-08-11 03:49
So, no problems with HL2. Not a glitch, played an hour at least, and no crash.

**Comment by apolitech** [comment] 2016-08-13 23:45
Same problem .But the bug is diferent in some os's. in UBuntu unity 16.04.1 you need to restart and in ubuntu mate 16.04.1 you will get logout from the os. in my opinion it's a a conflict with the open source video drivers

**Comment by DrakeJa** [comment] 2016-08-27 13:22
I'm still having the issue on my TONGA R9 380. It seems whenever I try to do damage to an enemy it hangs, loops and get's stuck until I have to do the old hold the power button down trick. It may be a problem with Mesa 11.XX. I'll try getting Mesa 12.1 working on Debian Testing and see if that works.

**Comment by apolitech** [comment] 2016-08-27 13:23
Same problem with mesa 12.1

**Comment by DrakeJa** [comment] 2016-08-27 13:26
Okay well I guess we'll just have to wait for the devs to fix this issue. Every other game I've tested is running just fine. Also forgot to mention I'm using the AMDGPU open source driver.

**Comment by Lindenk** [comment] 2016-11-06 20:49
I would like to add that this is still a problem for me. I'm running an AMD RX480 with the open source amdgpu drivers.

**Comment by a123qwertz567** [comment] 2016-11-11 14:37
@Lindenk and @DrakeJa have you tried using "amdgpu pro"? Today I discovered the same problem. Using an RX 480 with Manjaro and a 4.7 kernel.

**Comment by Lindenk** [comment] 2016-11-12 06:00
The amdgpu pro drivers work, but don't provide much of a performance benefit and break wlc. Ideally, I would like to use the open source drivers instead, as they work with every other game I've tried without a noticeable performance hit.

**Comment by Fornax** [comment] 2016-11-12 21:32
If you're having this problem with the amdgpu or radeon driver, it could be the following problem: [https://github.com/ValveSoftware/Source-1-Games/issues/1943](https://github.com/ValveSoftware/Source-1-Games/issues/1943)

**Comment by a123qwertz567** [comment] 2016-11-13 01:26
@Lindenk I prefer the open source solution, too. I do not plan to install amdgpu pro anyways. Years of linux gaming teached me just stop playing this game an play another.

@Fornax Thanks for the reference. Insane to see this thread is running since 2015. Seems Valve will fix it just randomly with any updates. Maybe they should put more then 3 people and a janitor on this game to dev it.

**Comment by udvarit** [comment] 2016-11-13 22:02
Update: With my RX 460, I can reproduce the `ring 0 stalled` issue with Ubuntu 16.10, AMDGPU driver, latest everything from the official repos. 
The lockup under Windows and with the AMDGPU-PRO driver is different though. It seems like I got the short end of the stick in the silicone lottery, because the card cannot handle its stock clock speed for long. Under Windows, I could underclock the card easily with the bundled WattMan software. But the [AMDGPU-PRO driver only supports overclocking the card](https://www.phoronix.com/scan.php?page=news_item&px=AMDGPU-OverDrive-Kernel), I can't use this feature to underclock, so no TF2 under Linux for me...

**Comment by ElectricTriangle** [comment] 2016-12-13 17:19
https://github.com/ValveSoftware/Source-1-Games/issues/1943
The issue has been resolved in mesa git, scroll down to near the bottom.

**Comment by kisak-valve** [comment] 2016-12-20 13:22
Please update to a build of mesa containing https://cgit.freedesktop.org/mesa/mesa/commit/?id=6dc96de303290e8d1fc294da478c4f370be98dea or wait until a point release that contains that commit. Closing as a duplicate of #1943.

**Closed by kisak-valve** 2016-12-20 13:22 UTC
