### ISSUE TITLE
[TF2] Problems with connecting to non-Valve servers

### ISSUE THREAD

**Issue by Thrash-td** [ValveSoftware/Source-1-Games#1873] opened 2015-03-04 16:21 UTC
### Description

I have a problem with the first per session connection to non-Valve server. Very often (almost everytime) during connection game client freezes on the "Sending client info...", then happens one of two things: either client freezes completely or I, after all, get on the server and get the "WARNING: Connection Problem Auto-disconnect in xx.x seconds" message. (_Also, sometimes, game crashes during "Sending client info..." and throws me out to my desktop_)

In first case (if game completely freezes) I can't Alt+Tab, open terminal (Ctrl+Alt+F1) or even just move mouse. Only thing I can do in this case is reboot with Alt+SysRq+RSEIUB.

Never had such problems with connections to Valve servers.

There also differences in loading time for first connection: for Valve servers it's about 1 minute against 5-[infinite] minutes for all other servers. If game doesn't crashed or completely freezed after first (even failed) connection to non-Valve server, then next connection to any server will pass flawlessly for ~20 seconds. Attempts to connect to the Valve servers first before connecting to others does not help.
### Steps for reproducing
1. Open the game
2. Click "Servers"
3. Pick random non-Valve server (for example: skial server)
4. Join game (there will be temporary or complete freezes at "Sending client info...")
### System information

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0xf
    CPU Stepping:  0x6
    CPU Type:  0x0
    Speed:  2128 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.04.2 LTS (32 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-45-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  NVIDIA Corporation GeForce GTS 250/PCIe/SSE2

    Driver Version:  3.3.0 NVIDIA 331.113
    OpenGL Version: 3.3
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x615
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 16,14" x 10,12"  (19,02" diag)
                                            41,0cm x 25,7cm  (48,3cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: CA0106

Memory:
    RAM:  2015 Mb

Miscellaneous:
    UI Language:  English
    LANG:  ru_RU.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  298311 Mb
    Largest Free Hard Disk Block:  40032 Mb

Installed software:

Recent Failure Reports:
    Wed Mar  4 14:25:59 2015 GMT: file ''/tmp/dumps/assert_20150304171852_2.dmp'', upload yes: ''CrashID=bp-84414b32-930e-4cf7-aabf-49cc22150304''
    Wed Mar  4 14:26:01 2015 GMT: file ''/tmp/dumps/crash_20150304172556_2.dmp'', upload yes: ''CrashID=bp-355ad65c-cb99-4fbd-8d88-f0eb12150304''
    Wed Mar  4 14:26:06 2015 GMT: file ''/tmp/dumps/assert_20150304171557_1.dmp'', upload yes: ''CrashID=bp-5ce48aef-6eaf-4961-b161-437bf2150304''
    Wed Mar  4 14:26:28 2015 GMT: file ''/tmp/dumps/assert_20150304172621_4.dmp'', upload yes: ''CrashID=bp-7019233b-b4f3-4f1c-8f2e-de82b2150304''
```

**Comment by 50Wliu** [comment] 2015-03-20 20:00
I have a very similar problem.
There's a ~50% chance that TF2 will lock up for around 5 minutes when I try to connect to the first server.  Never bothered to notice if it ever happened on Valve servers though.  After the first freeze (assuming TF2 doesn't hard crash and bring Steam along with it), all subsequent connections are fine.

Reproduced on both 14.04 and 14.10 with a nVidia Geforve 525M (nvidia-331-updates).

**Comment by s0r00t** [comment] 2015-07-10 00:36
Have you tried running Steam in a terminal and getting its output? Something about your problems might be in the logs.

**Comment by 50Wliu** [comment] 2015-07-10 01:52
> Have you tried running Steam in a terminal and getting its output? Something about your problems might be in the logs.

I've stopped running into this after I reinstalled TF2, so it doesn't have to do with Steam.

**Comment by s0r00t** [comment] 2015-07-10 22:02
Steam's terminal output is also the game's terminal output. So it can help.
If the issue is not here, you should edit the title to show it, as Valve dropped this repo.

**Comment by 50Wliu** [comment] 2015-07-10 22:49
@s0r00t Thanks, didn't know that Steam also showed each game's output.

I can't close this issue since I wasn't the original reporter: @Thrash-td?

**Comment by Thrash-td** [comment] 2015-07-13 22:55
Well, it seems, the problem has vanished (for me at least) a few weeks ago.

**Comment by kisak-valve** [comment] 2016-12-30 00:36
Closing per the last comment.

**Closed by kisak-valve** 2016-12-30 00:36 UTC
