### ISSUE TITLE
[HL2+ep] water reflection corrupt at certain viewing angles

### ISSUE THREAD

**Issue by johndrinkwater** [ValveSoftware/Source-1-Games#647] opened 2013-05-13 12:56 UTC
Trying to turn #573 into single issues.

@pfannkuchengesicht said water refractions corrupt at certain viewing angles(mostly flickers between normal and buggy look):
![08](http://cloud-2.steampowered.com/ugc/559848462376622488/7A8661787349EF744BC73B9CFAF6FF3F39451EE2/)
![09](http://cloud-2.steampowered.com/ugc/559848462376639085/4D9386E5169FBA353AC584582878CB905A20B367/)

**Comment by koraktor** [comment] 2015-06-01 19:46
@johndrinkwater Is this still being worked on?

I just discovered flickering water reflections while starting to play Half-Life 2: Update, but it also occurs on plain Half-Life 2 now. I’m on OS X 10.10.4 on an MacBook Pro (Early 2011) with an AMD Radeon HD 6490M.
The flickering stops while Steam notifications are displayed, so Steam Overlay might be involved, too. Disabling it didn’t had an effect, though.

This wasn’t a problem when Source games were initially released on OS X.

**Comment by koraktor** [comment] 2015-06-04 09:33
Well, looks like this was fixed in yesterday’s engine update. There is no update news, but Steam did load 4.9MB.

**Comment by koraktor** [comment] 2015-06-05 20:32
Seams like it was only working by chance. While not changing anything, the problem is now back.

**Comment by Tele42** [comment] 2015-06-09 13:19
The majority of updates to HL2 happening right now are from OpenVR's depot. You find some basic insight as to what depots changed at https://steamdb.info/app/220/history/.

@johndrinkwater is a community moderator, not a valve employee, as such would not have that kind of information.

**Comment by koraktor** [comment] 2015-06-09 14:03
@Tele42 thanks for the information.

The issue again vanished after the latest update (about two days ago, seems to be related to OpenVR again). I will check if this fix is more persistent.

**Comment by kisak-valve** [comment] 2016-12-23 00:38
Closing as general video driver quality from 2013 is no longer relevant. If anyone is still experiencing this issue with an up to date system, please open a new issue report.

**Closed by kisak-valve** 2016-12-23 00:38 UTC
Labels: Half-Life 2, Half-Life 2: Episode One, Half-Life 2: Episode Two
