### ISSUE TITLE
[TF2] [Feature Request] Map Timers for Neutral Objective Modes in Casual Matchmaking

### ISSUE THREAD

**Issue by leo-proct** [ValveSoftware/Source-1-Games#4953] opened 2023-05-11 15:01 UTC
Currently Capture the Flag and Control Points (5CP) in casual have no current map timer. This leads to some matches persisting way longer than necessary. This is especially the case with 5CP where stalemates don't add to the existing win condition to change the map and prolongs the match even longer.

Please consider adding a mp_timelimit of something like 30 or 45 mins in order to prevent stalemate.

**Comment by kisak-valve** [comment] 2023-05-11 15:11
Hello @leo-proct, this is functionally a duplicate of #3402. Closing as a duplicate.

**Closed by kisak-valve** 2023-05-11 15:11 UTC
