### ISSUE TITLE
[TF2] Enable tf_viewmodels_offset_override in Casual, MVM and Competitive

### ISSUE THREAD

**Issue by JonaMake** [ValveSoftware/Source-1-Games#4252] opened 2022-09-06 21:25 UTC
tf_viewmodels_offset_override - This is the best console command to change viewmodel fov. In conjunction with other console commands (viewmodel_fov and tf_use_min_viewmodels) this will allow players to customize the game as they like

**Comment by AzureAzel** [comment] 2022-09-06 22:11
Duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/2484.

**Comment by kisak-valve** [comment] 2022-09-06 22:46
Hello @JonaMake, as @AzureAzel noted, this issue is already being tracked in the older issue report.

Closing as a duplicate.

**Closed by kisak-valve** 2022-09-06 22:46 UTC
