### ISSUE TITLE
[TF2] Workshop maps missing soundscapes, sound overrides, custom sounds #2701

### ISSUE THREAD

**Issue by Sreap** [ValveSoftware/Source-1-Games#3232] opened 2020-04-08 07:43 UTC
Please forgive me if duplicate/similar posts are not allowed. I just created this account so I could stress the importance of this issue. Below is a quote from Nosoop where he posted about it almost a year ago even though this seems to have been a bug since the release of the workshop. As stated below, if your map has a soundscape.txt file and you load your map via 'map workshop/12345678', the soundscapes are not going to play. I would really like this fixed. I really want to share my creations but not if my soundscapes aren't going to work.

 

> I guess since this exists I'll report it here. Seems to have more transparency than the game's built-in bug reporter where I reported this previously.
> 
> The following issues are present for Workshop maps in TF2:
> 
> Sounds embedded in maps cannot be played on the client. The engine reports the following error in the developer console:
> 
> Cannot figure out which search path %s came from. Absolute path is %s
> 
> It can be reproduced by running map workshop/1171267245 in the server console to load the Workshop version of Monster Bash.
> 
> Soundscape and soundscript (sound override) files are not loaded in at all. There are no "generic" variations of either, unlike the embed.nav support for navigation meshes.
> 
> I've written my own server-sided fix for this as a SourceMod plugin, though it's obviously limited to sounds that are emitted from the server.
> Unfortunately, these issues make for a subpar experience when playing Workshop maps.

**Comment by ICantShoot** [comment] 2020-04-08 11:40
This is a known issue to them. They already implemented fix for nav files not correctly working within workshop files as embed.nav and i assume that the rest of the stuff that wasnt working was ment to be fixed same way. However, development of this game is not the same as it used to. This may never happen untill there arent more important things to work on.

**Comment by kisak-valve** [comment] 2020-04-08 12:39
Hello @Sreap, there's no value in fragmenting a discussion over multiple issue reports. Please do not intentionally open duplicate issue reports.

Closing as a duplicate of #2701.

**Closed by kisak-valve** 2020-04-08 12:39 UTC
