### ISSUE TITLE
[HLS] Crowbar incorrect impact sounds

### ISSUE THREAD

**Issue by OrutoOtaku** [ValveSoftware/Source-1-Games#1866] opened 2015-01-14 19:39 UTC
Anything I hit in Half Life: Source will always make the sound of hitting metal, how do i fix this? It is killing my ear.

**Comment by Tele42** [comment] 2015-01-14 21:34
Random user who opened #1189 claims that this is the expected behavior from goldsrc.

**Comment by OrutoOtaku** [comment] 2015-01-15 03:46
I still don't know how to fix the issue, even though this started happening recently, it only started a couple months ago

**Comment by 1157** [comment] 2015-01-16 21:39
// This is HL1 material defs ONLY
// UNDONE: DO NOT REDEFINE HL2 MATERIALS HERE!

"crowbar"
{
	"base"		"metal"
	"impactsoft"	"Weapon_Crowbar.Melee_HitWorld"
	"impacthard"	"Weapon_Crowbar.Melee_HitWorld"
}

$surfaceprop

The $surfaceprop command links the surface of either a material or model to a set of physical properties, including:

    What sounds are emitted during collisions
    What effects are emitted when the surface is shot
    Mass, buoyancy, bounciness...
    The effect of the surface on nearby sounds (reverberation, echo, absorption...)

**Everything the crowbar strikes returns "metal" sound.Paper.wood,concrete, ect.
It should follow the $surfaceprop defined in .vmt's but it does not I.E. (below)

"LightmappedGeneric"
{
	"$basetexture" "11custom/11_plank2a"
	"$surfaceprop" "Wood_Panel"
}

**Comment by Alulim** [comment] 2015-11-01 02:30
How does this explain how to fix the issue? All I'm seeing is a wall of text. Please, I'm at my wit's end with this.

**Comment by kisak-valve** [comment] 2016-12-30 00:23
Closing as this appears to be the intended behavior.

**Comment by kisak-valve** [comment] 2016-12-30 14:24
Sorry for re-sending this close message. Closing as this appears to be the intended behavior.

**Closed by kisak-valve** 2016-12-30 14:24 UTC
Labels: Half-Life: Source
