### ISSUE TITLE
6 Year Old Bug: INFINITE BOT RAGE HACKERS!!!!!!!

### ISSUE THREAD

**Issue by compromisable** [ValveSoftware/Source-1-Games#5686] opened 2024-04-19 03:37 UTC
WHY DO YOU PERMIT THE USE OF LITERALLY THOUSANDS OF BOTS TO RUIN YOUR GAME FOR THE PAST SIX YEARS?

WHY, WHY!!!!????

**Comment by StShAzzy** [comment] 2024-04-19 04:42
bro chill, the only dev in the game can't do shit about it

**Comment by compromisable** [comment] 2024-04-19 06:53
If only Valve spent 0.00000000001% of their annual revenue to updating the anti-cheat, or hiring a real developer to implement a captcha system/phone verification ;-;

**Comment by JoriKos** [comment] 2024-04-19 07:14
> If only Valve spent 0.000000000000000000000000001% of their annual revenue to updating the anti-cheat, or hiring a real developer to implement a captcha system/phone verification ;-;

You're massively oversimplifying the issue. Throwing money at the problem or "just adding a captcha" is not going to solve anything, and shows you don't really know what you're talking about. Also calling the current developers not "real developers" is unnecessarily insulting.

>    1. Improve anti-cheat detection
> 
>    2. Ban accounts based on consistent bot-like behavior
> 
>    3. Collaborate with the anti-cheat community for new strategies
> 
>    4. Streamline bot reporting for players
> 
>    5. Implement a trusted community moderator system
> 
>    6. Optimize the votekick system for bot removal
> 
>    7. Increase barriers to creating matchmaking-eligible accounts (ie, phone verification/captcha)
> 
>    8. Increase communication with the community about anti-bot efforts

1. The only thing that would work. 
2. Would be too easy to bypass, or it would be catching innocent players. Horrible solution overall.
3. Valve has enough resources themselves to combat it, they just need to get on it.
4. Reporting is already incredibly easy, not sure how you would "streamline" clicking 2 buttons.
5. Giving random players the ability to VAC people is a horrible idea, I think the TF2 community has shown they can't handle the slightest bit of power. At most you'd have to implement the whole Overwatch system from CS:GO.
6. Band-aid solution
7. Excluding people for no reason, captcha is useless and phone verification would exclude people unnecessarily. Also another band-aid solution.
8. You should never announce anti-cheat changes you've made, as that just helps the cheat developers bypass them.

**Comment by compromisable** [comment] 2024-04-19 15:34
> > If only Valve spent 0.000000000000000000000000001% of their annual revenue to updating the anti-cheat, or hiring a real developer to implement a captcha system/phone verification ;-;
> 
> You're massively oversimplifying the issue. Throwing money at the problem or "just adding a captcha" is not going to solve anything, and shows you don't really know what you're talking about. Also calling the current developers not "real developers" is unnecessarily insulting.
> 
> > 1. Improve anti-cheat detection
> > 2. Ban accounts based on consistent bot-like behavior
> > 3. Collaborate with the anti-cheat community for new strategies
> > 4. Streamline bot reporting for players
> > 5. Implement a trusted community moderator system
> > 6. Optimize the votekick system for bot removal
> > 7. Increase barriers to creating matchmaking-eligible accounts (ie, phone verification/captcha)
> > 8. Increase communication with the community about anti-bot efforts
> 
> 1. The only thing that would work.
> 2. Would be too easy to bypass, or it would be catching innocent players. Horrible solution overall.
> 3. Valve has enough resources themselves to combat it, they just need to get on it.
> 4. Reporting is already incredibly easy, not sure how you would "streamline" clicking 2 buttons.
> 5. Giving random players the ability to VAC people is a horrible idea, I think the TF2 community has shown they can't handle the slightest bit of power. At most you'd have to implement the whole Overwatch system from CS:GO.
> 6. Band-aid solution
> 7. Excluding people for no reason, captcha is useless and phone verification would exclude people unnecessarily. Also another band-aid solution.
> 8. You should never announce anti-cheat changes you've made, as that just helps the cheat developers bypass them.

"The only thing that would work."  False. A complex issue like the bot crisis demands a multi-faceted solution. No single approach is a magic bullet.

"Would be too easy to bypass...  Every anti-cheat measure faces this challenge.  It's an ongoing battle; the point is to raise the bar high enough to deter most bot creators.  Plus, focusing on behavior patterns can avoid accidentally punishing skilled players.

"Valve has enough resources...   Resource allocation is complex. Even big companies have to prioritize. However, the sustained damage to TF2's reputation IS a financial cost that Valve might be forced to pay more attention to.

"Reporting is already incredibly easy..."  True, the basic function exists. But, streamlining means better categorization of reports (specifically flagging bots) for more efficient investigation and prioritization by Valve.

"Giving random players...   Nobody said "VAC" powers. It's about temporary server moderation – kicks and short bans to clear the immediate problem, with Valve reviewing for permanent action. The Overwatch system is a fair point but implementing a basic version could provide much-needed immediate relief.

"Band-aid solution."  Partially true. Votekicking needs improvement, but it can be a part of a larger toolkit. It's about making it more effective, not relying on it as the sole answer.

"Excluding people for no reason...  The goal isn't to exclude legitimate players forever, it's to make bot creation more tedious.  Small barriers deter mass bot production. It's a trade-off: mild inconvenience for new players vs. servers overrun by bots.

"You should never announce..." True for specifics.  But public acknowledgement that work is being done is different from revealing technical details, and it reassures the community that they aren't being ignored.

**Comment by ethanholt1** [comment] 2024-04-19 17:09
> > > If only Valve spent 0.000000000000000000000000001% of their annual revenue to updating the anti-cheat, or hiring a real developer to implement a captcha system/phone verification ;-;
> > 
> > 
> > You're massively oversimplifying the issue. Throwing money at the problem or "just adding a captcha" is not going to solve anything, and shows you don't really know what you're talking about. Also calling the current developers not "real developers" is unnecessarily insulting.
> > > 1. Improve anti-cheat detection
> > > 2. Ban accounts based on consistent bot-like behavior
> > > 3. Collaborate with the anti-cheat community for new strategies
> > > 4. Streamline bot reporting for players
> > > 5. Implement a trusted community moderator system
> > > 6. Optimize the votekick system for bot removal
> > > 7. Increase barriers to creating matchmaking-eligible accounts (ie, phone verification/captcha)
> > > 8. Increase communication with the community about anti-bot efforts
> > 
> > 
> > 
> > 1. The only thing that would work.
> > 2. Would be too easy to bypass, or it would be catching innocent players. Horrible solution overall.
> > 3. Valve has enough resources themselves to combat it, they just need to get on it.
> > 4. Reporting is already incredibly easy, not sure how you would "streamline" clicking 2 buttons.
> > 5. Giving random players the ability to VAC people is a horrible idea, I think the TF2 community has shown they can't handle the slightest bit of power. At most you'd have to implement the whole Overwatch system from CS:GO.
> > 6. Band-aid solution
> > 7. Excluding people for no reason, captcha is useless and phone verification would exclude people unnecessarily. Also another band-aid solution.
> > 8. You should never announce anti-cheat changes you've made, as that just helps the cheat developers bypass them.
> 
> "The only thing that would work." False. A complex issue like the bot crisis demands a multi-faceted solution. No single approach is a magic bullet.
> 
> "Would be too easy to bypass... Every anti-cheat measure faces this challenge. It's an ongoing battle; the point is to raise the bar high enough to deter most bot creators. Plus, focusing on behavior patterns can avoid accidentally punishing skilled players.
> 
> "Valve has enough resources... Resource allocation is complex. Even big companies have to prioritize. However, the sustained damage to TF2's reputation IS a financial cost that Valve might be forced to pay more attention to.
> 
> "Reporting is already incredibly easy..." True, the basic function exists. But, streamlining means better categorization of reports (specifically flagging bots) for more efficient investigation and prioritization by Valve.
> 
> "Giving random players... Nobody said "VAC" powers. It's about temporary server moderation – kicks and short bans to clear the immediate problem, with Valve reviewing for permanent action. The Overwatch system is a fair point but implementing a basic version could provide much-needed immediate relief.
> 
> "Band-aid solution." Partially true. Votekicking needs improvement, but it can be a part of a larger toolkit. It's about making it more effective, not relying on it as the sole answer.
> 
> "Excluding people for no reason... The goal isn't to exclude legitimate players forever, it's to make bot creation more tedious. Small barriers deter mass bot production. It's a trade-off: mild inconvenience for new players vs. servers overrun by bots.
> 
> "You should never announce..." True for specifics. But public acknowledgement that work is being done is different from revealing technical details, and it reassures the community that they aren't being ignored.

I don’t mean to be rude but I think we’ve reached that point. Valve has gone on record saying that they’re working on it on the TF2 Twitter and that they’re listening to the community. Are you expecting them to document every single byte changed in the executable? 
Besides, community servers have almost perfect anti cheat. Just go play there.

**Comment by compromisable** [comment] 2024-04-20 01:18
![image](https://github.com/ValveSoftware/Source-1-Games/assets/147524755/42b2d7ea-9499-410c-a418-7f6ac1ec6932)
### What's the plan, guys?
After 6 years, I think we should make a single attempt here. Let's turn this into a thinktank!

**Comment by erickoid** [comment] 2024-04-20 01:24
Remove the -textmode parameter that just about every bot uses and no regular human I've  ever come       across has used

**Comment by ethanholt1** [comment] 2024-04-20 03:09
> ### What's the plan, guys?
> After 6 years, I think we should make a single attempt here. Let's turn this into a thinktank!

I was thinking about implementing Overwatch? Humans are the best anti cheat and can, usually, tell when someone’s hacking.

**Comment by wgetJane** [comment] 2024-04-20 04:36
i feel like this discussion would fit better in the following places:

- https://www.reddit.com/r/tf2/submit?selftext=true
- https://steamcommunity.com/app/440/discussions/

**Comment by erickoid** [comment] 2024-04-20 15:39
> > ### What's the plan, guys?
> > After 6 years, I think we should make a single attempt here. Let's turn this into a thinktank!
> 
> I was thinking about implementing Overwatch? Humans are the best anti cheat and can, usually, tell when someone’s hacking.
Bandaid solution since it doesnt solve hackers in CSGO and everyone plays faceit because of it ;\

> 
> > **Remove the -textmode launch parameter that just about every bot uses and no regular human I've ever come across has used**
> 
> This is a bandaid solution, and I believe some servers use text mode. And even if valve did implement this, it’d take maybe a day for the cheaters to change to graphical mode and run their bots again.
srcds is different from the client version of the game innit, also how do you know for sure that wouldnt work have you seen anyone do what you just said?




> i feel like this discussion would fit better in the following places:
> 
> * https://www.reddit.com/r/tf2/submit?selftext=true
> * https://steamcommunity.com/app/440/discussions/

developer(s) don't seem to care so might as well bring the discussion closer to them maybe they might read

**Comment by erickoid** [comment] 2024-04-20 15:40
> > ### What's the plan, guys?
> > After 6 years, I think we should make a single attempt here. Let's turn this into a thinktank!
> 
> I was thinking about implementing Overwatch? Humans are the best anti cheat and can, usually, tell when someone’s hacking.
> 
Bandaid solution since it doesnt solve hackers in CSGO and everyone plays faceit because of it ;\
> > **Remove the -textmode launch parameter that just about every bot uses and no regular human I've ever come across has used**
> 
> This is a bandaid solution, and I believe some servers use text mode. And even if valve did implement this, it’d take maybe a day for the cheaters to change to graphical mode and run their bots again.

srcds is different from the client version of the game innit, also how do you know for sure that wouldnt work have you seen anyone do what you just said?

**Comment by erickoid** [comment] 2024-04-20 15:41
> i feel like this discussion would fit better in the following places:
> 
> * https://www.reddit.com/r/tf2/submit?selftext=true
> * https://steamcommunity.com/app/440/discussions/

that hasn't worked. time to  bring the discussion closer to the devs (aka here, on github) so they might read or listen?

**Comment by JoriKos** [comment] 2024-04-20 15:45
> that hasn't worked. time to bring the discussion closer to the devs (aka here, on github) so they might read or listen?

I can entirely assure you, the devs are aware of this, but that doesn't mean it's going to change anything. Talking about it here is no use, contact some anti-cheat engineers at Valve instead perhaps?

**Comment by compromisable** [comment] 2024-04-20 15:50
> > that hasn't worked. time to bring the discussion closer to the devs (aka here, on github) so they might read or listen?
> 
> I can entirely assure you, the devs are aware of this, but that doesn't mean it's going to change anything. Talking about it here is no use, contact some anti-cheat engineers at Valve instead perhaps?

The anti-cheat devs at valve have already designed a good anticheat, ( # CSGO2? ), the developers at tf2 need simply to update their version or implement literally any other anti cheat ever

even garry's mod has basic lua anti cheats that are more effective then the present version of VAC

**Comment by JoriKos** [comment] 2024-04-20 15:52
> The anti-cheat devs at valve have already designed a good anticheat

Everyone complains constantly about a large amount of cheaters and VAC not working, though? Anti-cheat engineers are the ones responsible for updating VAC, which needs to be tailored to each game specifically, not just ran across every game.

Talking about it here is pointless, especially as there is no bug being reported or no feature being requested, just someone yelling about VAC.

**Comment by compromisable** [comment] 2024-04-20 15:55
> > The anti-cheat devs at valve have already designed a good anticheat
> 
> Everyone complains constantly about a large amount of cheaters and VAC not working, though? Anti-cheat engineers are the ones responsible for updating VAC, which needs to be tailored to each game specifically, not just ran across every game.
> 
> Talking about it here is pointless, especially as there is no bug being reported or no feature being requested, just someone yelling about VAC.

Nobody is yelling about VAC, people are providing solutions to a problem that renders the game practically unplayable, my little devils contrarian. 

And those people who tailor VAC to their game are the develops of said game... In this case, the TF2 devs... Go to sleep now

**Comment by JoriKos** [comment] 2024-04-20 16:08
>  people are providing solutions to a problem that renders the game practically unplayable

Nothing productive is being said here. I'm not being a "devils contrarian", posts like these are not what this place is for and only serve to clog it up.

> And those people who tailor VAC to their game are the develops of said game... In this case, the TF2 devs... And they've done it before... 

Based on this comment I'm assuming you're largely unfamiliar with game development. The team responsible for adding content, fixing bugs, etc. for TF2 is a completely different team than the one that's responsible for anti-cheat.

And calm it with the name-calling, will you.

@kisak-valve Although you're the better judge, I think this issue (and any further VAC issues) should probably be closed.

**Comment by compromisable** [comment] 2024-04-20 16:31
> > people are providing solutions to a problem that renders the game practically unplayable
> 
> Nothing productive is being said here. I'm not being a "devils contrarian", posts like these are not what this place is for and only serve to clog it up.
> 
> > And those people who tailor VAC to their game are the develops of said game... In this case, the TF2 devs... And they've done it before...
> 
> Based on this comment I'm assuming you're largely unfamiliar with game development. The team responsible for adding content, fixing bugs, etc. for TF2 is a completely different team than the one that's responsible for anti-cheat.
> 
> And calm it with the name-calling, will you.
> 
> @kisak-valve Although you're the better judge, I think this issue (and any further VAC issues) should probably be closed.


The mere fact that these posts exist are productive in themselves, it shows the community demands reform and is tired of dealing with the unbearable weight of the bot crisis. You're wanting of the thread to be shut down makes me think you are on the side of the cheat developers.

**Comment by erickoid** [comment] 2024-04-20 16:33
> > people are providing solutions to a problem that renders the game practically unplayable
> 
> Nothing productive is being said here. I'm not being a "devils contrarian", posts like these are not what this place is for and only serve to clog it up.
Nothing productive has been done about this issue. Talking is the only option we have as a community and you call that unproductive? That seems very odd, no regular player would object to talking about this.
> 
> > And those people who tailor VAC to their game are the develops of said game... In this case, the TF2 devs... And they've done it before...
> 
> Based on this comment I'm assuming you're largely unfamiliar with game development. The team responsible for adding content, fixing bugs, etc. for TF2 is a completely different team than the one that's responsible for anti-cheat.
> 
> And calm it with the name-calling, will you.
......??
> 
> @kisak-valve Although you're the better judge, I think this issue (and any further VAC issues) should probably be closed.
And continue speaking into the void that is the community hub and reddit?

**Comment by compromisable** [comment] 2024-04-20 16:33
> > > people are providing solutions to a problem that renders the game practically unplayable
> > 
> > 
> > Nothing productive is being said here. I'm not being a "devils contrarian", posts like these are not what this place is for and only serve to clog it up.
> > Nothing productive has been done about this issue. Talking is the only option we have as a community and you call that unproductive? That seems very odd, no regular player would object to talking about this.
> > > And those people who tailor VAC to their game are the develops of said game... In this case, the TF2 devs... And they've done it before...
> > 
> > 
> > Based on this comment I'm assuming you're largely unfamiliar with game development. The team responsible for adding content, fixing bugs, etc. for TF2 is a completely different team than the one that's responsible for anti-cheat.
> > And calm it with the name-calling, will you.
> > ......??
> > @kisak-valve Although you're the better judge, I think this issue (and any further VAC issues) should probably be closed.
> > And continue speaking into the void that is the community hub and reddit?

Nice formatting, appreciate the effort kid but stick to the steam discussion.

**Comment by JoriKos** [comment] 2024-04-20 16:37
> Your wanting of the thread to be shut down makes me think you are on the side of the cheat developers.

If that's what you want to believe, but if you're gonna make this personal there's literally no point in talking to you.

**Comment by erickoid** [comment] 2024-04-20 16:38
> > Your wanting of the thread to be shut down makes me think you are on the side of the cheat developers.
> 
> If that's what you want to believe, but if you're gonna make this personal there's literally no point in talking to you. Having the github be filled with posts like this hides the actual problems that the devs checking this repo can fix.

This is a technical issue, and a big issue for the game..

**Comment by JoriKos** [comment] 2024-04-20 16:40
> This is a technical issue, and a big issue for the game..

This is neither a bug nor a feature request.

**Comment by compromisable** [comment] 2024-04-20 16:41
> > Your wanting of the thread to be shut down makes me think you are on the side of the cheat developers.
> 
> If that's what you want to believe, but if you're gonna make this personal there's literally no point in talking to you. Having the github be filled with posts like this hides the actual problems that the devs checking this repo can fix.

If you think that 6 years of unplayability is not an "actual problem", you need to reevulate your definition of problem.  

This believe is entirely empirical and can be deduced through  deductive reasoning. 

This believe is equatable to that of the existence of the subjective "I". The foundation of epistemology!



> > This is a technical issue, and a big issue for the game..
> 
> This is neither a bug nor a feature request.

The feature is anything that stops thousands of bots from ruining the game every day for 6 years straight


Goodnight, devils advocate/cheat developer!

**Comment by JoriKos** [comment] 2024-04-20 16:45
> If you think that 6 years of unplayability is not an "actual problem", you need to reevulate your definition of problem.

I never said this, I said it's not a problem the devs looking at the github can actually fix.

> Goodnight, devils advocate/cheat developer!

Being rude is not helping anyone, are you here to actually have a constructive discussion or just to insult me because you don't like what I'm telling you? I'm unsubscribing from this issue now, reconsider if you wanna be helpful or nothing but a burden to all present.

**Comment by compromisable** [comment] 2024-04-20 16:48
> > Your wanting of the thread to be shut down makes me think you are on the side of the cheat developers.
> 
> If that's what you want to believe, but if you're gonna make this personal there's literally no point in talking to you. Having the github be filled with posts like this hides the actual problems that the devs checking this repo can fix.

If you think that 6 years of unplayability is not an "actual problem", you need to reevulate your definition of problem.  

This believe is entirely empirical and can be deduced through  deductive reasoning. 

This believe is equatable to that of the existence of the subjective "I". The foundation of epistemology!



> > This is a technical issue, and a big issue for the game..
> 
> This is neither a bug nor a feature request.

The feature is anything that stops thousands of bots from ruining the game every day for 6 years straight

**Comment by erickoid** [comment] 2024-04-20 17:00
Okay now that troll is gone, I suggest remove -textmode

**Comment by ethanholt1** [comment] 2024-04-20 18:13
> Bots being forced to switch to graphical TF2 ensures that the numbers will dramatically drop, as the amount of resources it would take to achieve the 100+ numbers some hosts have would no longer be remotely possible.
> 
> At best, most players would only come across 1 or 2 bots a day, at worst, one host who owns a massive VPS chunks their money into it to maintain 50 bots.
> 
> It still is not a fix-all solution, but its sacrifice does help reduce the severity of the issue as the feature itself is not needed.

I can agree with you on Overwatch, but I do not believe that removing text mode will have the impact you think it will. I don’t mean to be rude, but bot hosters have access to very, very, very powerful hardware. They would still be able to run maybe around 10-20 instances per machine, which is still a pretty decent amount. However, I do agree that this would work in some capacity in limiting the number of bots until a more permanent solution is provided.

**Comment by ethanholt1** [comment] 2024-04-20 18:17
> Your wanting of the thread to be shut down makes me think you are on the side of the cheat developers.

Can we please not devolve into a flame war. This is supposed to be an issues forum, not r/tf2.

**Comment by wgetJane** [comment] 2024-04-21 02:24
removing things like -textmode, linux support, or the retry command will not fix anything

believe it or not, when steam updates a game, it doesn't magically wipe all previous versions of the game from every computer on earth

in fact, even if you fail to prevent steam from updating your game, you can easily acquire the previous version using [DepotDownloader](https://github.com/SteamRE/DepotDownloader) or by simply asking for it from someone that still has the previous version of the game

also, textmode is a feature that is so non-trivial for cheaters to reimplement even if it gets removed

seriously, it's literally just running the game without graphics, do you really think that that's such a difficult thing for a cheater to do

**Comment by compromisable** [comment] 2024-04-21 02:26
> removing things like -textmode, linux support, or the retry command will not fix anything
> 
> believe it or not, when steam updates a game, it doesn't magically wipe all previous versions of the game from every computer on earth
> 
> in fact, even if you fail to prevent steam from updating your game, you can easily acquire the previous version using [DepotDownloader](https://github.com/SteamRE/DepotDownloader) or by simply asking for it from someone that still has the previous version of the game
> 
> also, textmode is a feature that is so non-trivial for cheaters to reimplement even if it gets removed
> 
> seriously, it's literally just running the game without graphics, do you really think that that's such a difficult thing for a cheater to do

Bots being forced to switch to graphical TF2 ensures that the numbers will dramatically drop, as the amount of resources it would take to achieve the 100+ numbers some hosts have would no longer be remotely possible.

At best, most players would only come across 1 or 2 bots a day, at worst, one host who owns a massive VPS chunks their money into it to maintain 50 bots.

Also you can't play on servers with a mismatched client version

**Comment by wgetJane** [comment] 2024-04-21 02:28
i can see that this is a futile discussion

**Comment by compromisable** [comment] 2024-04-21 02:29
> i can see that this is a futile discussion

Goodnight troll

**Comment by wgetJane** [comment] 2024-04-21 02:36
i have come up with the ideal solution:

valve should simply add a userinfo cvar on the client called `cl_cheating` which defaults to a value of 0

then, cheat developers can just change its value to 1 to identify the client as non-legit

when a client with a cl_cheating value of 1 joins a vac-secured server, they will be promptly vac-banned

**Comment by compromisable** [comment] 2024-04-21 02:40
> i have come up with the ideal solution:
> 
> valve should simply add a userinfo cvar on the client called `cl_cheating` which defaults to a value of 0
> 
> then, cheat developers can just change its value to 1 to identify the client as non-legit
> 
> when a client with a cl_cheating value of 1 joins a vac-secured server, they will be promptly vac-banned

I don't follow. But thank you for pitching in anyways. Anyone care to elaborate?

**Comment by ethanholt1** [comment] 2024-04-21 03:01
> believe it or not, when steam updates a game, it doesn't magically wipe all previous versions of the game from every computer on earth
> 
> in fact, even if you fail to prevent steam from updating your game, you can easily acquire the previous version using [DepotDownloader](https://github.com/SteamRE/DepotDownloader) or by simply asking for it from someone that still has the previous version of the game
> 

Yes, but as far as I can tell, outdated game versions aren’t compatible with the latest server version. At least that’s what I’ve been told.

> when a client with a cl_cheating value of 1 joins a vac-secured server, they will be promptly vac-banned
 
 I have come up with an even better solution. We could politely ask the cheaters to stop cheating whenever they join a server, and then they’ll stop! Foolproof.

**Comment by ethanholt1** [comment] 2024-04-21 03:02
> > i can see that this is a futile discussion
> 
> Goodnight troll

I’m beginning to think that the only reason you’re continually posting in this discussion, is not to provide constructive responses or engage in conversation, but to just be a generally unpleasant person. Please stop being so rude.

**Comment by compromisable** [comment] 2024-04-21 03:51
> > > i can see that this is a futile discussion
> > 
> > 
> > Goodnight troll
> 
> I’m beginning to think that the only reason you’re continually posting in this discussion, is not to provide constructive responses or engage in conversation, but to just be a generally unpleasant person. Please stop being so rude.

I will readjust me attitude. Thank you.

**Comment by erickoid** [comment] 2024-04-21 13:29
> > > i can see that this is a futile discussion
> > 
> > 
> > Goodnight troll
> 
> I’m beginning to think that the only reason you’re continually posting in this discussion, is not to provide constructive responses or engage in conversation, but to just be a generally unpleasant person. Please stop being so rude.

Yeah he's being rude meanwhile the other 3 people above are being disingenuous, I can't believe a player base would actually get mad over trying to solve a real big issue.
Going back to removing -textmode, can any of you please describe a way it could be overcome? It sounds trivial so I'd like to hear why since I'm convinced removing one launch option will cripple bots for a good while and lead to better quality games with no disruptions

**Comment by NULLYUKI** [comment] 2024-04-21 13:31
Isn't this issue a possible duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/3477 ?

**Comment by wgetJane** [comment] 2024-04-21 14:26
> will cripple bots for a good while

so you admit that it's temporary (fail!)

**Comment by kisak-valve** [comment] 2024-04-21 14:57
Hello everybody, from a high level perspective, this is a valid issue, but by the nature of any anti-cheat discussion, nothing truly productive can be discussed on a public issue tracker which is visible to those who intend to make games worse for everybody.

If someone has found a substantial internal detail that can help with the VAC, that needs to be communicated via a non-public medium like email.

@erickoid, your specific request is being tracked separately at #4475.

It's worth leaving a friendly reminder that I'm a moderator for Valve's issue trackers on Github, and not a Team Fortress 2 or anti-cheat developer myself. Let's keep this issue tracker friendly for everyone. In particular @compromisable, @erickoid, name calling based on a difference of opinion will no longer be tolerated and there will be consequences if either of you choose continue to do so.

For transparency, I had left this issue report open with the intent that there would be a single thread to discuss the topic, but now that the discussion has digressed, there's no real value left compared to #3477. Feel free to continue the discussion there, but please try to keep it civilized.

**Closed by kisak-valve** 2024-04-21 14:57 UTC
