### ISSUE TITLE
[HL2] Steampipe has stopped non-scripted actor NPC blinking

### ISSUE THREAD

**Issue by ihonnyboy** [ValveSoftware/Source-1-Games#1850] opened 2014-11-17 00:49 UTC
I'm referring to blinking of the eyes, not model blinking. I've asked friends and looked up previous footage of Half Life 2 before and after the steampipe update, and this is indeed the case. I tired looking through the code on this repository, but I can't make sense of it. I even fired up my xbox360 copy of the orange box to check that NPCs blinked on the orange box engine. Currently they blink when told to do so (view the flex sliders in a VCD file), but they won't blink "naturally." The opening sequence of Half Life 2 is a good example of this, the G-man doesn't blink at all, and the Citizens encountered afterward don't blink either.

**Comment by hitmen047** [comment] 2016-04-15 02:20
Looks like Valve broke flex controling in c_baseflex.

**Comment by yaomtc** [comment] 2016-10-02 23:37
Two years later, and NPCs still aren't blinking. I wonder if Valve even saw this.

**Comment by idchlife** [comment] 2016-10-08 08:19
Hey. Is there fix yet?

**Comment by Exile37** [comment] 2017-01-20 20:43
@idchlife nope, but we hope 👀

**Comment by stalcer** [comment] 2017-01-20 20:45
MAKE NPCS BLINK AGAIN!

**Comment by flymans** [comment] 2017-01-20 20:48
Fix it, please.

**Comment by dankerino** [comment] 2017-01-30 19:43
Blink hype! 😄

**Comment by giulliano-lonardoni** [comment] 2017-01-30 22:08
I hope that they fix this, it's annoying.

**Comment by hitmen047** [comment] 2017-01-30 22:27
Easy to fix: https://www.youtube.com/watch?v=NEABoX3eF_g

**Comment by yaomtc** [comment] 2017-01-30 22:55
Hey guys, please don't spam. The only reason to comment on here is if you have a question, or something helpful to add - like a video demonstrating how it should be (thanks hitmen047), or a comment saying that the bug is either fixed or still not fixed after an update, or a significant amount of time has passed. This isn't YouTube. Everybody following this gets notified of useless comments and it's pretty annoying.

Hey hitmen, is that your video? I'm wondering how they/you fixed it.

**Comment by Exile37** [comment] 2017-01-30 22:56
@yaomtc unsubscribe from tread and you didn't receive notifications.

**Comment by yaomtc** [comment] 2017-01-30 23:13
@Exile37 of course I want to receive notifications... How else will I know when it's fixed? The problem isn't in my having subscribed, the problem is with users adding noise when they can just add an emoji, which is the reason they added them! https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

They even added the ability to sort a repo's issues by number of specific reactions: https://github.com/isaacs/github/issues/527

I don't want to fill up this thread with more comments that aren't about the blinking, so that's all I've got to say.

**Comment by hitmen047** [comment] 2017-01-31 00:52
@yaomtc yes, I'm the author of this video. I described the problem above in this thread. The problem in "blink" flex controlling in c_baseflex.cpp on client side. Looks like Valve changed it for TF2.

**Comment by GamerDude27** [comment] 2017-03-28 15:39
@hitmen047 How exactly did you fix the problem?

**Comment by NicknineTheEagle** [comment] 2017-08-21 16:43
Didn't take too long to figure out the cause.
https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/client/c_baseflex.cpp#L1152
this shouldn't be here

**Comment by kisak-valve** [comment] 2019-09-26 22:11
Closing as fixed per "Fixed NPCs not blinking" in the [2019-09-26](https://store.steampowered.com/news/54632/) Half Life 2 series game update.

**Closed by kisak-valve** 2019-09-26 22:11 UTC
Labels: Half-Life 2

**Comment by Pikamander2** [comment] 2019-09-27 15:46
https://www.rockpapershotgun.com/2019/09/27/half-life-2s-downtrodden-npcs-have-been-unable-to-blink-for-five-years-until-now/

**Comment by hirowatch** [comment] 2019-09-28 07:41
Thanks
