### ISSUE TITLE
[TF2] Weapons does not render properly (black textures)

### ISSUE THREAD

**Issue by TheEpicNoobZilla** [ValveSoftware/Source-1-Games#6065] opened 2024-06-09 09:51 UTC
As in title the game renders weapons with only black textures. It's doing it only with your weapons. This most of the time fixes itself after few minutes and happens randomly when launching the game
Picture with visible problem
![obraz](https://github.com/ValveSoftware/Source-1-Games/assets/55759769/bab5d810-1bb0-4222-99d7-320cbaf8e5b2)
Minigun fixed itself while sandvich not
![obraz](https://github.com/ValveSoftware/Source-1-Games/assets/55759769/ba040c96-453a-4a11-9422-efe6bfebadfb)

**Comment by Tiagoquix** [comment] 2024-06-09 10:41
Duplicate of #5888.

**Comment by kisak-valve** [comment] 2024-06-09 12:46
Hello @TheEpicNoobZilla, as @Tiagoquix noted, this issue is already being tracked at #5888.

Closing as a duplicate.

**Closed as not planned by kisak-valve** 2024-06-09 12:46 UTC
