### ISSUE TITLE
[TF2] Minimized viewmodel, jump during animation when inspecting weapon after cloaking once

### ISSUE THREAD

**Issue by DdariQ** [ValveSoftware/Source-1-Games#4775] opened 2023-02-12 03:36 UTC
Minimized viewmodels, Spy.

Not only gun, but sappers and knives too:
https://user-images.githubusercontent.com/64756077/218291436-c39e53c0-39e2-4a3a-ab00-9340d77cf543.mp4

With all invis watches; gun, sapper, knife inspect animations jump after cloaking once.

Changing class inside spawn fixes it, but not kill or resupply touch. (Although changing loadout and then touching resupply fixes it too, sorry for not including this in the video.)

**Comment by Ashetf2** [comment] 2023-02-12 04:33
Duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/4273

**Comment by kisak-valve** [comment] 2023-02-12 13:22
Closing in favor of the older issue report.

**Closed** 2023-02-12 13:21 UTC
