### ISSUE TITLE
[L4D2] 5.1 audio setting doesn't save or appear to affect anything

### ISSUE THREAD

**Issue by Frogging101** [ValveSoftware/Source-1-Games#1793] opened 2014-08-05 17:24 UTC
When I go to the audio settings in Left 4 Dead 2 and select 5.1-channel audio, the setting doesn't appear to do anything. I open the console and run "soundinfo" and it still says it's 2-channel. pavumeter shows that the front and rear speakers are playing the same things. If I restart the game, the setting has reverted to Headphones.

According to other Valve replies here on GitHub, there is no support for surround sound on Linux and it "isn't something we're going to address" (https://github.com/ValveSoftware/Source-1-Games/issues/93#issuecomment-13734652). So maybe the setting is there but there's nothing implemented for it, which is a shame because surround sound really increases the quality of the atmosphere.

So, that's my bug report. But I also have a question: Why was surround sound support dropped from the Linux version of the Source engine? I don't really care to argue the point but I'd at least like to know the reason because prior answers have been unsatisfactory in that regard (there was no reason given).

System Information:
Sound device: Integrated VIA Audio on M4A78T-E
Graphics: nVidia GTX 480
OS: Linux Mint 17 64-bit Cinnamon

**Comment by steamlinux** [comment] 2015-05-06 15:15
I have 5.1 audio system and this works

**Comment by Cybolic** [comment] 2015-05-07 00:46
I just downloaded Half-Life 2: Episode One again and I still only have the option of selecting 2 speakers, despite my sound card being set to 5.1 surround and Pulseaudio, MPlayer, mpv and VLC using the channels just fine.

**Comment by kisak-valve** [comment] 2016-12-29 19:55
Closing as this appears to be working as intended in Left 4 Dead 2.

Note: Surround sound headsets that claim Dolby Headphones with their hardware are not surround sound hardware, there is an implementation of HRTF in the windows drivers.

@Cybolic Half-Life 2: Episode One does not support surround sound at this time. The feature request for this is at #1678.

**Closed by kisak-valve** 2016-12-29 19:55 UTC
