### ISSUE TITLE
new update broke Mac tf2 :(

### ISSUE THREAD

**Issue by whydoineedhuh** [ValveSoftware/Source-1-Games#5720] opened 2024-04-19 09:40 UTC
when I tried to start up tf2 it said It could find hl2_oxs I tried renaming the file to hl2_osx and made a copy of the original file then tried to run it then it said unknown error >:( very confuzed I did un-install then re-install then verified and still it gone wrong

**Comment by JoriKos** [comment] 2024-04-19 10:01
Seems like a semi-dupe of #5625

**Comment by kisak-valve** [comment] 2024-04-19 12:43
Hello @whydoineedhuh, as @JoriKos noted this issue is already being tracked at #5625.

Closing as a duplicate.

**Closed as not planned by kisak-valve** 2024-04-19 12:43 UTC
