### ISSUE TITLE
Team Fortress 2 freezes entire system after playing for a few minutes (can only hardware reboot) on modern AMD graphics

### ISSUE THREAD

**Issue by fredddii** [ValveSoftware/Source-1-Games#2013] opened 2016-11-26 19:48 UTC
This did not occur on my system when I used to have NVIDIA. I have a Sapphire Radeon R9 Fury with the stock AMDGPU drivers on the latest Linux Mint (flgrx is deprated and not available for modern hardware).

The entire system freezes. I can not switch to another session. It all just hangs, and only a hardware reboot can fix it.

No crash dumps are available due to this. I also experience this issue with modern AMD hardware only, which might or might not affect this:

Steam will only work preloading libstdc++.so.6 on AMD graphics hardware #4725
https://github.com/ValveSoftware/steam-for-linux/issues/4725

![screenshot from 2016-11-26 20-29-41](https://cloud.githubusercontent.com/assets/15217150/20642805/82b9dbd2-b419-11e6-8e2d-b2de0ccd6bd2.png)

**Comment by Tele42** [comment] 2016-11-26 20:20
Duplicate of #1991.

**Comment by ElectricTriangle** [comment] 2016-12-01 23:55
Welcome to Valve and their absolute refusal to talk to their customers. Just a friendly suggestion, return it for an nvidia card. It's what I plan to do.

**Comment by fredddii** [comment] 2016-12-02 00:23
This is the only Source game that I play on which it occurs. I have no issues with other titles. Perhaps if Team Fortress 2 will migrate to Source 2 this will get resolved.

**Comment by ElectricTriangle** [comment] 2016-12-13 17:20
https://github.com/ValveSoftware/Source-1-Games/issues/1943
The issue has been resolved in mesa git, scroll down to near the bottom.

**Comment by kisak-valve** [comment] 2016-12-20 13:21
Please update to a build of mesa containing https://cgit.freedesktop.org/mesa/mesa/commit/?id=6dc96de303290e8d1fc294da478c4f370be98dea and retest or wait until a point release that contains that commit. Closing as a duplicate of #1943.

**Closed by kisak-valve** 2016-12-20 13:21 UTC

**Comment by fredddii** [comment] 2016-12-29 05:10
This issue no longer occurs on the current Debian testing platform. I have closed the ticket.
