### ISSUE TITLE
[HL2DM] Player model stopping "func_rotating"

### ISSUE THREAD

**Issue by darrnoktjurna** [ValveSoftware/Source-1-Games#1532] opened 2013-11-05 10:31 UTC
If you enter in round cylinder (func_rotating) it would stop.
http://www.youtube.com/watch?v=mjlWJXEV87Q

And yes, I know that I can change settings of func_rotating, but if I make it - I'll stuck and die in it...

**Comment by kisak-valve** [comment] 2016-12-24 17:04
Closing as a duplicate of #517.

**Closed** 2016-12-24 17:05 UTC
