### ISSUE TITLE
[TF2] In Casual, sometimes the Competitive endscreen doors show up instead of the regular ones

### ISSUE THREAD

**Issue by JoriKos** [ValveSoftware/Source-1-Games#6165] opened 2024-07-19 20:44 UTC
As title says, the endscreen's doors sometimes show up as the doors used in Competitive instead of Comp, with a red/blue "C".

Apologies if this was already reported, I couldn't find anything.

**Comment by rabscootle** [comment] 2024-07-23 22:12
Bug is covered in #3516

It's caused by late-joining into Casual matches. The door skins are handled only at the start of the match, a remnant of how Casual worked at its launch.

Would be fixed by setting the respective door model skin when joining a Casual or Competitive match.

**Comment by kisak-valve** [comment] 2024-07-23 22:18
Thanks @rabscootle, closing in favor of the older issue report.

**Closed as not planned by kisak-valve** 2024-07-23 22:18 UTC
Labels: Team Fortress 2
