### ISSUE TITLE
[Half-Life 2 Episode Two] Prop cull glitches; disappear from certain angles

### ISSUE THREAD

**Issue by stevethepocket** [ValveSoftware/Source-1-Games#657] opened 2013-05-14 06:38 UTC
I've spotted a couple of props in the _Half-Life 2_ series that, for whatever reason, randomly turn invisible or near-invisible from certain angles.

Second is this tool cabinet in _Episode Two_, when Gordon and Alyx stop off at the rebel base to disable the autogun. From the left side only, it displays reverse fade distance where it fades out and then reappears when you approach it.

![2013-05-14_00001](https://f.cloud.github.com/assets/3085348/499888/2b9cd4b2-bc60-11e2-9a35-c01f51520ce8.jpg)
![2013-05-14_00002](https://f.cloud.github.com/assets/3085348/499889/2d9e8aa8-bc60-11e2-8bb2-af157e11c14c.jpg)

There may be others like this. I guess maybe the fade distances are invalid? Next time I boot into Windows, I'll check if either of these issues are there as well. For now, here's my system info:

```
Processor Information:
    Vendor:  GenuineIntel
    Speed: 2400 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-29-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release-i386_2013-04-16

Video Card:
    Driver:  ATI Technologies Inc. ATI Radeon HD 4800 Series    

    Driver Version:  3.3.11672 Compatibility Profile Context
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x944a
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.91" x 11.77"  (23.98" diag)
                                            53.1cm x 29.9cm  (60.9cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Realtek ALC1200

Memory:
    RAM:  3954 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  487728 Mb
    Largest Free Hard Disk Block:  385398 Mb
```

**Comment by kisak-valve** [comment] 2016-12-22 23:26
Closing as a duplicate of #609.

**Closed by kisak-valve** 2016-12-22 23:26 UTC
Labels: Half-Life 2: Episode Two
