### ISSUE TITLE
[TF2] VALVE ANTI-CHEAT

### ISSUE THREAD

**Issue by Skardium** [ValveSoftware/Source-1-Games#5823] opened 2024-04-20 13:11 UTC
Please can you update the Anti cheat Valve becuz too much cheater Megatronic and Omegatronic, Luna BOT cheating on the game.. reset all level ?

**Comment by Skardium** [comment] 2024-04-20 13:13
too many cheater on Capture the flag in 2Fort map.

**Comment by Skardium** [comment] 2024-04-20 13:16
Put Easy Anti Cheat and Valve Anti cheat cooperation its good

**Comment by JoriKos** [comment] 2024-04-20 13:27
Duplicate of #5686

This is also for Source 1 games, not for VAC

**Comment by kisak-valve** [comment] 2024-04-20 13:49
Closing as a duplicate of #5686.

**Closed by kisak-valve** 2024-04-20 13:49 UTC
