### ISSUE TITLE
func_door ignores Stop Sound and Start Close Sound in MP

### ISSUE THREAD

**Issue by NukemD** [ValveSoftware/Source-1-Games#4844] opened 2023-03-11 15:30 UTC
This issue is as old as the Source Engine itself is.

"Stop Sound" and "Start Close Sound" are ignored on func_door entities in multiplayer. It will only play "Start Sound" and "Stop Close Sound".

This means that the door will play a sound when it starts moving for opening, but won't play a sound when it reaches its fully opened state. It also won't play a sound from its fully opened state when it starts moving to its fully closed state again.

func_door_rotating doesn't have this problem. Here is an example of a func_door and func_door_rotating with the same sound settings. You'll notice that the func_door doesn't play sounds properly.

[doorbug.webm](https://user-images.githubusercontent.com/1351169/224493095-a355291c-47a4-4bf3-a05e-1b1eb0d12134.webm)

**Comment by kisak-valve** [comment] 2023-03-11 15:46
Hello @NukemD, this reads like a duplicate of #4374. Closing in favor of the older issue report.

**Closed by kisak-valve** 2023-03-11 15:47 UTC
