### ISSUE TITLE
Airblast hitbox

### ISSUE THREAD

**Issue by Stack-Sash** [ValveSoftware/Source-1-Games#5871] opened 2024-04-22 07:06 UTC
People prob gonna hate this post but fix the airblast hitbox, feels like the hitbox is way to small. Please fix it that it can be managable for pyro but dont make it a huge cube. Make it into a decent airblast hitbox. I suggest not to be like a 90 degree cone but it could be a 115 degree like in this issue shows the solution : https://github.com/ValveSoftware/Source-1-Games/issues/5522

**Comment by JoriKos** [comment] 2024-04-22 07:13
This just seems like a duplicate of the mentioned issue

**Comment by kisak-valve** [comment] 2024-04-22 12:53
Closing as a duplicate.

**Closed by kisak-valve** 2024-04-22 12:53 UTC
