### ISSUE TITLE
Question on when a bug will be fixed

### ISSUE THREAD

**Issue by TheBucketWasTaken** [ValveSoftware/Source-1-Games#5772] opened 2024-04-19 20:13 UTC
When will the bug not allowing steam deck players to play tf2 be fixed?

**Comment by kisak-valve** [comment] 2024-04-19 20:15
Hello @TheBucketWasTaken, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #5621.

**Closed by kisak-valve** 2024-04-19 20:15 UTC

**Comment by JoriKos** [comment] 2024-04-19 20:22
This is not a general forum, posts should only be made for bug reports or feature requests.

**Comment by TheBucketWasTaken** [comment] 2024-04-19 20:23
Alright sorry for the misunderstanding
