### ISSUE TITLE
[HL2] Bridge pillar texture issue

### ISSUE THREAD

**Issue by VladimirVSC** [ValveSoftware/Source-1-Games#3793] opened 2022-01-16 15:43 UTC
Camera moving makes bridge textures shaking erratically (the same for the opposite side) (Highway 17 Chapter)
![d2_coast_080000](https://user-images.githubusercontent.com/96921167/149666919-a6a4813b-4792-4ce4-99c0-036dbb9cdfd3.jpg)
.

**Comment by VladimirVSC** [comment] 2022-01-16 15:47
[save.zip](https://github.com/ValveSoftware/Source-1-Games/files/7877297/save.zip)

**Comment by Yetoo1** [comment] 2022-01-16 15:47
@VladimirVSC Duplicate of #834.

**Comment by kisak-valve** [comment] 2022-01-16 15:57
Closing as a duplicate.

**Closed by kisak-valve** 2022-01-16 15:57 UTC
