### ISSUE TITLE
[TF2/Linux] The fonts are too small

### ISSUE THREAD

**Issue by ViBE-HU** [ValveSoftware/Source-1-Games#1997] opened 2016-07-03 21:20 UTC
Please use the same font type/size (if no licensing issues) or very similar like in the Windows build because the Linux build's globally much different and unreadable sometimes.

**Comment by kisak-valve** [comment] 2016-12-30 20:22
Closing as a duplicate of #1883.

**Closed by kisak-valve** 2016-12-30 20:22 UTC
