### ISSUE TITLE
[HL2DM][SDKHammer2013] "cubemap" didnt work after compile

### ISSUE THREAD

**Issue by darrnoktjurna** [ValveSoftware/Source-1-Games#1320] opened 2013-09-18 10:16 UTC
After compile and "buildcubemaps" they are didnt works.
We tested with impulse 81 and cubemaps has no gleam. People who created maps in hl2dm has this problem.

**Comment by kisak-valve** [comment] 2016-12-26 18:39
Closing as a duplicate of #860.

**Closed by kisak-valve** 2016-12-26 18:39 UTC
Labels: Half-Life 2: Deathmatch, Reviewed
