### ISSUE TITLE
[Linux] (HL:S) - Immune to tentacle monster

### ISSUE THREAD

**Issue by maquis196** [ValveSoftware/Source-1-Games#1780] opened 2014-07-15 22:38 UTC
As summary suggests, I noticed I was taking no damage from the tentacle monster in the silo. Can't find any other issue with this.

Ubuntu 14.04
Optimus laptop

**Comment by kisak-valve** [comment] 2016-12-29 19:19
Closing as a duplicate of #1193.

**Closed by kisak-valve** 2016-12-29 19:19 UTC
Labels: Half-Life: Source, Linux
