### ISSUE TITLE
TF2 - Feature Request: Add dynamic footer for MvM Operations to accurately advertise Australium drops

### ISSUE THREAD

**Issue by rabscootle** [ValveSoftware/Source-1-Games#4129] opened 2022-08-03 16:07 UTC
Hi!

I was wondering if there was any chance that the MvM Tour select HUD could be updated to fit a footer to advertise Australium drops in all tours that support it (Advanced difficulty and up).

![image](https://user-images.githubusercontent.com/108029512/182656545-7d789785-d595-4866-a558-cade200189bf.png)

Currently, the only Operation that mentions it in the UI is 'Operation Two Cities', meaning that the other tours receive significantly less traffic as it's not commonly known that other tours (Gear Grinder, Mecha Engine, Steel Trap) also have this chance. This could use some variation of the code that's already used to display a warning for 'Expert' difficulty tours so that it only displays when a tour meets the difficulty threshold.

**Comment by AzureAzel** [comment] 2022-08-03 20:59
https://github.com/ValveSoftware/Source-1-Games/issues/3554#issue-890493262
Posted this awhile ago, but I also agree that it should be updated. Some people I'm friends with didn't even know about the fact that you could get them outside of two cities in the past, since the patch that changed this never ended up changing the descriptions for the tours.

**Comment by kisak-valve** [comment] 2022-08-03 22:22
Closing as a duplicate of #3554.

**Closed by kisak-valve** 2022-08-03 22:22 UTC
Labels: Feature Request, Team Fortress 2
