### ISSUE TITLE
Duck Journal quack sounds broken.

### ISSUE THREAD

**Issue by gdfsgdfg** [ValveSoftware/Source-1-Games#5729] opened 2024-04-19 11:28 UTC
![Untitled](https://github.com/ValveSoftware/Source-1-Games/assets/8344799/c2a1490d-d32a-428e-bd11-ac427ffcf705)

**Comment by JoriKos** [comment] 2024-04-19 12:10
Duplicate of #5672

**Closed** 2024-04-19 12:50 UTC
Labels: Team Fortress 2, Audio
