### ISSUE TITLE
Lighting Error 

### ISSUE THREAD

**Issue by FixTF2** [ValveSoftware/Source-1-Games#6121] opened 2024-07-02 00:57 UTC
![20240621001131_1](https://github.com/ValveSoftware/Source-1-Games/assets/172848927/ccd364d1-eef1-45c4-a353-8680f1132266)

![20240621001151_1](https://github.com/ValveSoftware/Source-1-Games/assets/172848927/02c4d87b-66fa-4fd3-b9fd-c361facee204)

Map, Bad water, first spawn, something about the lighting makes the cosmetic The Claws And Infect to go from normal to pure black

**Comment by Ashetf2** [comment] 2024-07-02 07:19
It's an issue with the claws. Duplicate of #4220

**Comment by kisak-valve** [comment] 2024-07-02 11:59
Closing in favor of the older issue report.

**Closed as not planned by kisak-valve** 2024-07-02 11:59 UTC
Labels: Team Fortress 2
