### ISSUE TITLE
[TF2] [Bug Report]: CELT Voice Codec Causing Problems

### ISSUE THREAD

**Issue by Contradicktory** [ValveSoftware/Source-1-Games#2026] opened 2016-12-22 02:34 UTC
I've noticed two key issues with the CELT voice codec so far:

1. Certain users sound very chipmunk-y, as if their voice's pitch isn't being managed properly by the codec. This bug was reported in communities prior to the codec coming out of beta, but it's still an issue. The cause of it is unknown.

2. Users are reporting sounded more muted or distant with the CELT codec than they did with the previous one, and are unable to heighten their options in-game to alleviate these issues. Perhaps an issue with in-game options?

Though I'm fairly sure these problems aren't tied to specific hardware, here's mine:

i5 4690, Quad-Core Processor
Nvidia GTX 760 on driver version 376.33
8GB DDR3 RAM
Windows 10 64-bit

**Comment by fearts** [comment] 2016-12-22 23:10
I have some demos for you to view where I tested combinations of each setting with a user who was effected. To change the settings I added the cvars to the server.cfg and restarted the server completely each time to make sure it was fresh boot. Here are the results:

Demos Link: https://drive.google.com/open?id=0BylofitQmCBVNW45UWY0VlNyNGM


speexwith1.dem

^Works fine with:

sv_voicecodec vaudio_speex
sv_use_steam_voice 1

-----------------------------

speexwith0.dem

^No/Low sound with:

sv_voicecodec vaudio_speex
sv_use_steam_voice 0

-----------------------------

celtand1.dem

^Chipmunk voice with:

sv_voicecodec vaudio_celt
sv_use_steam_voice 1

-----------------------------

celtand0.dem

^No/Low sound with:

sv_voicecodec vaudio_celt
sv_use_steam_voice 0


(This is using a Windows 2008 R2 server with a user who is using Windows 10)

**Comment by fearts** [comment] 2016-12-23 02:04
Did some testing and found a few things.

1. On servers with the new default settings MAC users all have chipmunk voices. I tested this over multiple servers with 5+ different MAC users. Just going on the server asking if anyone was using a MAC and then requesting they speak on the mic briefly.

2. The user who I was testing with last night (Windows 10 User) whose mic is very low, we ran some more tests. I found two things. The user was using a Corsair Gaming H1500 head set and I had them switch to a Iphone head set. The switch seemly improved the mic quality. Then I found something even more strange. If the user connected to the server with no headset plugged into their computer and then plugged in their headset after full connection the sound quality was perfect. However, to keep this perfect quality they need to unplug the headset on every connection including map changes.

**Comment by Contradicktory** [comment] 2016-12-23 17:52
@kisak-valve Can you take another look at this? It looks like this issue pertains more to MAC users and people who use certian headsets.

**Comment by shaggytwodope** [comment] 2016-12-24 09:22
On my linux client voice doesnt work at all, previously voice was perfect. This may be the same issue as reported here.

**Comment by doublah** [comment] 2016-12-25 02:14
Had the Chipmunky voices happen today on a community server and it seemed all users were effected (even though most running Windows, not Mac/Linux). My guess is it's a server issue with something conflicting with the codec, as I've not seen this on Casual/Competitive.

**Comment by Nephyrin** [comment] 2017-01-05 21:16
We're looking in to this, thanks for the detailed reports so far.

For users affected by this, please ensure that sv_use_steam_voice and sv_voicecodec are set prior to the first map load.  There is some new code related to switching sample rates when the voice codec changes that may be at fault.

**Comment by Nephyrin** [comment] 2017-01-05 21:20
@shaggytwodope This is likely a separate issue. TF2 uses openal-soft for microphone input, currently defaulting to the default device. You may need to adjust your default audio device, or, if using a custom sound setup, modify ~/.alsoftrc to ensure it is using the correct backend. If you have a proper default device and are using a standard audio setup, please open a new issue so we can investigate.

**Comment by shaggytwodope** [comment] 2017-01-07 13:07
@Nephyrin thank you, looking into it I found the settings I needed to set.  I greatly appreciate the help in getting back my ability to mic spam once again. 

For anyone coming across this, I only set these options in the `~/.alsoftrc` file. 
```
drivers = pulse
[pulse]
allow-moves=yes
```

**Comment by kepgnar** [comment] 2017-01-09 00:30
hello, I'm a Mac user (Mac Pro, 10.11.6, USB Blue Snowball microphone) and I've been having this issue, seemingly since around the smissmas update. My voice output in TF2 is extremely low, choppy, completely unintelligible. It used to work perfectly. I've tried many things in troubleshooting, with no positive results.

I'd be happy to test any configurations in order to get this resolved, as it's a huge bummer to not have voice in-game. I'm a Mac-certified technician and am well-versed in the OS and system files if that helps. Thanks.

**Comment by RandomChaos** [comment] 2017-01-10 05:07
I am also experiencing this problem (Mac Pro, 10.11.6, USB Logitech mic). The issue was introduced with the November 18th update that added the CELT codec, and affects any servers configured to use that codec. This problem affects gameplay, given that team members are no longer able to communicate with each other. Since it's server-side configured which codec is used, there is no client-side way to fall back to the old codec to work around this bug on servers configured to use CELT.

I am also able to test any fixes.

**Comment by kf6bbl** [comment] 2017-01-10 07:43
Another chipmunk vote.
iMac w/10.11.6

**Comment by timeimp** [comment] 2017-01-15 00:22
+1 to the Scourge of the Chipmunk Voice on macOS 10.12.3. Since Smissmas update, voice output has been horrible. rMBp (Early 2013)

**Comment by jrivard** [comment] 2017-01-19 04:00
Having same issue on linux (OpenSuse Leap 42.2) here.    Using voice test my voice sounds echo and distorted.  Started happening around the CELT codec update, before that had been just fine.  I've tried just about every pulse audio tip I can find and nothing makes it better.  Other apps work just fine with my mic, its just tf2 that sounds dreadful.

**Comment by ibuprofane** [comment] 2017-01-20 05:17
@Nephyrin I'm having the same chipmunk voice with my Bluetooth Mic on OSX. Per your earlier post I can confirm that setting sv_use_steam_voice and sv_voicecodec before first map load fixes the issue if I create my own server and test, however these values are reset once I join a Casual game - the mic goes chipmunky again.

**Comment by jfortier** [comment] 2017-01-23 22:19
Glad I'm not the only one having this issue. First time I ever got called a "squeaker". Gotta say, not being able to chat is real downer. :( Any kind of ETA on this fix?

- Hackintosh running OS X 10.11.2
- Focusrite Scarlett 6i6 sound card

**Comment by jeremyclarke** [comment] 2017-02-04 17:54
So all this time and still no recognition from a Valve employee that voice is totally broken for OSX. 

@kisak-valve Any ideas what you guys will try to do to fix this? Things above apply only to people who might have misconfiguration, not the 100% of OSX users who can't use voice chat. 

Very disappointing. Please tell us you are working on this!

**Comment by hahagoni** [comment] 2017-02-04 17:58
@jeremyclarke, Nephyrin is a dev

**Comment by jeremyclarke** [comment] 2017-02-04 18:01
Okay, so I guess you consider this acknowledgement:

>We're looking in to this, thanks for the detailed reports so far.

@Nephyrin Have you guys tried playing TF2 on OSX in a Casual server and confirmed that voice comes are totally broken? Are you still looking into it, or working on a solution now?

**Comment by TonyPHX** [comment] 2017-02-05 06:38
MacOS totally broken for in-game voice.

**Comment by vfjpl** [comment] 2017-02-05 18:32
Hi. I'm using linux. I also have problems with voice chat. This "Chipmunk Voice" is I think 16k hz sample being played at 48hz. I'm really sure about that :) I have heard that distortion before :) And also duration of voice seems to agree with my hypothesis. So it's most likely resampling issue. If someone is investigating this issue, please also try using pure alsa(dmix) in opposition to pulseaudio. I have played it earlier with pulseaudio uninstalled and I do not recall having this issue. But it was like 2-3 weeks ago. And maybe I was lucky.
Best regard
PS: I have switched to pulseaudio because of features like this: http://0pointer.de/blog/projects/pulse-glitch-free.html :)

**Comment by evinruding** [comment] 2017-02-10 17:43
To reiterate - in-game voice is completely broken on all recent versions of MacOS and it has been since the Smissmas update. How do we get the game developers to look at this issue?

**Comment by TonyPHX** [comment] 2017-02-10 17:45
I couldn't agree more.  This cripples the game for players and has likely resulted in higher costs for Steam/Valve as players attempt to resolve by redownloading the game, only to have same issue.

**Comment by justfortier** [comment] 2017-02-10 17:54
@evinruding I believe @Nephyrin is a game developer. Hopefully we'll hear back soon, the fact that this has been busted for almost 8 weeks now and barely any acknowledgment is discouraging. Especially considering Fearts can demo the issue easily, and can confirm his test on OS X.

I agree with @vfjpl that this definitely sounds like 16KHz being played at 48KHz issue. Audio played back is high pitched, shorter playback time than input, effectively speeding up playback 3x.

**Comment by kf6bbl** [comment] 2017-02-10 17:54
At the very least, can Valve reply with a comment such as, "It's in the queue, hoping to release in XX days" or something to that effect?

**Comment by jeremyclarke** [comment] 2017-02-10 19:56
I got a response via Valve support ticket on Feb 6 :

> We certainly understand this is a wider issue for TF2 players on OSX, and we have seen multiple reports of this issue.
> The forum mentioned above is the best method for gaining more visibility from the TF2 developers. I have also forwarded your comments to the appropriate department.

So as we expected, they aren't totally deaf to the many complaints about this, they just haven't figured out what to do about it yet and I guess don't want to say anything publicly until they do. 

Extremely disappointing that it's lasted this long, but at least they know about it so there's not much we can do but wait.

**Comment by Nephyrin** [comment] 2017-02-10 22:56
This is fixed in the next bugfix update for TF, tentatively scheduled for next week.

@vfjpl 11025hz being placed into a 22050hz buffer to be precise

**Comment by justfortier** [comment] 2017-02-10 23:03
@Nephyrin much appreciated!

**Comment by TonyPHX** [comment] 2017-02-10 23:04
Nephyrin, - LOVE!!

**Comment by RandomChaos** [comment] 2017-02-10 23:06
Thank you!

**Comment by kf6bbl** [comment] 2017-02-10 23:31
Sweet baby Jebus!

**Comment by TonyPHX** [comment] 2017-02-10 23:31
Sadly with this fix I will no longer again have reason to visit the Steam forums where kids will tell me to buy a PC.  : )

**Comment by evinruding** [comment] 2017-02-11 16:36
@Nephyrin Soon again on my mac I will be able to tell the kids on their PC's why having 5 snipers and no medics on the team doesn't help us win, you just made my Christmas card list! Thank you so much!

**Comment by kisak-valve** [comment] 2017-02-14 20:45
Per "Will now use the native Steam Voice sampling rate, instead of clamping to 11kHz" and "Fixed OS X voice communication sounding high-pitched when using the default CELT voice codec" in the 2017-02-14 update, is anyone still experiencing this issue? I'd like at least one report from each platform please.

**Comment by timeimp** [comment] 2017-02-14 20:57
@kisak-valve I can confirm this is no longer an issue on macOS Sierra.

👏  for the devs fixing this!

**Comment by RumbleFrog** [comment] 2017-02-14 22:13
@kisak-valve Verified on Windows, no longer a problem with sv_voicecodec steam

**Comment by RandomChaos** [comment] 2017-02-15 00:07
@kisak-valve confirmed it is working for me - MacOS Sierra also. Thanks!

**Comment by TonyPHX** [comment] 2017-02-15 00:11
@kisak-valve Tested on macOS Sierra 10.12.3.  All fixed and happy!  Nicely done.

**Comment by jeremyclarke** [comment] 2017-02-15 00:31
@kisak-valve Working on Yosemite. Thank you. Just had a string of replays where we all head a great, pleasant voice chat about strategy, helped a returning player re-orient himself to changes and had a wonderful time. The server even stayed together because of the update that lets us choose a different PL map!

Great update, but please keep OSX in mind in the future, this bug still took too long to fix.

**Comment by RumbleFrog** [comment] 2017-02-15 00:38
@jeremyclarke It's on all platforms in this case.

**Comment by fearts** [comment] 2017-02-15 23:21
I have tested this with multiple Windows and Mac users on my server. I have tested each of the three codec options resetting the server each time. On each codec option most users on both platforms had no issues with their mics.

I'm still however seeing a issue with a couple Windows (Windows 10) users having muffled voices on any setting except "steam". I spent hours last night with one of the users trying to trouble shoot this issue. I made sure their default device was set properly, I tried changing volume settings, I tried every bit rate, I tried removing volume boost, I tried reinstalling their drivers and nothing seems to help. This user isn't using any custom huds or content for their game it's a basic install.

I also searched Google a bit and it seems these issues have been around for a while. Here are some examples:

http://forums.steampowered.com/forums/showthread.php?t=832575
https://steamcommunity.com/discussions/forum/1/541907867771215982

**Comment by agrastiOs** [comment] 2017-02-16 10:08
Well, someone with Linux would still have to see if the problem is fixed for them

**Comment by justfortier** [comment] 2017-02-16 17:57
I seem to be having an issue where my audio is being defined by others as "quiet" and "choppy".

Here are things I've noted:
- Running OS X 10.11 El Capitan
- My external sound card's input source is 96KHz. 
- My mic gain is fine on my audio card. I can use it in other applications no problem.
- It sounds fine in Steam Application itself.
- I can't seem to set my transmit volume in game. I move the volume up, press apply, OK. Open the options dialog back up and it's back to 0. This may/may-not be related.
- I checked the file permissions for config.cfg (as well as all other config files) they are fine, all owner +rw and belonging to `whoami`:wheel. Those permissions seem correct to me. Note voice_scale variable was set to "0.75" in config file, despite it looking like 0 in the dialog.

Anything I can do to help debug? I don't mind getting my feet wet. I do DevOps automation work mostly now, but have a pretty strong development background.

**Comment by vfjpl** [comment] 2017-02-19 17:37
@Nephyrin Thank you for correcting my! I knew that steam chat was capturing sound at 16hkz so I incorrectly extrapolated from that to tf2 because I thought that is is using the same mechanism. :) And well... for 48Khz playback… I should have thought that tf2 output is probably at 44Khz, so I have no knowledge about real output rate. 
So sound was like 11Khz sound is treated like 22khz? and then is resampled to the frequency that match the game output? So there was no actual problem with resampling?

**Comment by kisak-valve** [comment] 2017-03-03 17:36
Thanks for the retesting, I'm going to go ahead and close this issue report.

@fearts and @justfortier, please open separate issue reports for those issues.

**Closed by kisak-valve** 2017-03-03 17:36 UTC
Labels: All Platforms, Need Retest, Team Fortress 2

**Comment by TonyPHX** [comment] 2017-04-23 08:40
Would anyone be incredible upset if I were to state that these issues are back?  : (

**Comment by kisak-valve** [comment] 2017-04-23 12:51
Hello @TonyPHX, please open a new issue report so we can collect fresh information.

**Comment by TonyPHX** [comment] 2017-04-23 19:03
@kisak-valve Thank you for reply. No need....  I am so incredibly stupid that sometimes I think should uninstall the operating system...  I had the wrong input source selected.  The code is fine.  It's me, not you.  : )

Sorry.
