### ISSUE TITLE
[TF2] New players can get stuck in Spectator mode If they skip the map intro video

### ISSUE THREAD

**Issue by gaelcoral** [ValveSoftware/Source-1-Games#6365] opened 2024-09-20 19:53 UTC
I've seen many posts from players getting stuck in Spectator mode for a while. While playing with a new account, I realized that skipping the map intro video causes you to get stuck in spectator mode. Due to the F2P chat restrictions, new players can't ask for help because they are muted 🫠

https://github.com/user-attachments/assets/96af180e-3dea-4eab-90b5-bedec1e6bfcb

_(F2P account tested through Geforce Now)_

**Comment by kisak-valve** [comment] 2024-09-20 20:21
Possible duplicate of #6290.

**Comment by gaelcoral** [comment] 2024-10-11 06:32
Now this happened to me in the new ZI map

**Comment by gaelcoral** [comment] 2024-10-11 08:05
using the command `closedwelcomemenu` fixes the issue

**Comment by NULLYUKI** [comment] 2024-10-18 23:37
According to patch [230932](https://www.teamfortress.com/post.php?id=230932)

>Fixed players not being able to select a class and spawn after watching an intro video 

Please retest this issue.

**Comment by KimmyTF2** [comment] 2024-10-20 10:52
It appears to be fixed

https://github.com/user-attachments/assets/a66d78a2-bbe7-4481-81bb-646e49073671

**Comment by kisak-valve** [comment] 2024-11-22 21:58
Closing per the last couple comments.

**Closed as completed by kisak-valve** 2024-11-22 21:58 UTC
Labels: Team Fortress 2
