### ISSUE TITLE
Username triggers VAC ban 

### ISSUE THREAD

**Issue by MrStonedOne** [ValveSoftware/Source-1-Games#2479] opened 2018-01-02 01:57 UTC
So when you have an username on your GNU/Linux machine containing "catbot", you get a VAC ban.

**Comment by kisak-valve** [comment] 2018-01-02 02:05
Hello @MrStonedOne, VAC issues are not handled on these issue trackers in any capacity. Closing as a duplicate of #2475.

**Closed by kisak-valve** 2018-01-02 02:05 UTC
