### ISSUE TITLE
[TF2] Scout's BLU pants use the wrong color

### ISSUE THREAD

**Issue by RedFire512** [ValveSoftware/Source-1-Games#4736] opened 2023-01-21 19:53 UTC
Scout's pants in all pre-release images show him as wearing blue pants on BLU team. 

![image](https://user-images.githubusercontent.com/60904124/213884718-9d0d0e58-3cad-42e9-be7f-baa0b14fe8fd.png)

However, since release, the texture has the proper belt loop color, but his pants are incorrect, still using the color of the red team texture.

![image](https://user-images.githubusercontent.com/60904124/213884594-9b46ea0b-beae-4a59-ba4c-05544c905cb8.png)

The PS3 version of the Orange Box doesn't have this problem, his pants are the proper color on BLU. This is most definitely an oversight that has been in the game for over 15 years. He is the only class to have this issue on the pants, as every other character has the proper pants for their team. This _should_ just be a simple case of turning on a layer in the Photoshop file.

**Comment by ljcool2006** [comment] 2023-01-21 19:59
Duplicate of #2289

**Comment by kisak-valve** [comment] 2023-01-21 20:00
Closing as a duplicate of #2289.

**Closed by kisak-valve** 2023-01-21 20:00 UTC
