### ISSUE TITLE
Ullapool caber recharge 30 second after use 

### ISSUE THREAD

**Issue by Narnilz** [ValveSoftware/Source-1-Games#4575] opened 2022-12-10 04:34 UTC

**Comment by jh34ghu43gu** [comment] 2022-12-10 05:54
Semi-duplicate of #2567 ?

**Comment by kisak-valve** [comment] 2022-12-10 13:33
Hello @Narnilz, there's not enough written here to understand your intent. I have to assume this is a duplicate of #2567.

Closing as invalid.

**Closed by kisak-valve** 2022-12-10 13:33 UTC
