### ISSUE TITLE
Queue Isn't working, just stops

### ISSUE THREAD

**Issue by motherofdragons96** [ValveSoftware/Source-1-Games#6195] opened 2024-07-25 02:29 UTC
Did everyone know why the queue Isn't working, the community servers are fine, but something must of happened. I really want to play Casual right now

**Comment by JoriKos** [comment] 2024-07-25 11:22
Seems like this was fixed already according to the in-game message

**Comment by JoriKos** [comment] 2024-07-25 13:21
May also be a duplicate of #2820, was the queue starting, then stopping entirely without you doing anything?

**Comment by ethanholt1** [comment] 2024-08-09 16:24
Retested on Windows X64. Seems to be fixed (queued for 10 different games, issue didn't happen.) I would wait for another person to retest, preferably on Linux before this can be safely closed.

**Comment by kisak-valve** [comment] 2024-09-28 14:49
Closing per the last several comments.

**Closed as completed by kisak-valve** 2024-09-28 14:49 UTC
