### ISSUE TITLE
[TF2] Black screen after being kicked

### ISSUE THREAD

**Issue by apchistuo** [ValveSoftware/Source-1-Games#5414] opened 2024-01-13 05:22 UTC
There's a chance that you'll get a black screen after being kicked from matchmaking.
**Reproduction steps**
Get kicked from a server using the in-game vote menu.
**System Information**
Windows 10 Pro 22H2
NVIDIA GeForce GTX 1050 Ti
Intel Core I7-7700k

**Comment by JoriKos** [comment] 2024-01-13 11:34
Duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/4714

That mentions it being Linux-specific, but it isn't.

**Comment by kisak-valve** [comment] 2024-01-13 13:36
Closing in favor of the older issue report.

**Closed by kisak-valve** 2024-01-13 13:36 UTC
