### ISSUE TITLE
[32-bit only] Games don't start from an XFS partition

### ISSUE THREAD

**Issue by MRebhan** [ValveSoftware/Source-1-Games#2223] opened 2017-04-10 11:42 UTC
(Same bug: https://github.com/ValveSoftware/halflife/issues/1787)
Only affects 32-bit source games, CS: GO works fine.
When trying to launch a Source game from an XFS partition, it segfaults before hitting the main menu and sometimes brings up a dialog box.
After copying it to an ext4 partition it starts fine.

How to reproduce (ex: HL2):

- Create a file large enough to hold HL2, for example with `dd if=/dev/zero of=hl2.img bs=1M count=8192`
- Format it with XFS: `mkfs.xfs hl2.img`
- Mount it and copy over the Half-Life 2 files: `mount hl2.img /mnt && cp -r ~/.steam/steamapps/common/Half-Life\ 2 /mnt`
- Try to run Half-Life: `cd /mnt/Half-Life\ 2 && ./hl2.sh`
- It should crash and open a dialogbox saying `COM_LoadFile: not enough space for media/StartupVids.txt` in the case of HL2. Varies based on the game.

System Information: 

- Arch Linux x64
- i5-6600
- 16GB RAM
- GTX 1070

```
SDL video target is 'x11'
SDL video target is 'x11'
Using breakpad crash handler
Setting breakpad minidump AppID = 220
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198084571756 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198084571756
Did not detect any valid joysticks.

(hl2_linux:9668): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(hl2_linux:9668): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
[0410/133948:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
tcmalloc: large alloc 4294230016 bytes == (nil) @ 
crash_20170410133945_1.dmp[9945]: Uploading dump (out-of-process)
/tmp/dumps/crash_20170410133945_1.dmp
./hl2.sh: line 67:  9668 Segmentation fault (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
crash_20170410133945_1.dmp[9945]: Finished uploading minidump (out-of-process): success = yes
crash_20170410133945_1.dmp[9945]: response: CrashID=bp-c531eba6-6623-489d-9479-678c02170410
crash_20170410133945_1.dmp[9945]: file ''/tmp/dumps/crash_20170410133945_1.dmp'', upload yes: ''CrashID=bp-c531eba6-6623-489d-9479-678c02170410''
```

**Comment by kisak-valve** [comment] 2017-04-10 12:54
Closing as a duplicate of #1685.

**Closed by kisak-valve** 2017-04-10 12:54 UTC
