### ISSUE TITLE
[TF2] The group chat window glitches and shrinks everytime you open and close it

### ISSUE THREAD

**Issue by StShAzzy** [ValveSoftware/Source-1-Games#5844] opened 2024-04-21 03:37 UTC
eventually, i'll get like this
![image](https://github.com/ValveSoftware/Source-1-Games/assets/90798128/4853ed0a-b405-4caa-8d1f-2de43c629b68)

**Comment by slender100** [comment] 2024-04-21 04:13
this sounds like issue #3774

**Comment by kisak-valve** [comment] 2024-04-21 13:27
Hello @StShAzzy, the game resolution is close enough to match the older issue report.

Closing as a duplicate of #3774.

**Closed by kisak-valve** 2024-04-21 13:27 UTC
