### ISSUE TITLE
[HLDMS] Models are doubled [Breaks doors,lifts,prop_physics]

### ISSUE THREAD

**Issue by 1157** [ValveSoftware/Source-1-Games#1517] opened 2013-10-27 23:38 UTC
![d_rats](https://f.cloud.github.com/assets/5712715/1416658/decf5720-3f60-11e3-839f-187fd899da83.png)

**Comment by kisak-valve** [comment] 2016-12-26 21:41
Closing as a duplicate of #1368.

**Closed by kisak-valve** 2016-12-26 21:41 UTC
