### ISSUE TITLE
[LINUX EXCLUSIVE] Lightwarp bug that causes some shadowing to be way too harsh.

### ISSUE THREAD

**Issue by Munoida** [ValveSoftware/Source-1-Games#3731] opened 2021-11-28 04:26 UTC
As the title says. 
How it looks like on Windows 10
![20211127221958_1](https://user-images.githubusercontent.com/84733553/143729485-a572f2e2-7e9c-4e06-8ce5-e44576920a97.jpg)
How it looks like on Pop!_OS
![20211127231507_1](https://user-images.githubusercontent.com/84733553/143729504-7e42ff56-0139-46dd-9d87-2bd2ef42a7a0.jpg)
[Left is how other lightwarps look like, like the TF2 one, compared to the custom dewobedil cel-shaded lightwarp.]
Any way to fix this or is this just a bug with the engine or driver?

Link to all models:
https://steamcommunity.com/sharedfiles/filedetails/?id=1518697901&searchtext=miu+iruma
https://steamcommunity.com/sharedfiles/filedetails/?id=2633114003&searchtext=makoto+naegi
https://steamcommunity.com/sharedfiles/filedetails/?id=1475514745&searchtext=maki

Pop!_OS system specs
OS: Pop!_OS 21.04
KERNEL: 5.13.0-7620-generic
CPU: Intel Core i7-3770S @ 3.10GHz
GPU: NVIDIA NVIDIA GeForce GTX 1050 Ti
GPU DRIVER: NVIDIA 470.82.00
RAM: 16 GB

**Comment by Munoida** [comment] 2021-11-28 04:30
If needed I will provide screenshots from other Source games showing this issue.

**Comment by Yetoo1** [comment] 2021-11-28 04:48
@Munoida What games were the screenshots in? Please demonstrate in Valve titles.

**Comment by kisak-valve** [comment] 2021-11-28 13:44
Hello @Munoida, this looks like an issue for the Garry's Mod devs to evaluate. If you can reproduce this issue with a Valve published game, let me know and we can ponder it further here.

Closing as out of scope for this issue tracker.

**Closed by kisak-valve** 2021-11-28 13:44 UTC

**Comment by Munoida** [comment] 2021-11-28 23:55
> Hello @Munoida, this looks like an issue for the Garry's Mod devs to evaluate. If you can reproduce this issue with a Valve published game, let me know and we can ponder it further here.
> 
> Closing as out of scope for this issue tracker.

I was infact not able to reproduce the same bug in different VALVe games, after using the same models in Left 4 Dead 2 and the same lightwarp in Team Fortress 2 I was not able to reproduce the harsh shadowing bug. Although, it made the Team Fortress 2 characters look really nice
The lightwarp applied on Team Fortress 2 mercenaries.
![20211128184410_1](https://user-images.githubusercontent.com/84733553/143791406-c97b416a-2708-418e-a83b-9f80c88647e2.jpg)
The same models in Left 4 Dead 2 by the same person on Hard Rain
![20211128185131_1](https://user-images.githubusercontent.com/84733553/143791427-6f57adc4-1aea-42a1-be6c-b76f722ea2e7.jpg)

It looks like my initial assumption was wrong that it affected every Source Engine game. I would look more into it and see if it was specifically Source SDK Base 2013 but the likeliness of that is nill. Thank you for your help.
