### ISSUE TITLE
TF2 | vulkan freezing while loading on debian

### ISSUE THREAD

**Issue by melodyjkah** [ValveSoftware/Source-1-Games#6210] opened 2024-07-27 02:59 UTC
TF2 vulkan freezing while loading to game (after valve intro) on **debian (xfce)**
OS: Debian GNU/Linux 12 (bookworm) x86_64 
DE: Xfce 4.18 
CPU: Intel i7-9700 (8) @ 4.700GHz 
GPU: NVIDIA GeForce RTX 2060

**Comment by melodyjkah** [comment] 2024-07-27 03:00
and i got vulkan drivers

**Comment by NULLYUKI** [comment] 2024-07-27 03:01
Check if your Steam client is up to date.

**Comment by melodyjkah** [comment] 2024-07-27 03:03
it is

**Comment by NULLYUKI** [comment] 2024-07-27 03:12
Copy the contents of Steam Runtime Diagnostics from Steam (Steam -> Help -> Steam Runtime Diagnostics) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by melodyjkah** [comment] 2024-07-27 03:15
https://gist.github.com/melodyjkah/628f2978d50f84e41313a373205c7b32

**Comment by kisak-valve** [comment] 2024-07-27 12:32
Hello @melodyjkah, can you test if this is the same issue as #5939 by setting the game's launch options to `-windowed` and checking how the game behaves?

**Comment by melodyjkah** [comment] 2024-07-27 18:10
okay

**Comment by melodyjkah** [comment] 2024-07-27 18:13
yeah with -windowed everything works, i installed steam by using .deb from steam website if its important info.

**Comment by kisak-valve** [comment] 2024-07-27 18:58
Thanks for checking, that makes this the same issue as the older issue report.

Closing as a duplicate of #5939.

**Closed by kisak-valve** 2024-07-27 18:58 UTC
Labels: Team Fortress 2, Linux
