### ISSUE TITLE
[TF2] [Feature Request] Let mappers use custom models in Robot Destruction

### ISSUE THREAD

**Issue by mrtino** [ValveSoftware/Source-1-Games#4086] opened 2022-07-20 10:59 UTC
In the Robot Destruction gamemode, robot models are managed by the ``tf_robot_destruction_robot_spawn`` entity. In Hammer, it lets you choose between several types of robots, but doesn't come with the option to choose your own models if you want to. One solution to this would be to replicate the way ``npc_breen`` or ``npc_alyx`` in Half-Life 2 lets you choose a world model in the object properties.

This QoL feature could make the gamemode more relevant in certain contexts (e.g an Halloween-themed map).

Here is how this could look like in the editor (results obtained by tweaking the fgd): 
![image](https://user-images.githubusercontent.com/7429496/179960965-52e782df-26ec-4849-8307-ecb4d5a9ae18.png)

**Comment by Ashetf2** [comment] 2022-07-20 13:34
Dupe of #3339?

**Comment by kisak-valve** [comment] 2022-07-20 13:39
Indeed, closing as a duplicate.

**Closed by kisak-valve** 2022-07-20 13:39 UTC
Labels: Feature Request, Team Fortress 2, SDK
