### ISSUE TITLE
[TF2] Visual bug (WEAPONS WORLD MODEL DISSAPEARING)(not solved)

### ISSUE THREAD

**Issue by WizardoBD** [ValveSoftware/Source-1-Games#6234] opened 2024-08-02 02:24 UTC
![64fa1d8499b97](https://github.com/user-attachments/assets/471797e2-cdb9-4983-bfb8-f90d361bcad0)
It has nothing to do with the texture of the weapons, it's the model, even the shadow of the weapon goes away because the model itself goes away.
For the medigun this happens when: 
-A medic heals a patient (it happens randomly but it happens)
-A medic heals a patient and the patient respawns away from the medic while changing loadouts
For all of the other weapons (including the medigun) this happens after the player gets out of the loser or surrender animation:
-After the round ends if the player in the loser animation doen't get killed he will respawn without the weapons models.
-Gets scared by a ghost
-Gets stunned by snipers huntsman taunt kill but the sniper gets killed before finishing the taunt
-Gets stunned by the sandman ball (in custom servers with the old weapons mechanics)

**Comment by Ashetf2** [comment] 2024-08-02 05:23
Btw, back in Jungle inferno this bug was intended to be fixed but it wasn't

**Comment by WizardoBD** [comment] 2024-08-02 05:32
I wonder what coused it...
I've played the TF2 classic sourcemod to see if that bug is there but no, not even when the ghost scare you in the halloween map.

**Comment by JoriKos** [comment] 2024-08-02 12:04
> I've played the TF2 classic sourcemod to see if that bug is there but no

Probably because it removed about 90% of the weapons that are affected by this bug :^)

The mod uses way older code, so the bug must have been created from a change after the code used in that mod.

**Comment by kisak-valve** [comment] 2024-08-02 12:54
Hello @WizardoBD, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #5656.

**Closed as not planned by kisak-valve** 2024-08-02 12:54 UTC

**Comment by WizardoBD** [comment] 2024-08-02 15:36
I will update the other one then.

**Comment by WizardoBD** [comment] 2024-08-02 15:49
> Hello @WizardoBD, please do not intentionally open duplicate issue reports.
> 
> Closing as a duplicate of #5656.

It was more like an updated version of the other one. It wasn't the intention to be a duplicate of the other one.
I don't know how to use or move arround this site yet.

**Comment by WizardoBD** [comment] 2024-08-02 15:52
> > I've played the TF2 classic sourcemod to see if that bug is there but no
> 
> Probably because it removed about 90% of the weapons that are affected by this bug :^)
> 
> The mod uses way older code, so the bug must have been created from a change after the code used in that mod.

I've seen this bug since the Gun Mettle update.

**Comment by iraizo** [comment] 2024-08-06 02:24
> It was more like an updated version of the other one. It wasn't the intention to be a duplicate of the other one. I don't know how to use or move arround this site yet.

You can edit the original post using the 3 dots on the right of the comment or just add another comment
