### ISSUE TITLE
[TF2][Spy]Disguise bug 

### ISSUE THREAD

**Issue by Wasmanr2** [ValveSoftware/Source-1-Games#2121] opened 2017-02-10 06:18 UTC
If the spy disguises as the following classes ;Scout,Pyro,Demoman; some parts of the actuall body are mostly missing/invisible.

This occurs rare and randomly.
 
On the Scout disguise its always the legs that are missing/invisible.

On the Demoman disguise its same as above "the legs" are invisible.

On the Pyro disguise its "the head" that is mostly invisible/missing.

This bug is not related to the knifes/spy watches from what I've seen.

(It seems that some parts of the model are missing or are not loading idk.)

Thats all.
Thanks.

**Comment by kisak-valve** [comment] 2017-02-10 13:33
Hello @Wasmanr2, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

Additionally, please verify the game files and if you can easily grab a few screenshots or a demo recording that reliably reproduces this issue, please include them as well.

**Comment by Wasmanr2** [comment] 2017-02-10 14:15
Okay.
Also verifying the game files didnt fixed this. 
Since its there like ages.

I will provide the informations/screenshots soon.

**Comment by Wasmanr2** [comment] 2017-02-18 13:56
<script src="https://gist.github.com/anonymous/b255dec74dedd2bc91c6ee8fb880ec04.js"></script>


I need to correct the description. This issue is rare.
I will still try to recreate the bug.

**Comment by kisak-valve** [comment] 2017-03-02 23:35
Turns out this is not driver related and is already being tracked at #275. Closing as a duplicate.

**Closed by kisak-valve** 2017-03-02 23:35 UTC
Labels: Team Fortress 2
