### ISSUE TITLE
[TF2][MVM] Bots aren't working after the newest updated

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [ValveSoftware/Source-1-Games#4555] opened 2022-12-03 17:14 UTC
Title, currently most of the MVM missions are broken after the December 1 patch, this issue is very bad since currently its making MVM maps unplayable currently

**Comment by kisak-valve** [comment] 2022-12-03 17:19
Hello @FriskTheFallenHuman, this reads like a duplicate of #4552. Closing in favor of the older issue report.

**Closed by kisak-valve** 2022-12-03 17:19 UTC
