### ISSUE TITLE
TF2 - Spy Disguise weapon broken for Shotgun

### ISSUE THREAD

**Issue by powerlord** [ValveSoftware/Source-1-Games#276] opened 2013-04-08 18:42 UTC
When you disguise as an Engineer, if they're using the stock Shotgun, the Spy will appear to be holding the Spy's primary weapon instead of the Shotgun.

For Heavy, Solder, and Pyro disguises, if a Spy attempts to switch to the shotgun disguise weapon, he will instead go into the disguise's reference animation pose.

I'm not sure if this applies to the Strange Shotgun as well as the stock.  The other Engineer primaries and Pyro/Heavy/Soldier secondaries are not affected.

**Comment by Exaeta** [comment] 2017-12-03 04:51
@kisak-valve Still broken! 4 years, please fix! It's really annoying when you're a spy and get slaughtered because of this bug. ;)

http://steamcommunity.com/sharedfiles/filedetails/?id=1219744552

Some more details: This only happens with the fallback shotgun, i.e. when there are no real engineers or whatever class on the other team.

**Comment by nosoop** [comment] 2020-10-30 14:39
I dug into this today.  Here's what's happening:

1. The spy changes disguise weapon during `CTFPlayerShared::DetermineDisguiseWeapon`.
2. The game checks if the target has a weapon for that slot, then falls back to the default weapons.  We're interested in the failure case for the shotgun, so we'll go with the `tf_weapon_shotgun_pyro` fallback.
3. The game tries to give the player the given weapon via `CTFPlayer::GiveNamedItem`.
4. The game doesn't have a script item (econ item view) to work with, so it generates a random item in `CItemGeneration::GenerateRandomItem` by looking up the class name as an item name in the schema and finds item definition index 12, which uses the `weapon_shotgun` prefab, which specifies `tf_weapon_shotgun` as the item class.
5. The game attempts to create an entity with that classname at `CItemGeneration::SpawnItem` , which fails, since it isn't translated to the class-specific variant.

I suspect an escape hatch by adding a `const char*` param to force the class `CTFPlayer::GiveNamedItem` would be the easiest way to go.  Setting the `item_class` key for item definitions 9-12 to their class-specific classnames also works on the server side, but I'm not what side effects doing that would have on the client.

**Comment by agrastiOs** [comment] 2022-06-23 20:33
@kisak-valve I also tested, it's fixed.

**Comment by nosoop** [comment] 2022-07-14 05:54
[Also confirmed fixed by shounic.](https://youtu.be/n8VJ-5UekWk?t=53)

@kisak-valve I believe the original issue poster is no longer involved in TF2-related activities; since multiple other parties have confirmed the fix, would it be okay to get this closed on their behalf?

**Comment by thejaviertc** [comment] 2022-07-23 10:46
> [Also confirmed fixed by shounic.](https://youtu.be/n8VJ-5UekWk?t=53)
> 
> @kisak-valve I believe the original issue poster is no longer involved in TF2-related activities; since multiple other parties have confirmed the fix, would it be okay to get this closed on their behalf?

Also in [a recent video of shounic](https://youtube.com/clip/UgkxVWmOOSmZAatCOtNgNoDzjw8Uy3Vc14FT) shows that is fixed with more detail.

**Comment by agrastiOs** [comment] 2022-07-23 21:37
@powerlord Has been fixed.

**Comment by kisak-valve** [comment] 2022-08-26 19:54
Thanks for retesting, closing per the last several comments.

**Closed by kisak-valve** 2022-08-26 19:54 UTC
Labels: Team Fortress 2, Reviewed, All Platforms, Need Retest
