### ISSUE TITLE
BUG: 6 Years of Rampant Bot Hosting Hackers

### ISSUE THREAD

**Issue by compromisable** [ValveSoftware/Source-1-Games#5796] opened 2024-04-20 01:10 UTC
![image](https://github.com/ValveSoftware/Source-1-Games/assets/147524755/e384e736-e375-4046-a054-bcf7e942d856)

What's the plan, guys?  
After 6 years, I think we should make a single attempt here. Let's turn this into a thinktank!

**Comment by erickoid** [comment] 2024-04-20 01:12
Im Sad.........................

**Comment by kisak-valve** [comment] 2024-04-20 01:16
Hello @compromisable, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #5686.

**Closed by kisak-valve** 2024-04-20 01:16 UTC
