### ISSUE TITLE
csgo mouse input

### ISSUE THREAD

**Issue by Steven20102** [ValveSoftware/Source-1-Games#3864] opened 2022-03-05 21:14 UTC
Hello,

is it possible to make the mouse input the same as in other source games? I also play css and codename cure and use in all 3 games the same settings and m_rawinput 1. But in csgo the sensitivity behaviour is different, its like having m_filter on.

Also adding -useforcedmparms in launch options and m_mousespeed 0 in csgo changes the sensitivity even it should not cause of m_rawinput 1.

Now i wonder if csgo use by default noforcemparms.

Thanks for help

**Comment by djdallmann** [comment] 2022-03-05 21:50
Not sure if you're in this thread already, I posted some analysis there of MouseThreshold1, MouseThreshold2 and MouseSpeed behaviors in relation to useforcedmparms.

https://forums.blurbusters.com/viewtopic.php?p=78837#p78837

**Comment by kisak-valve** [comment] 2022-03-05 21:58
Hello @Steven20102, please do not intentionally open duplicate issue reports. Closing as a duplicate of https://github.com/ValveSoftware/csgo-osx-linux/issues/2962.

**Closed by kisak-valve** 2022-03-05 21:58 UTC
