### ISSUE TITLE
[Left 4 Dead 2][Linux]Segfault on attempt to connect to certain servers

### ISSUE THREAD

**Issue by shatsky** [ValveSoftware/Source-1-Games#2726] opened 2019-01-06 21:36 UTC
Currently happens with these ones:
```
46.174.52.14:27216
185.248.102.39:27020
```
A friend of mine running Windows plays on these without issues. I've tried to connect a dozen of other randomly chosen servers and didn't run into segfault. I'm running NixOS which creates chroot from Ubuntu packages for running Steam, there's also confirmation from another user who runs Mint. I'm no GDB expert but I've managed to convert minidump to core file and see that main thread's (PID of which was referenced in the dmesg message) backtrace is deep in game executable/engine.so, probably a game bug.
[assert_20190106211337_1.zip](https://github.com/ValveSoftware/Source-1-Games/files/2730873/assert_20190106211337_1.zip)

**Comment by kisak-valve** [comment] 2019-01-06 21:48
For reference, the attached minidump is a null pointer SIGSEGV in engine.so.

**Comment by kisak-valve** [comment] 2019-01-06 21:51
Possible duplicate of #2261.

**Comment by shatsky** [comment] 2019-01-06 22:30
> Possible duplicate of #2261.

Indeed, no segfault with "Custom Server Content" set to "None".

**Comment by kisak-valve** [comment] 2019-01-06 22:33
Thanks for checking, closing in favor of the existing issue report.

**Closed by kisak-valve** 2019-01-06 22:33 UTC
Labels: Left 4 Dead 2, Linux
