### ISSUE TITLE
[Linux] [TF2] Really low fps in MvM 

### ISSUE THREAD

**Issue by Luupuc** [ValveSoftware/Source-1-Games#1806] opened 2014-08-19 19:38 UTC
Basically, the framerate is unplayably low in MvM game mode. With the same graphics settings, I get a good framerate on other game modes.

I'm running the game on latest Ubuntu with Nvidia GTX 460 graphics card with Nvidia proprietary drivers version 331.38.

EDIT: As I wrote below, it seems that disabling HDR solved the problem for me.

**Comment by kisak-valve** [comment] 2016-12-29 15:14
Possible duplicate of #23.

**Comment by kisak-valve** [comment] 2024-06-08 00:57
Closing as outdated.

**Closed by kisak-valve** 2024-06-08 00:57 UTC
Labels: Duplicate, Team Fortress 2, Linux, Need Retest
