### ISSUE TITLE
[HLDMS] Brush entities are spawning additional, non-functional versions of themselves

### ISSUE THREAD

**Issue by Candidate3014** [ValveSoftware/Source-1-Games#1879] opened 2015-03-25 11:23 UTC
A func_physbox for example would leave a duplicate static brush (as if it weren't tied to an entity). This is detrimental to those who don't want to build their maps simply out of brushes.

**Comment by 1157** [comment] 2015-03-25 16:07
Yes, map level design becomes "basic" as many things are or act like "func_physbox"  (reported here #1483)
almost a year and half ago.

**Comment by Candidate3014** [comment] 2015-03-25 16:37
Oh right, I didn't see that. But still, the fact that this game hasn't been updated within that year and a half ago is terrible on the devs' part.

**Comment by kisak-valve** [comment] 2016-12-27 19:26
Closing as a duplicate of #1483.

**Closed by kisak-valve** 2016-12-27 19:26 UTC
