### ISSUE TITLE
After latest steam update, TF2 hangs while overlay is open on Linux

### ISSUE THREAD

**Issue by Exaeta** [ValveSoftware/Source-1-Games#2595] opened 2018-05-06 00:40 UTC
Like, it hangs a LOT.

Please fix this, it's quite annoying.

**Comment by kisak-valve** [comment] 2018-05-06 00:59
Most likely a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/4933.

There's a potential workaround by sending SIGSTOP and SIGCONT to the game after it freezes.

**Comment by Exaeta** [comment] 2018-05-17 18:18
@kisak-valve that seems to "fix" it, albeit temporarily.

**Comment by kisak-valve** [comment] 2018-05-17 20:15
Per https://github.com/ValveSoftware/steam-for-linux/issues/4933#issuecomment-389368082, please opt into Steam's beta client and retest this issue.

**Comment by kisakvalve** [comment] 2018-05-29 23:06
Good day, I've received word from the VAC team that this is intentional and not open for discussion on Github.

In general VAC issues are not handled on Github in any capacity and further issue reports on this may result in being banned from the Valve Software issue trackers.

**Comment by kisak-valve** [comment] 2018-07-03 00:31
Closing as fixed.

**Closed by kisak-valve** 2018-07-03 00:31 UTC
Labels: Linux, Need Retest, Steam client
