### ISSUE TITLE
[TF2] Casual mapvote broken after scream fortress

### ISSUE THREAD

**Issue by SirBlockles** [ValveSoftware/Source-1-Games#4365] opened 2022-10-05 20:43 UTC
![image](https://user-images.githubusercontent.com/3620019/194159443-82927453-efa0-4589-a02f-6862e3ff0e52.png)

after my last casual game from the scream fortress update, the mapvote came up with "map not found" entries. all players in the lobby mentioned seeing this, and once the first map was voted for, the server immediately disconnected all of us and told us the match was over.

this happened on cp_spookeyridge.

**Comment by MikhailaTF** [comment] 2022-10-22 16:38
confirmed to be fixed since treacherousfiend's last comment, ticket can be closed

**Comment by kisak-valve** [comment] 2022-11-25 21:15
Closing per the last couple comments.

**Closed by kisak-valve** 2022-11-25 21:15 UTC
Labels: Team Fortress 2, Need Retest
