### ISSUE TITLE
[TF2] Cloak Proxy VMT parameters can be easily removed from VMTs.

### ISSUE THREAD

**Issue by Wosheereal** [ValveSoftware/Source-1-Games#5171] opened 2023-09-01 09:47 UTC
Cloak proxy VMT parameters in any VMTs that have them can be easily changed or removed, leading to bad actors being able to see cloaked spies. 

This can be done with any sv_pure setting. A way to fix the issue is to make the cloak proxy VMT parameters hardcoded and unable to be modified.

**Comment by TF2CutContent** [comment] 2023-09-01 09:52
Duplicate of #5170.

**Comment by Wosheereal** [comment] 2023-09-01 09:54
It is not a duplicate of #5170

**Comment by TF2CutContent** [comment] 2023-09-01 09:56
> It is not a duplicate of #5170

It is a duplicate and you are stating directly in the first sentence to "ignore the issue under this one" which is issue #5170, the issue you are duplicating.

**Comment by Wosheereal** [comment] 2023-09-01 09:56
> > It is not a duplicate of #5170
> 
> It is a duplicate and you are stating directly in the first sentence to "ignore the issue under this one" which is issue #5170, the issue you are duplicating.

I don't see it, you must be seeing things.

**Comment by TF2CutContent** [comment] 2023-09-01 09:57
> > > It is not a duplicate of #5170
> > 
> > 
> > It is a duplicate and you are stating directly in the first sentence to "ignore the issue under this one" which is issue #5170, the issue you are duplicating.
> 
> I don't see it, you must be seeing things.

Edit history is a thing on Github.
![Screenshot_20230901_055647_Firefox](https://github.com/ValveSoftware/Source-1-Games/assets/5123258/74136b61-ce9d-4a19-ac05-4dec6dc371bc)

**Comment by Wosheereal** [comment] 2023-09-01 09:57
like you said earlier... And?

**Comment by TF2CutContent** [comment] 2023-09-01 10:00
Well I'll just let kisak handle this duplicate when they see it then.

**Comment by Wosheereal** [comment] 2023-09-01 10:11
You are not very slick about changing up your reactions to my replies to be less negative, not to mention making a big stink earlier about comparing my valid concerns to the whole quickswitch debacle.

**Comment by TF2CutContent** [comment] 2023-09-01 10:40
VaLiD cOnCeRnS

**Comment by kisak-valve** [comment] 2023-09-01 12:56
For transparency, I'm not seeing how this is a distinctly different issue from #5170, but I'll give you the benefit of the doubt.

**Comment by TF2CutContent** [comment] 2023-09-01 16:05
On

> For transparency, I'm not seeing how this is a distinctly different issue from #5170, but I'll give you the benefit of the doubt.

It's the same thing, just reworded to not mention the sv_pure bypass

**Comment by kisak-valve** [comment] 2023-09-01 16:12
With the added details refining the scope of the issue being discussed on #5170, I'm inclined to agree.

Closing as a duplicate of #5170.

**Closed by kisak-valve** 2023-09-01 16:12 UTC
Labels: Team Fortress 2
