### ISSUE TITLE
[TF2] Visual Casual Badge bug.

### ISSUE THREAD

**Issue by matty4kek** [ValveSoftware/Source-1-Games#2584] opened 2018-04-25 15:58 UTC
Tier 2-9 badges only show their "colors" in the main menu.

On the scoreboard, the badge looks like a regular Tier 1 badge. Please fix this, so we can actually identify what "tier" other players are.

**Comment by Exaeta** [comment] 2018-05-23 18:38
This bug still isn't fixed.

**Comment by CriticalFlaw** [comment] 2018-07-18 18:54
This is the same as https://github.com/ValveSoftware/Source-1-Games/issues/2546

**Comment by kisak-valve** [comment] 2018-07-18 19:49
Thanks @CriticalFlaw, closing as a duplicate of #2546.

**Closed by kisak-valve** 2018-07-18 19:49 UTC
Labels: Team Fortress 2, User Interface
