### ISSUE TITLE
[L4D2] [Linux] Can't import sprays ("Unable to load vtex.dll")

### ISSUE THREAD

**Issue by OrdinaryMagician** [ValveSoftware/Source-1-Games#912] opened 2013-06-15 20:29 UTC
Yes, dll. I'm pretty sure I'm running on Linux, and without using Wine, by the way.

I can't check if this happens on other games right now.

On a side note, I wish there was a native Linux tool for edition of VTF files.

**Comment by FreeSlave** [comment] 2016-12-17 20:43
Issue is still present.

**Comment by kisak-valve** [comment] 2016-12-23 18:56
Closing as a duplicate of #705.

**Closed by kisak-valve** 2016-12-23 18:56 UTC
Labels: Left 4 Dead 2, Reviewed
