### ISSUE TITLE
[TF2] Streaming mode *Feature request*

### ISSUE THREAD

**Issue by perkoz323** [ValveSoftware/Source-1-Games#5999] opened 2024-05-12 16:58 UTC
Please add a streaming mode to TF2 that would change the following things: hide chat, blur avatars, and not display full usernames.

**Comment by NULLYUKI** [comment] 2024-05-12 17:00
Duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/4212

**Comment by kisak-valve** [comment] 2024-05-12 19:02
Hello @perkoz323, as @NULLYUKI noted, this request is already being tracked at #4212.

Closing as a duplicate.

**Closed as not planned by kisak-valve** 2024-05-12 19:02 UTC
