### ISSUE TITLE
[TF2,Linux,intel] Failed to lock vertex buffer crash

### ISSUE THREAD

**Issue by nightsky30** [ValveSoftware/Source-1-Games#2234] opened 2017-04-17 02:13 UTC
On the map loading screen I received the following error message prior to a crash:

Failed to lock vertex buffer in CMeshDX8::LockVertexBuffer: nVertexCount=49141, nFirstVertex=0

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected
    
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    CPU Family:  0x6
    CPU Model:  0x8e
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3500 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Ubuntu 16.04.2 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.10.0-19-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11804000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-beta-release_2016-12-05
    
Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Kabylake GT2 x86/MMX/SSE2

    Driver Version:  3.0 Mesa 12.0.6
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0x5916
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1200
    Primary Display Size: 18.78" x 10.55"  (21.54" diag)
                                            47.7cm x 26.8cm  (54.7cm diag)
    Primary VRAM Not Detected
    
Sound card:
    Audio device: Realtek ALC3246
    
Memory:
    RAM:  15926 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Steam Controller Cable and Base:  Not set
    Total Hard Disk Space Available:  445055 Mb
    Largest Free Hard Disk Block:  331711 Mb
    VR Headset: None detected
    
Recent Failure Reports:
    Mon Apr 17 00:56:15 2017 GMT: file ''/tmp/dumps/assert_20170416195614_24.dmp'', upload yes: ''CrashID=bp-7256f03f-de49-4f56-b2aa-734f72170416''
    Mon Apr 17 02:05:17 2017 GMT: file ''/tmp/dumps/crash_20170416201850_1.dmp'', upload yes: ''CrashID=bp-48edae91-ea9a-4876-b3ef-6ff762170416''
    
![screenshot_2017-04-16_21-05-01](https://cloud.githubusercontent.com/assets/6024315/25076779/906890ae-22e9-11e7-96d9-5344e16b5b13.png)

**Comment by kisak-valve** [comment] 2017-04-28 17:21
Noted in #2244, this is also being seen with mesa 17.0.4 and an Intel Haswell.

**Comment by nightsky30** [comment] 2017-11-03 21:52
Just an update, this is seen in Ubuntu 17.10 with Mesa 17.2.2

**Comment by ypsy** [comment] 2017-11-06 23:36
Same here on a Thinkpad X220i (Intel Core i3-2310M, Intel HD Graphics 3000, 8 GB Ram). Running ArchLinux with Mesa 17.2.4. I've been getting these for a while now but kinda settled with it, as it is a rather outdated laptop and I thought it just got hiccups sometimes. Since the Jungle Inferno update the crashes got very frequent though, almost after every mapchange. A workaround/fix would be nice.

**Comment by nightsky30** [comment] 2017-11-09 01:15
Is there any way I could help debug this issue?  I'm not sure any crash dumps or logs are being generated at this time, but I'll try keeping an eye out.

**Comment by nightsky30** [comment] 2018-03-13 01:25
Still getting this with the latest Mesa Git 18.0.1:

[System Info](https://gist.github.com/nightsky30/a36a2a69e488c55894bd50142948adc0)

I simply started the game and was in the main menu for a few seconds looking at an item that popped into my inventory when this happened.  I hadn't loaded a map or anything.

**Comment by DFOXpro** [comment] 2018-04-30 17:41
## This also happen with AMD+mesa 

Device:
CPU: AMD PhenomX2
GPU: AMD r9 280X
OS: Ubuntu 18.04 (Linux kerner 4.15.0-20)
GPU Driver: Mesa 18.2.0

glxinfo driver info log: 

```
    Device: AMD TAHITI (DRM 2.50.0, 4.15.0-20-generic, LLVM 6.0.0) (0x6798)
    Version: 18.2.0
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 3071 MB, largest block: 3071 MB
    VBO free aux. memory - total: 2043 MB, largest block: 2043 MB
    Texture free memory - total: 3071 MB, largest block: 3071 MB
    Texture free aux. memory - total: 2043 MB, largest block: 2043 MB
    Renderbuffer free memory - total: 3071 MB, largest block: 3071 MB
    Renderbuffer free aux. memory - total: 2043 MB, largest block: 2043 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 3072 MB
    Total available memory: 5115 MB
    Currently available dedicated video memory: 3071 MB
OpenGL vendor string: X.Org
OpenGL renderer string: AMD TAHITI (DRM 2.50.0, 4.15.0-20-generic, LLVM 6.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.2.0-devel
OpenGL core profile shading language version string: 4.50
```

![captura de pantalla -2018-04-30 12-36-09](https://user-images.githubusercontent.com/5248241/39441305-1a57b390-4c73-11e8-9330-4b1cf039fa66.png)

**Comment by DFOXpro** [comment] 2018-05-13 19:14
using the 2016 noHats mod seems to solve the problem, so may be this error is caused by some hat/skin/particle in particular

**Comment by kisak-valve** [comment] 2018-07-27 20:31
Can someone check if the situation improves with running TF2 with mesa 18.1.5?

**Comment by kisak-valve** [comment] 2018-08-31 16:47
Closing pending feedback.

**Closed by kisak-valve** 2018-08-31 16:47 UTC
Labels: Intel Driver, Linux, Team Fortress 2

**Comment by AaronBottegal** [comment] 2018-11-16 19:21
Currently seeing this error myself. Happened ever since I moved to the RX 480 from the Nvidia 1070, been about 2 months or so now.

OpenGL vendor string: X.Org
OpenGL renderer string: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.27.0, 4.19.2-1-ck, LLVM 7.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.2.4

To reproduce this error, load into a game, disconnect, and then load into another game. I tested it with two different community servers I was on and both crash.

Image: https://aaronbottegal.com/TempFiles/TF2.png

**Comment by kisak-valve** [comment] 2018-11-16 19:31
Hello @AaronBottegal, you're looking for #2483, not this issue report.

**Comment by AaronBottegal** [comment] 2018-11-16 19:43
Thanks, I'm gonna keep my eye on it if I can help at all.

**Comment by AaronBottegal** [comment] 2019-01-02 20:39
Looks like a commit landed that is supposed to alleviate this issue.

https://cgit.freedesktop.org/mesa/mesa/commit/?id=3ae57957be0296eea6799655e5f945db714c2584

**Comment by AaronBottegal** [comment] 2019-01-03 00:45
Just compiled and tested, it does not fix the issues with loading into a game. Hit the 4GB RAM limit while loading in. My config is probably to blame. Waiting patiently for a 64-bit TF2, hah.
