### ISSUE TITLE
[TF2] Soldier's left arm using Original with Ultrawide monitor

### ISSUE THREAD

**Issue by nwerosama** [ValveSoftware/Source-1-Games#6034] opened 2024-05-31 07:23 UTC
If the monitor's resolution far exceeds game's expectations of resolution setting, the Original rocket launcher shows Soldier's left arm and effectively obstructing the view on left side of the screen as shown in screenshot below. I believe this has been around for years and I just decided to open an issue now, it's mildly annoying to deal with but not affecting anything gameplay-wise.

![image](https://github.com/ValveSoftware/Source-1-Games/assets/96593068/257e7801-8ef2-4049-8f1d-3479c684928a)

Edited 50 mins later: I see that there's multiple issues on this, for some reason the search didn't show it earlier... (calling this one a duplicate of #5759)

**Comment by kisak-valve** [comment] 2024-05-31 12:32
Closing as a duplicate of #5759.

**Closed as not planned by kisak-valve** 2024-05-31 12:32 UTC
