### ISSUE TITLE
[L4D2] [Linux] Crash when joining or starting games with "Official Dedicated" servers

### ISSUE THREAD

**Issue by Sharparam** [ValveSoftware/Source-1-Games#5986] opened 2024-05-07 23:10 UTC
When starting or joining a multiplayer campaign (or any other game mode) using the "Official dedicated" option, the game will crash just before halfway on the loading bar. The crash also happens when choosing the "Best available dedicated" option.

Using the "local server" option works, and single player also works fine.

Output from running `steam-runtime` in terminal here: https://gist.github.com/Sharparam/2d7cf51812892324eccca50a3c1d7428

OS: Arch Linux
`uname -a`: `Linux melina 6.8.9-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 02 May 2024 17:48:53 +0000 x86_64 GNU/Linux`
Dump file: [crash_20240508010322_3.zip](https://github.com/ValveSoftware/Source-1-Games/files/15242040/crash_20240508010322_3.zip)

Tested with both `steam-runtime` and `steam-native`, both experience the crash.

Edit:
Using the 1.0 Linux runtime ("scout") has the same issue.
Using Proton experimental or 9.0-1 instead gets that it cannot find any official dedicated servers, but the "best available" option works and connects to some third-party server.

**Comment by kisak-valve** [comment] 2024-05-07 23:40
For reference, the attached minidump is a SIGBUS in studiorender.so.

Hello @Sharparam, this is unlikely, but can you check if https://gitlab.freedesktop.org/drm/amd/-/issues/3343 is relevant to your system? A quick test would be to reboot into an older kernel and see how the game behaves.

**Comment by Sharparam** [comment] 2024-05-08 00:13
@kisak-valve That issue sounds like if it applied, single player shouldn't work either? But now that I'm testing again, it *is* crashing in single player as well on latest kernel (6.8.9), not sure why it worked before.

Downgrading the kernel to 6.8.8 or earlier does make things work.

**Comment by Sharparam** [comment] 2024-05-08 00:26
@kisak-valve Further update: I discovered I did not have the "Enable 4G memory" (or something to that effect) enabled in BIOS, after enabling that (I already had resizable BAR enabled), L4D2 now works on the latest kernel.

(Same with Lies of P, which I hadn't even noticed stopped working since I haven't played that in a while.)

**Comment by z5vix** [comment] 2024-05-10 02:48
my game keeps crashing only when playing long sessions on linux.

**Comment by NULLYUKI** [comment] 2024-05-10 08:58
> my game keeps crashing only when playing long sessions on linux.

Which Linux distribution are you using?
And can you share your crash log please.

**Comment by z5vix** [comment] 2024-05-11 17:48
nobara linux, and i cant find the crashlog output

edited to add: the crashes happen from random times but it did just happen now, it typically unloads tiles before inevitally crashing, i cant find a way to fix this, maybe you know based on what i just described. Im also using Nobara Linux KDE Plasma version.

**Comment by Voklen** [comment] 2024-05-18 12:18
This issue seems to be the same as #5973 and is fixed in the Linux kernel 6.9.1.

**Comment by kisak-valve** [comment] 2024-06-28 18:41
Closing as fixed in the kernel.

**Closed as completed by kisak-valve** 2024-06-28 18:41 UTC
Labels: AMD/ATI Driver, Linux, Left 4 Dead 2

**Comment by gamertyke** [comment] 2024-09-04 06:11
I believe I am seeing this behavior (the one in the OP) on a fully patched Nobara system (kernel 6.10.6). 7800X3D/3090

**Comment by kisak-valve** [comment] 2024-09-04 12:20
Hello @gamertyke, the issue tracked in this issue report was a 6.8.9 specific amdgpu kernel module regression. Please open a new issue report.

**Comment by mspencerl87** [comment] 2025-05-22 22:17
Hmm, this is happening again on Nobara 42 with a 6700XT.
It only happens in Survival mode, with online games, single player works fine. As soon as the map loads and there are visuals it crashes to desktop :(

**Comment by nipnipj** [comment] 2025-07-26 21:53
As soon as the map starts, the game crashes.

Adding `-vulkan` to launch arguments helped.

**Comment by mockdot** [comment] 2025-07-28 02:43
> As soon as the map starts, the game crashes.
> 
> Adding `-vulkan` to launch arguments helped.

Thank you! This fixed all issues in L4D2 when running via Steam Linux Runtime.
