### ISSUE TITLE
[Portal 2] Portal 2 sourcemods download workshop content, wasting storage space.

### ISSUE THREAD

**Issue by kotenok2000** [ValveSoftware/Source-1-Games#6553] opened 2024-11-16 14:12 UTC
When I subscribed to workshop maps and started portal 2 sourcemod I noticed, that game creates workshop directory  in sourcemod/maps directory and starts to download workshop maps in it.
I was able to mitigate that by creating a file with that name, so game can't create folder.

**Comment by kisak-valve** [comment] 2024-11-16 14:15
Hello @kotenok2000, please do not intentionally open duplicate issue reports.

Closing as a duplicate of https://github.com/ValveSoftware/portal2/issues/427.

**Closed as not planned by kisak-valve** 2024-11-16 14:15 UTC
