### ISSUE TITLE
TF2 does not run on steam deck

### ISSUE THREAD

**Issue by Muthaducka** [ValveSoftware/Source-1-Games#5735] opened 2024-04-19 12:54 UTC
I play the game on steam deck in desktop mode, when you click play on steam it asks if you want to use "play TF2" or "legacy openGL" launch options. Both do the same thing, the play button turns blue for a split second then the button turns green again. You can run the game with proton and with console commands but it won't let you join a match if you do it that way. It says I'm in insecure mode.

**Comment by JoriKos** [comment] 2024-04-19 13:18
Seems like a dupe of #5621 as it also mentions proton + insecure mode

**Comment by kisak-valve** [comment] 2024-04-19 15:00
Hello @Muthaducka, as @JoriKos noted, this issue is already being tracked at #5621. Closing as a duplicate.

**Closed by kisak-valve** 2024-04-19 15:00 UTC
