### ISSUE TITLE
[TF2] Projectiles impacting invisible map tiles (Dragon's Fury, Wrap Assassin, Pomson, Bison, Short Circuit)

### ISSUE THREAD

**Issue by Sweddy** [ValveSoftware/Source-1-Games#2702] opened 2018-11-27 18:28 UTC
Hello,
this report is a collection of observations of a weapon-breaking bug observed by the community. The bug involves certain projectiles, such as the Wrap Assassin's bauble, the Pomson's laser, the Righteous Bison's laser, and apparently also the Dragon's Fury's flame ball, being destroyed or having their effects nullified on impact with certain invisible map properties. This seems to apply particularly to slopes. 

Here is a video example of the bug in action, on the Dragon's Fury, posted to reddit by the user u/Deathaster a few days ago. (2018-11-25): https://www.reddit.com/r/tf2/comments/a0c1mp/excuse_me_what_is_going_on_here/   

Here is a detailed reddit post by the user u/AoiHono-BlueFlame, who has seemingly managed to track down the exact invisible map tiles responsive for the bug: 
https://www.reddit.com/r/truetf2/comments/9y1ttd/wrap_assassin_collisions/ 
   
This issue has seemingly been around for quite a while. Here is a video released about a year ago once again showing the bug it in action:
https://www.youtube.com/watch?v=sWgXw1voYy4

Here is also a very detailed post, explaining the bug further, also posted about one year ago by the user u/DarkNecrid:
https://www.reddit.com/r/tf2/comments/6cd0cd/psa_the_pomson_6000_and_wrap_assassin_will_not/

Because of this bug, players, including myself, have been discouraged from using the affected weapons. Furthermore, players unaware of the bug probably feel very frustrated upon discovering it.

**Comment by Sweddy** [comment] 2018-11-29 05:56
UPDATE: It seems the same applies to the Short Circuits energy ball.

Some locations where this applies include the back room in Red base on the final point of Frontier and

**Comment by Sweddy** [comment] 2018-11-29 05:57
UPDATE: The same bug applies to the Short Circuit's energy ball.
Also I don't know how this site works and accidentally closed and reopen the issue.

**Comment by h9lk** [comment] 2018-11-29 17:51
It's strange that they noticed a bug just now, Jungle Inferno Update has been added in October 20, 2017 Patch... Anyway after the bug https://github.com/ValveSoftware/Source-1-Games/issues/2493 - 
I'm not surprised at anything

**Comment by Sweddy** [comment] 2018-12-01 14:45
I have made a video showing some of the weapons affected as well as where they are affected, which can be found here:
https://youtu.be/aRHDRh9yJN0

**Comment by kisak-valve** [comment] 2021-11-15 23:57
Hello, per "Fixed Dragon's Fury, Short Circuit, and tf_projectile_energy_ring projectiles colliding with func_lod entities" in the [2021-11-15](https://www.teamfortress.com/post.php?id=101361) TF2 update, please retest.

**Comment by agrastiOs** [comment] 2021-11-16 12:50
@kisak-valve just tested, every projectile except the Wrap Assassin's bauble is fixed. I can suggest updating the title.

**Comment by kisak-valve** [comment] 2021-12-03 02:20
Hello again, per "Fixed Wrap Assassin projectiles colliding with other projectiles and func_lod entities" in the [2021-12-02](https://www.teamfortress.com/post.php?id=101867) TF2 update, please retest.

**Comment by agrastiOs** [comment] 2021-12-03 04:42
Thanks for the fix! However, I can confirm that it is still broken on prop_dynamic (e.g. Badwater last point), unlike the other projectiles that got fully fixed.

**Comment by echaskaris** [comment] 2021-12-03 11:12
Wrap Assassin still collides with that huge invisible box on badwater last.

**Comment by agrastiOs** [comment] 2021-12-18 06:14
Not anymore! Only parts of a map all the projectiles collide with is func_brush.

**Comment by echaskaris** [comment] 2021-12-18 09:50
Yes, it's fixed on badwater last, finally.

**Comment by kisak-valve** [comment] 2022-01-21 20:21
Thanks for retesting. Closing as fixed.

**Closed by kisak-valve** 2022-01-21 20:21 UTC
Labels: Team Fortress 2, Need Retest

**Comment by jh34ghu43gu** [comment] 2022-10-02 21:01
@kisak-valve this actually is still broken on a few places such as hightower and watchtower

https://www.youtube.com/watch?v=cv5iwBavJGA

This video linked on the wiki (prior to this reply) tries to claim it's a visual bug
https://www.youtube.com/watch?v=44yxtsGqpvg
Counter proof recorded today on watchtower due to the larger area
https://youtu.be/vJ8n-o8fwLQ

It isn't a trigger or a clip brush that they are colliding with so idk what's causing it

**Comment by kisak-valve** [comment] 2022-10-02 23:05
Hello @jh34ghu43gu, please open a new issue report so that your issue can be tracked properly.

**Comment by Ashetf2** [comment] 2023-03-25 23:34
Yeah it's still broken for func_brush
