### ISSUE TITLE
[TF2] In PASS Time pressing the scroll wheel 3 times will disconnect you from the server. 

### ISSUE THREAD

**Issue by gaelcoral** [ValveSoftware/Source-1-Games#4798] opened 2023-02-26 09:08 UTC
https://user-images.githubusercontent.com/63524243/221401644-27d03b96-0b89-4615-bb48-3127424d25f2.mp4

**Comment by Ashetf2** [comment] 2023-02-26 14:35
Duplicate of #3353

**Comment by kisak-valve** [comment] 2023-02-26 20:11
Closing as a duplicate.

**Closed by kisak-valve** 2023-02-26 20:11 UTC
