### ISSUE TITLE
[TF2] Bugged UI in arena - Number of living BLU players not visible

### ISSUE THREAD

**Issue by luki1412** [ValveSoftware/Source-1-Games#4562] opened 2022-12-06 12:12 UTC
UI hides the number of living blu players in arena mode.

Windows 11(happened on 10 also), Nvidia geforce 1070 maxq, Resolution 1920x1080
Happens in spectator and while playing. With minmode enabled and disabled.

Steps:
1.load game
2.enter "map arena_*"  (i tested with byre and badlands) into the console
3.(optional) add bots to be able to spawn

![20221206123444_1](https://user-images.githubusercontent.com/20016096/205903233-64336407-49cc-49b5-ab83-5e05c59028a5.jpg)
![20221206123523_1](https://user-images.githubusercontent.com/20016096/205903238-82cd42eb-c6fc-4438-a993-b96cd348f5a4.jpg)
![20221206124111_1](https://user-images.githubusercontent.com/20016096/205903240-ede950e9-68b5-4443-8c5b-9d4379065129.jpg)
![20221206124143_1](https://user-images.githubusercontent.com/20016096/205903243-04afe821-e25a-4344-b154-5016b577ef3b.jpg)

**Comment by worMatty** [comment] 2022-12-06 14:51
I believe this is a duplicate of issue #3967

**Comment by luki1412** [comment] 2022-12-06 14:55
> I believe this is a duplicate of issue #3967

True. Nothing came up when I was searching for the issue.

**Comment by kisak-valve** [comment] 2022-12-06 14:59
Closing in favor of the older issue report.

**Closed by kisak-valve** 2022-12-06 14:59 UTC
Labels: Team Fortress 2, User Interface
