### ISSUE TITLE
[TF2] [Feature Request] More Loadout buttons (like the ABCD)

### ISSUE THREAD

**Issue by WolfoIsBestWolf** [ValveSoftware/Source-1-Games#4868] opened 2023-03-25 15:14 UTC
An extra EF slot or a whole second row with EFGH

With the many different playstyles and huge amount of cosmetics some people would like more than 4 Loadouts to more easily switch between them.
This feature would mostly benefit players with large backpacks or who want to keep things really organized.

This could be implemented with a Extra Loadout item that you buy similar to the Backpack Expander as to not give new players too many loadouts and to make some profit.

**Comment by kisak-valve** [comment] 2023-03-25 15:29
Hello @WolfoIsBestWolf, this is functionally a duplicate of #2399. Closing in favor of the older feature request.

**Closed by kisak-valve** 2023-03-25 15:29 UTC
