### ISSUE TITLE
[TF2] The game is still marked as a 32-bit game in library

### ISSUE THREAD

**Issue by CosminPerRam** [ValveSoftware/Source-1-Games#5721] opened 2024-04-19 09:40 UTC
**Note**: The game is not officially supported on MacOS anymore, this issue is just to state that the game is still marked as 32 bit while its not anymore. This issue isn't related to MacOS support or compatibility.

# Problem
The game is still marked as being 32-bit, although this is not a game-specific issue, I thought it'll be alright to mention it here.

# Reproduce
1. Start steam on a newer MacOS system that does not support 32-bit anymore.
2. Enter the library and select TF2

# Extra context
System: MacBook Pro 13" M1 2020 8GB
MacOS: Sonoma 14.1.1

A screenshot of the game in my steam library:
![image](https://github.com/ValveSoftware/Source-1-Games/assets/7972857/3acaa6d7-316a-413c-b4aa-f67840324408)

# Expected behaviour
The game to not being marked as 32-bit anymore.

**Comment by JoriKos** [comment] 2024-04-19 10:00
Duplicate of #5625

**Closed** 2024-04-19 10:02 UTC
