### ISSUE TITLE
[Linux] [L4D2] Mouse Clicks Not Registering

### ISSUE THREAD

**Issue by sunnybubblegum** [ValveSoftware/Source-1-Games#1805] opened 2014-08-19 00:25 UTC
In my Left 4 Dead 2 session today, my mouse buttons in-game were unresponsive about half of the time. I sometimes had to click them up to four, five, even seven times, or worse indefinitely, before the game responded. This occurred with both the left-click and right-click. I didn't seem to have the problem on the game menus, only in-game.

Then other times, I would click the mouse buttons, and the character would start shooting or shoving repeatedly and indefinitely. It only stopped when I clicked the respective mouse buttons again (sometimes after multiple tries, as well).

Everything other than the mouse clicks was working well: mouse movement, keyboard strokes, etc.

At first I thought it was only because of my high ping connection to the server I was on. But then I tried hosting my own game, and it still happened. Then I tried playing single player, and it still happened. I started to worry my mouse was failing.

I quit the game, and tested my mouse out on the desktop. It seems to be working great -- both left and right clicks. So it's not the mouse.

I also tested playing another game afterward, and the mouse clicks all register as usual. I guess it remains to be seen whether this problem will persist in future Left 4 Dead 2 sessions.

The mouse I use is an HP, PS/2-connected mouse.

System Information:

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0x5
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3100 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.5 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.8.0-44-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2014-07-22

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 240/PCIe/SSE2

```
Driver Version:  3.3.0 NVIDIA 331.38
OpenGL Version: 3.3
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0xca3
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 23.62" x 13.39"  (27.13" diag)
                                        60.0cm x 34.0cm  (68.9cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: VIA VT1708S

Memory:
    RAM:  7984 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_CA.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  232570 Mb
    Largest Free Hard Disk Block:  89159 Mb

Installed software:

Recent Failure Reports:

**Comment by jwcalla** [comment] 2015-09-06 04:08
I experienced this again tonight and tracked it down to one of the Cube compiz plugins.  I'm not sure which of the three (I'll dig in deeper later), but after disabling them the issue went away.

It makes me wonder just how much latency, performance and other issues can be caused by compiz plugins.

**Comment by kisak-valve** [comment] 2017-01-31 16:07
Closing pending feedback.

**Closed by kisak-valve** 2017-01-31 16:07 UTC
Labels: Left 4 Dead 2, Linux, Need Retest

**Comment by eversins** [comment] 2017-04-27 22:35
I am running Manjaro KDE with newest drivers/software, I have constant 300FPS and still have this issue. If you wan't additional info's let met know.
