### ISSUE TITLE
(TF2 64 Bit, Windows 10) I keep crashing randomly and during the map swap

### ISSUE THREAD

**Issue by Xavibite** [ValveSoftware/Source-1-Games#5935] opened 2024-04-28 04:19 UTC
I've tried legit everything, from using 32 bit to reinstalling the game and nvidia drivers
This has been happening since the update released

Here are 5 crash logs, all from today, 2 of them being random and 3 of them being map swaps.

[crash_tf_win64.exe_20240427205721_1.dmp](https://github.com/ValveSoftware/Source-1-Games/files/15140753/crash_tf_win64.exe_20240427205721_1.dmp)
[crash_tf_win64.exe_20240427211759_1.dmp](https://github.com/ValveSoftware/Source-1-Games/files/15140754/crash_tf_win64.exe_20240427211759_1.dmp)
[crash_tf_win64.exe_20240427223808_1.dmp](https://github.com/ValveSoftware/Source-1-Games/files/15140755/crash_tf_win64.exe_20240427223808_1.dmp)
[crash_tf_win64.exe_20240427231708_1.dmp](https://github.com/ValveSoftware/Source-1-Games/files/15140756/crash_tf_win64.exe_20240427231708_1.dmp)
[crash_tf_win64.exe_20240427234512_1.dmp](https://github.com/ValveSoftware/Source-1-Games/files/15140757/crash_tf_win64.exe_20240427234512_1.dmp)

**Comment by NULLYUKI** [comment] 2024-04-28 04:21
Duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/5885

**Closed** 2024-04-30 02:39 UTC
Labels: Team Fortress 2, Windows
