### ISSUE TITLE
How difficult is to port Left for dead 1 to Linux?

### ISSUE THREAD

**Issue by ekaris** [ValveSoftware/Source-1-Games#1986] opened 2016-06-11 12:44 UTC
How difficult is to port Left for dead

**Comment by ElectricTriangle** [comment] 2016-06-16 18:18
Not a bug, not a suggestion. Also nearly entirely pointless since L4D2 includes the original maps.

**Comment by ViBE-HU** [comment] 2016-06-16 18:36
@ElectricTriangle that's true but the games are not compatible with each other. so if a user only have L4D for some reason(s), L4D maps in L4D2 does not make any sense, so...

**Comment by Tele42** [comment] 2016-06-16 19:36
@ViBE-HU, the main map campaigns from L4D(1) are included in L4D2, but with the L4D2 game mechanics.

Really, this issue report should be a straight request for L4D(1) for linux, not a leading questing in that direction. I enjoyed the L4D(1) game mechanics a bit better than L4D2, but that's just personal opinion.

**Comment by steamlinux** [comment] 2016-06-16 19:46
l4d2 doesn't have legs:D

**Comment by kisak-valve** [comment] 2016-12-30 20:02
Closing as a duplicate of #1812.

**Closed by kisak-valve** 2016-12-30 20:02 UTC
