### ISSUE TITLE
[TF2] Item Servers have been down for almost 2 days

### ISSUE THREAD

**Issue by AzureWoof** [ValveSoftware/Source-1-Games#5411] opened 2024-01-11 19:09 UTC
The item servers for TF2 seem to have been having major issues as of late for almost 2 entire days now. It's extremely rare for it to actually let you use your loadout, especially on official servers. Posting this here because this is abnormal behavior.

**Comment by kisak-valve** [comment] 2024-01-11 19:13
Possible duplicate of #5405.

**Comment by BreavyTF2** [comment] 2024-01-11 19:38
Items are back online.

**Comment by gaelcoral** [comment] 2024-01-11 22:06
I can confirm that the item servers are now working!
![2024-01-11 (10)](https://github.com/ValveSoftware/Source-1-Games/assets/63524243/a3452289-3944-4362-beb4-92412de2dd93)

**Comment by AwesomeCoder412412** [comment] 2024-01-18 14:45
Definitely want to close this, as it's fixed @kisak-valve

**Comment by kisak-valve** [comment] 2024-03-02 01:12
Closing per the handful of comments.

**Closed by kisak-valve** 2024-03-02 01:12 UTC
Labels: Team Fortress 2, Need Retest
