### ISSUE TITLE
Random fall damage is always there even if random damage spread is turned off

### ISSUE THREAD

**Issue by agrastiOs** [ValveSoftware/Source-1-Games#2571] opened 2018-04-14 23:21 UTC
Fall damage will always have 20% variance and is hard coded in TF2, thus staying even if the random damage spread is turned off.

**Comment by FindTheBorealis** [comment] 2018-04-15 01:26
Duplicate of #2489

**Comment by kisak-valve** [comment] 2018-04-15 02:06
Indeed, closing as a duplicate.

**Closed by kisak-valve** 2018-04-15 02:06 UTC
Labels: Team Fortress 2
