### ISSUE TITLE
[TF2] The Sydney Sleeper does not  have a blu skin

### ISSUE THREAD

**Issue by Ismaciodismorphus** [ValveSoftware/Source-1-Games#4196] opened 2022-08-21 03:12 UTC
The darts on the Sydney Sleeper's weapon model do not turn blue when used by a blue sniper despite the fact that the darts in bullet bodygroup of the sniper model are turned blue when the Sydney Sleeper is used by a blue sniper.

**Comment by condor00fr** [comment] 2022-08-21 12:14
there's actualy a lot of weapons that don't have a BLU variant such as the disguise kit, the razorback or the Winger, but there was a mod out there to fix this issue here, it's quite literally a drag and drop:
https://steamcommunity.com/sharedfiles/filedetails/?id=1512670207

**Comment by condor00fr** [comment] 2022-09-18 13:36
so.... the workshop mod I proposed dosn't have an actual sydney sleeper skin... so here is one on game banana made by SeizeTheBeans: (https://gamebanana.com/members/1685248)

**Comment by kisak-valve** [comment] 2022-09-26 19:58
Hello, per "Fixed missing BLU skin for The Sydney Sleeper" in the [2022-09-26](https://www.teamfortress.com/post.php?id=143572) Team Fortress 2 update, please retest this issue.

**Comment by agrastiOs** [comment] 2022-09-26 20:11
Can confirm it's fixed.

![paveikslas](https://user-images.githubusercontent.com/15906773/192370640-b9863eb4-814b-4da1-bf70-db7b03095ad5.png)

**Comment by Ismaciodismorphus** [comment] 2022-09-26 20:17
![Team Fortress 2 Screenshot 2022 09 27 - 05 44 28 62](https://user-images.githubusercontent.com/101957605/192371643-9ba5c74c-c14c-4a5b-902a-16bda5491ac7.png)
Can also confirm

**Comment by renimg** [comment] 2022-09-27 00:39
![blender_2022-09-26_16-11-30](https://user-images.githubusercontent.com/48497753/192405132-b03fe5d3-bafd-4eb0-b3ce-4f741b76f259.png)
There's a small issue with this where there's a bit of the blue paint-over on the dart feathers is on the bottom of the stock.

**Comment by MikhailaTF** [comment] 2022-10-22 16:41
can also confirm the original issue has been fixed, the new skin works as intended. however as per renimg's comment, there's indeed a small error with the texture still.

**Comment by kisak-valve** [comment] 2022-11-25 21:13
Closing as fixed. I went ahead and opened #4532 for the follow up issue.

**Closed by kisak-valve** 2022-11-25 21:13 UTC
Labels: Team Fortress 2, Need Retest, Art
