### ISSUE TITLE
[TF2] box_cluster03 prop has the wrong texture assignment and a busted UV map

### ISSUE THREAD

**Issue by stevethepocket** [ValveSoftware/Source-1-Games#6307] opened 2024-08-25 23:24 UTC
[As referenced in this video](https://www.youtube.com/watch?v=OvtMFMfrV0E), not only does the file refer to the wrong material, the UV does not line up with any known texture. (In fact, it has way more faces than the actual prop does; I have no idea what they all reference.) Low priority since the prop has only ever been used in cp_junction, probably because all of Valve's official mappers realized it was broken but couldn't get anyone to fix it.

**Comment by NULLYUKI** [comment] 2024-08-25 23:25
Duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/6281

**Comment by kisak-valve** [comment] 2024-08-25 23:28
Hello @stevethepocket, as @NULLYUKI noted, this issue is already being tracked at #6281. Closing as a duplicate.

**Closed as not planned by kisak-valve** 2024-08-25 23:28 UTC
