### ISSUE TITLE
[TF2] Add timer onto CTF Frosty

### ISSUE THREAD

**Issue by ShadowMan44** [ValveSoftware/Source-1-Games#4561] opened 2022-12-06 09:30 UTC
I know I know, it would make people not want to be friendly

But damn it, I want a CTF map that people actually want to play the objective for. Helltrain was timed, and every round I played never got friendly (except if there was like only 5 people in the server). It's a simple thing to add to completely change the flow of gameplay.

**Comment by kisak-valve** [comment] 2022-12-06 13:50
Hello @ShadowMan44, this is functionally a duplicate of #3402. Closing as a duplicate.

**Closed by kisak-valve** 2022-12-06 13:50 UTC
