### ISSUE TITLE
[TF2] Missing texture in the backpack menu when exiting a server

### ISSUE THREAD

**Issue by ShadowMan44** [ValveSoftware/Source-1-Games#4235] opened 2022-08-30 00:04 UTC
I don't have a screenshot for this at the moment, but you know when you click the help icon in the backpack, there's supposed to be this white texture as the speech bubble arrows? Well, for some odd reason this specific texture will corrupt/go missing whenever I exit a server. I can't remember how this is exactly triggered but I remember it happening when playing on Community servers.

I will update this with a screenshot if I can get one.,

**Comment by ShadowMan44** [comment] 2022-09-05 02:38
![tf2 arrow texture missing](https://user-images.githubusercontent.com/42453370/188350223-c0c6ed53-266f-48f9-a4ce-223490be28c1.png)
Here is the screenshot

**Comment by ljcool2006** [comment] 2022-12-06 01:39
Duplicate of #2074

**Comment by ShadowMan44** [comment] 2022-12-06 01:46
> Duplicate of #2074

Kay

**Comment by kisak-valve** [comment] 2022-12-06 01:47
Closing in favor of the older issue report.

**Closed by kisak-valve** 2022-12-06 01:47 UTC
Labels: Team Fortress 2, Texture
