### ISSUE TITLE
[HL2DM] Quickly changing weapons makes view model disappear

### ISSUE THREAD

**Issue by darrnoktjurna** [ValveSoftware/Source-1-Games#1314] opened 2013-09-18 09:47 UTC
Quickly changing weapons makes view model disappear.

http://youtu.be/iSzzyEBxrMw?t=15m55s

**Comment by kisak-valve** [comment] 2016-12-21 14:16
Closing as a duplicate of #219.

**Closed by kisak-valve** 2016-12-21 14:16 UTC
Labels: Half-Life 2: Deathmatch, Reviewed
