### ISSUE TITLE
Vaccinator resistance icons persisting between rounds.

### ISSUE THREAD

**Issue by Zungrysoft** [ValveSoftware/Source-1-Games#4672] opened 2023-01-06 08:45 UTC
**Issue:** Vaccinator icons can persist on players who are no longer being healed by a Medic who is using the Vaccinator.

**How to Reproduce:** Play any gamemode where the teams switch sides between rounds. (Such as Attack/Defend or Payload.) Finish a round. Then, during post-round humiliation, heal one of your teammates with the vaccinator and keep healing them until the teams switch sides. When the next round begins, your teammate will still have the vaccinator resistance icon above their head. (The color of the icon will be of the team you were on before the switch.)

Another thing to note is that the false icon will go away if the correct resistance type (and color) is applied, then taken away. (So if they have a red explosion-resist icon, it will go away if red explosion-resist is applied, then switched away from.)

This bug does not appear to  occur on gamemodes where the teams do not switch sides between rounds. (Such as King of the Hill or Symmetrical Control Points.)

I have also heard that this can happen when healing a disguised enemy spy and they lose their disguise while being healed. (Possibly for similar reasons, as their "apparent team" changes while the icon is above their head.) I did not attempt to reproduce this.

Here is a screenshot I captured of this in action. I am on red team and am applying bullet resistance to the Engineer bot, but it also has a blue fire resistance shield from the previous round and a red explosion resist icon from two rounds ago. If I cycle to explosion resistance, the false red explosion icon will be fixed, but the blue fire icon will not go away.
![vaccinatorshields](https://user-images.githubusercontent.com/21090689/210964000-d98ba604-498c-42a5-afa4-fbce0232f988.png)

**Comment by JoriKos** [comment] 2023-01-06 10:27
I've also heard reports of this happening when a player gets autobalanced. IIRC it persists when a Spy goes invisible (I vaguely remember getting accused of cheating when I kept seeing a floating vaccinator icon).

**Comment by Ashetf2** [comment] 2023-01-06 16:38
Duplicate of #2334

**Comment by kisak-valve** [comment] 2023-01-06 16:41
Thanks @Ashetf2, closing in favor of the older issue report.

**Closed by kisak-valve** 2023-01-06 16:41 UTC
