### ISSUE TITLE
[TF2] Unused Text Chat Icon on players

### ISSUE THREAD

**Issue by JonaMake** [ValveSoftware/Source-1-Games#4107] opened 2022-07-26 16:12 UTC
Add an icon above the player when he writes something to the chat
![image](https://user-images.githubusercontent.com/73250357/181056226-27b04d1e-0a25-4ed1-95ce-53094df52d00.png)
in game:
![Screenshot_1](https://user-images.githubusercontent.com/73250357/181056718-0a8134f5-aacd-4fae-ade9-9057e932c7a2.png)

**Comment by rabscootle** [comment] 2022-07-27 02:06
Chat bubble would maybe need a new asset to fit the new style used for 'MEDIC!' call (as of Two Cities Update):
![image](https://user-images.githubusercontent.com/108029512/181144740-3ec7b87d-e0ed-49ca-9ec2-8abb4fc438f7.png)

**Comment by condor00fr** [comment] 2022-08-01 09:56
good idea, tf2c did it, so why not in live?

**Comment by Ashetf2** [comment] 2022-08-06 21:41
Duplicate of #2052?

**Comment by kisak-valve** [comment] 2022-08-06 22:47
Indeed, closing in favor of the older feature request.

**Closed by kisak-valve** 2022-08-06 22:47 UTC
Labels: Feature Request, Team Fortress 2
