### ISSUE TITLE
[TF2] Graphics issue when in water on 2FORT

### ISSUE THREAD

**Issue by josephbisch** [ValveSoftware/Source-1-Games#1512] opened 2013-10-27 06:20 UTC
When I am in the water on 2FORT and either crouch or look at a certain angle there are graphics issues as seen in the attached images. Half the images show the issue and half show what I normally see when not crouching or looking at an angle.

Reproduce the issue by connecting to 67.228.59.146:27015, which should be playing 2FORT. Choose engineer and navigate the map so that you are standing on water. Now crouching or looking in certain directions should reproduce the issue. I am unsure if the character or server are significant.

I have not had an issue with any other map.

I am running Crunchbang Linux 64 bit, but I am using the Debian Testing repos. I have Intel HD Graphics 2000.

```
joseph@crunchbang:~$ glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ironlake Mobile 
OpenGL version string: 2.1 Mesa 9.1.6
OpenGL shading language version string: 1.20
OpenGL extensions:
```

![2013-10-27_00001](https://f.cloud.github.com/assets/665854/1415012/3145c798-3ece-11e3-806b-62b514c83e03.jpg)
![2013-10-27_00003](https://f.cloud.github.com/assets/665854/1415013/31464236-3ece-11e3-9b32-959259f8af95.jpg)
![2013-10-27_00002](https://f.cloud.github.com/assets/665854/1415014/31467b52-3ece-11e3-8d43-420cb93fab5f.jpg)
![2013-10-27_00004](https://f.cloud.github.com/assets/665854/1415015/31468c46-3ece-11e3-85be-f6189f02d0d5.jpg)

**Comment by kisak-valve** [comment] 2016-12-28 13:43
Closing per the last comment.

**Closed by kisak-valve** 2016-12-28 13:43 UTC

**Comment by SstarLit** [comment] 2024-12-05 13:05
found this issue in source sdk base 2013 in TF2:classic i am on windows 11 and the issue appears when i use mastercomfig, so the cause is a console setting. this means we just need to figure what causes this and its presumable tf2 prevents this now by disallowing whatever settings cause this.
![image](https://github.com/user-attachments/assets/28fe6fbf-5653-4f2c-a280-138ebce995af)

**Comment by Retsko** [comment] 2025-07-24 05:11
> Replying to https://github.com/ValveSoftware/Source-1-Games/issues/1512#issuecomment-2520274244

i have the same problem when i use Comanglia config, I'm trying to solve this problem from the GFX, I think the problem is there, because when I remove the GFX from Comanglia this problem disappears, if I solve it I will give answers
