### ISSUE TITLE
[TF2] GetDisguiseMaxHealth does not take account of "max health additive bonus"

### ISSUE THREAD

**Issue by KaelaSavia** [ValveSoftware/Source-1-Games#5390] opened 2024-01-01 17:00 UTC
The result is that spy's health can appear as overhealed when it shouldn't happen if they disguise as someone who has weapon equipped with "max health additive bonus" attribute

**Comment by JoriKos** [comment] 2024-01-02 17:11
Seems to be a duplicate of #4548

**Comment by kisak-valve** [comment] 2024-01-02 17:19
Thanks @JoriKos, closing in favor of the older issue report.

**Closed by kisak-valve** 2024-01-02 17:19 UTC
Labels: Team Fortress 2
