### ISSUE TITLE
[TF2] Strange lag when getting killed

### ISSUE THREAD

**Issue by UAVXP** [ValveSoftware/Source-1-Games#3938] opened 2022-06-23 10:42 UTC
Hello. Yesterday, after the [latest update](https://www.teamfortress.com/post.php?id=139819) me and my friend experienced a huge time-consuming lag, when getting killed on Valve Matchmaking servers.
The maps were ctf_2fort, ctf_doublecross and koth_harvest (haven't tried other maps though). After it begins to happen I asked about it in game chat, and received a few confirmations that this lag happened to some guys.

This lag takes almost exactly the whole death period (8-15 seconds) and initiates right after the death camera approaches the killer. It starts with a second lag, and increases in time to the point when I got kicked from a server due to "Client disconnect".

Under "lag" I mean whole game just stops working, and the last played sound is repeating itself, until my next spawn
Notice: you must be killed by a player/sentry, not by "kill" in console or jumping down the pit on Double Cross

My PC:
[uavxp_pc.txt](https://github.com/ValveSoftware/Source-1-Games/files/8966482/uavxp_pc.txt)

During this lag RAM usage is not increasing, and CPU utilization is dropping from around 90% to 70%. GPU usage drops to 4%

My `custom` folder contains [Bot Detector Vote HUD](https://gamebanana.com/mods/26382), which messes with `resource` folder

I use Comanglia's Toaster FPS config from here: https://cfg.tf/make/ with a few changes: [uavxp_config.zip](https://github.com/ValveSoftware/Source-1-Games/files/8966479/uavxp_config.zip)
My friend is using straight up Comanglia: Toaster config without dramatic changes

Also me and my friend were using TF2 Bot Detector software from here: https://github.com/PazerOP/tf2_bot_detector
This software sets the priority level for hl2.exe as "high"

Command-line parameters: `-novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -noquicktime`

I might say that this lag bug could not happen right after the first kill in the first match, but if it hits you - the only solution is rebooting the game

**UPD**: The only fast way we've found to eliminate this bug after it starting to happen - is to execute `hud_reloadscheme` command in console

**Comment by UAVXP** [comment] 2022-06-23 10:56
Almost forgot to mention. After this huge lag some of the enemy players starts to not render at all, and sometimes if they render - they're having my team model for some reason (imagine being in BLU team and getting killed by BLU sniper). Someone in the game chat suggested to me running a "stopdemo" command, but I don't remember if it fixes that model issues

**Comment by UAVXP** [comment] 2022-06-23 20:20
Here's the video with example: https://youtu.be/kIn6BiXYKHM
This time bug started to happen after 3 games and 2 enemy team votekicks

**Comment by UAVXP** [comment] 2022-06-24 00:19
Just tested, this bug occurs after 23-25 minutes on ctf_doublecross. I was not using TF2BD and removed any addons from "custom" folder

**Comment by Jgr9** [comment] 2022-06-24 04:11
Same here since the recent update, Intel CPU graphics (no mods).  Length of game freezes increase with every death until it finally crashes.

I also noticed that bots are able to change everyone's Flair! cosmetic decals - Troll Face of course.

**Comment by UAVXP** [comment] 2022-06-24 22:10
Changing mat_setvideomode could help btw

**Comment by Jgr9** [comment] 2022-06-25 00:18
Your resolution / window size?  Why?

**Comment by UAVXP** [comment] 2022-06-25 13:13
No, mat_setvideomode actually fixes the main bug (death lag), but not for long I suppose. mat_setvideomode has 3 parameters: `width`, `height` and `windowed`.
If you're in fullscreen mode, you can run `mat_setvideomode yourW yourH 1` and then `mat_setvideomode yourW yourH 1`
If in windowed - do the opposite

It's the fastest way to eliminate the death lag I found at the time. It's definitely faster than rebooting the whole game

**Comment by Jgr9** [comment] 2022-06-25 15:41
Actually you seem to be right, except..... For me the first time doing it always takes FOREVER for it to actually switch/change - Long enough to disconnect me, so I recommend not changing the video settings (fullscreen/windowed etc) until after you're off the server if you can help it. - Unfortunately griefers like to hold matches with objectives to instead last for 4 hours, so

Also, somebody who was also talking about the same problem in a TF2 match seemed to confirm that it isn't only an Intel graphics driver thing, nor laptop.  They're desktop with Nvidia and were also getting it since the update.

**Comment by UAVXP** [comment] 2022-06-25 19:36
Hey @Jgr9 , could you provide crash dumps that has been created due to death lag bug? It would be pretty handy for developers to investigate more quickly into that bug

**Comment by Jgr9** [comment] 2022-06-25 20:34
idk, I've always found logs TF2 gives to be pretty useless, but I can't say I actually know for sure in that regard. Also It takes (or can take) quite a while not only for the issue to show, but for it to finally crash, too.

**Comment by UAVXP** [comment] 2022-06-25 20:37
Yeah, I believe it take so long, but I meant not the logs, but crash dump, .mdmp file that is getting created after crash in a TF2's root folder

**Comment by Jgr9** [comment] 2022-06-25 20:41
I don't see one in TF2's root folder.

**Comment by UAVXP** [comment] 2022-06-25 20:45
No, verifying files shouldn't remove these dumps. Okay, that's strange and sad at the same time. Thank you for investigating)

**Comment by treacherousfiend** [comment] 2022-06-25 21:36
I've talked to a couple people who also have this issue but don't have an intel iGPU, so it might be worthwhile to remove the "Intel Driver" tag from this issue report?

**Comment by UAVXP** [comment] 2022-06-25 22:00
@kisak-valve , can you please remove the "Intel Driver" label from issue?

**Comment by Jgr9** [comment] 2022-06-26 04:24
Ugh... Unfortunately changing the video settings Fullscreen/Windowed still permanently removes objective status from the HUD (Capture Points, Cart progression, etc) until restart, and I still don't know of a way to fix it.  hud_reloadscheme doesn't fix it.

**Comment by UAVXP** [comment] 2022-06-26 20:49
By the way, hud_reloadscheme does fix the main issue (death lag)

**Comment by Jgr9** [comment] 2022-06-26 20:56
Wait what, it does?  So no need to change video settings then? lol

**Comment by UAVXP** [comment] 2022-06-26 21:12
Yes, it works for me at least

> idk if it's related, but Ever since they added the Friends list to the main screen my game stutters every time Esc is used during game. And yes, disabling the in-game Friends list does remove that issue but then you can't use parties.

Esc and also inventory change menu? I had that issue too, but this is probably Win10 related. When I was on Win7 on the same PC, I didn't experienced that stuttering

**Comment by Jgr9** [comment] 2022-06-26 21:16
I am 100% certain that started the update before the in-game Friends list appeared.

**Comment by UAVXP** [comment] 2022-06-26 21:20
Yeah, I've read that a Friends panel is causing this, but I'm too lazy to remove it so I can test. You probably can make another issue about this stuttering here

**Comment by nejby** [comment] 2022-06-26 22:38
Ok so i thought i had issues with my pc or something but thankfully i am not the only one having this issue
I remember having a normal match when then for some reason it was giving me a huge stutter when getting killed
even on the next map, the issue stays and becomes more and more annoying
my hardware is 
OS: Windows 10
GPU: GTX 1050TI
CPU: AMD Ryzen 3 1200

**Comment by Jgr9** [comment] 2022-06-27 00:14
I'll probably end up trying it tonight, but OP says inputting hud_reloadscheme in console temporarily fixes it (workaround).  Try that first once it starts happening. (or more if you want)

**Comment by treacherousfiend** [comment] 2022-06-27 00:21
i've seen a couple workarounds and all of them seem to include reloading the hud in some way, material resets like changing video settings are also a way to reload the hud (probably because the game needs to translate the hud to the new resolution)

and regarding that aimbot comment, the server keeps track of what areas the client can and can't see, and will only send data of other players that the client _can_ see, i'm not super familiar with how the cheats work but they probably don't need the team outline to find out where a player is, as long as the server sends that data.

**Comment by Jgr9** [comment] 2022-06-27 00:24
yeah, unfortunately changing some of the video settings can cause objective status on the hud (CP, Payload progression etc) to disappear permanently and hud_reload scheme doesn't even fix that for some reason.  Yet it sounds like it may fix the new death freezing.  i gotta test myself later

**Comment by Jgr9** [comment] 2022-06-27 04:35
Yup, can confirm that **hud_reloadscheme** does temporarily fix death freezes.

**Comment by Jgr9** [comment] 2022-06-28 04:39
Ugh....  hud_reloadscheme causes a giant scrollbar to cover Ping on the scoreboard.  It's always something.....

**Comment by VeridianFox** [comment] 2022-07-03 03:07
Having this same issue too. Just began happening recently. I can only assume it has something to do with the recent update to the game. Uninstalled/reinstalled the game with no custom HUD or master config in the game files. Issue seemed briefly resolved before coming right back. Incredibly annoying and always seems to last the full 15 seconds.

**Comment by treacherousfiend** [comment] 2022-07-03 04:56
Yeah unfortunately it is due to the update, I'm part of the mastercomfig discord and recently we fixed an issue which made the freezes worse, but otherwise all that we can do is wait for it to be fixed, and occasionally use a command like `hud_reloadscheme` to temporarily relieve the issue

**Comment by RexBucket** [comment] 2022-07-03 10:12
The problem is that if I write this command the game freezes and I am banned for lost connection, maybe we can only wait for an update from them, to fix death lag and invisible players.

**Comment by Jgr9** [comment] 2022-07-03 15:58
If you're using the video settings command, yeah, It'll do that.  Use **hud_reloadscheme** instead.  It should be quicker (though still temporary).

**Comment by ScorpianCode** [comment] 2022-07-12 01:52
It can be caused by getting dominated/revenged, and typically there's a pyro around. Then the sounds dies almost completely.

**Comment by toaoEda** [comment] 2022-07-23 02:06
Hey, I dont know much about computers or GitHub, but I started experiencing this problem around the time of the update too. Audio looping and freezing when I die (just like in the video), after I've been playing for a while. Some other bugs I've noticed is invisible players like OP mentioned, and I play a lot of MvM bootcamp (valve servers) - sometimes normal-sized robots appear large, sometimes they appear ubered. Using "snd_restart", "record; stop" dont fix these issues, usually I restart tf2 after letting my laptop cool down. Yes, potato gaming laptop. I use low graphical settings changed using in-game menu; i have no configs or mods or custom huds. I just assumed my potato settup was causing this problem, but i really think its something in the update. Its super annoying hearing audiolooping of screaming when you die. I'll try hud_reloadscheme, mat_setvideomode, to see if they help for me.

**Comment by Jgr9** [comment] 2022-07-23 03:55
Great, now hud_reloadscheme made my game crash completely.  No error of course.  I really hope they fix it soon, but I'm fearing they might not fix it ever.

**Comment by agrastiOs** [comment] 2022-07-23 08:34
@Jgr9 The death freeze will be fixed next update.

**Comment by UAVXP** [comment] 2022-07-23 12:51
> @Jgr9 The death freeze will be fixed next update.

How do you know that?

**Comment by MechaWolft** [comment] 2022-07-24 16:37
> @Jgr9 The death freeze will be fixed next update.

i hope it will drop really soon cuz that freezing is really annoying

**Comment by KookyKlutz** [comment] 2022-07-28 20:21
Low-key relieved to know that I'm not the only one experiencing this issue. Really hope that Valve does something about it soon, cuz it's getting to the point where it's almost unbearable to play

**Comment by agrastiOs** [comment] 2022-07-29 18:53
May be fixed in the latest update, per "Fixed an occasional lag spike when showing the kill cam for some players".

**Comment by agrastiOs** [comment] 2022-07-29 18:56
@UAVXP

**Comment by Jgr9** [comment] 2022-07-29 19:11
Here's hoping, but I always have to doubt.

**Comment by UAVXP** [comment] 2022-07-30 00:49
Will do. Need to play longer, I've only handled about 30 minutes of gameplay or so today, so maybe this bug didn't show yet

**Comment by KookyKlutz** [comment] 2022-07-30 17:45
With roughly 3 hours worth of gameplay after the patch, I have yet to experience the death lag. 99% sure the issue is gone, but once again you never know with Source games lol

**Comment by KookyKlutz** [comment] 2022-07-30 17:45
With roughly 3 hours worth of gameplay after the patch, I have yet to experience the death lag. 99% sure the issue is gone, but once again you never know with Source games lol

**Comment by Jgr9** [comment] 2022-07-30 18:11
I don't think I got it either, but.....

it still sucks that normal (?) lag spikes can cause players go invisible (fixed by recording a demo).  Which happened to me a lot still last night due to household internet usage.  ugh

**Comment by agrastiOs** [comment] 2022-07-31 09:07
> I don't think I got it either, but......
> 
> it still sucks that normal (?) strong lag spikes can cause players to go invisible (fixed by recording a demo). Which happened to me a lot still last night due to household internet usage. ugh

Well, that is a separate issue. I've experienced the Death Freeze bug twice before the patch, but haven't experienced it yet. Seems like it might be fixed, knowing that four of us didn't get it yet.

**Comment by UAVXP** [comment] 2022-08-05 09:07
@kisak-valve 
Well, so I've tested for a few days, if this bug appears now, after the latest update. Now I could definitely say that no, it doesn't.

I think the issue is fixed now. Thank you all guys for participating)

**Comment by Jgr9** [comment] 2022-08-05 15:44
I'm still wondering if it (or some part/portion) of (what we think is it) might still be happening, and may be brought on / pushed into happening by bots?

Though I haven't needed hud_reloadscheme anymore so far I don't think, so maybe not that issue.  Maybe, even though Valve is working on DDoS protection the bots may be doing it / successful just enough to cause a lag spike that'll cause people to end up with invisible players (fixed by recording a demo).  I say this because others were mentioning the lag and invisible players at the same time I got it.

**Comment by agrastiOs** [comment] 2022-08-05 16:03
@Jgr9 That's an entirely different issue. I would suggest closing this one and opening one regarding invisible players after a lag spike.

**Comment by kisak-valve** [comment] 2022-09-09 19:40
Closing as fixed in the [2022-07-29](https://www.teamfortress.com/post.php?id=141285) Team Fortess 2 update.

**Closed by kisak-valve** 2022-09-09 19:40 UTC
Labels: Team Fortress 2, Windows, Need Retest
