### ISSUE TITLE
[CS:S/Mac] Seeing hostages causes graphics bug

### ISSUE THREAD

**Issue by philip-lamb** [ValveSoftware/Source-1-Games#2003] opened 2016-09-01 03:06 UTC
Game: 
Counterstrike Source

System:
Mac OS El Capitan 10.11.1
Various CPUs and GPUs.

When i enter a map with hostages, cs_office or cs_italy for example,
i move to the hostages so i can see them, a hard graphics bug appears and it blocks my view completely. 
If I dont look at them, there is no graphics bug.

Issue #1930 has much more complete reporting.

**Comment by BrianMcElwain** [comment] 2016-09-05 22:30
I've had this bug since I got the macbook a year ago. This bug is at least a year old.

**Comment by raymusmunt** [comment] 2016-10-12 20:02
I wonder why this issue has not been addressed in over a year ?

**Comment by enkaskal** [comment] 2016-10-14 03:57
I've opened a steam support incident in the hopes it will help. 

Ticket #: 4918-ERTA-1881

**Comment by rememberedbound** [comment] 2016-10-31 14:15
This same bug exists in Half Life 2 Deathmatch, but only with certain player models. It's specifically the faces on the models causing the issue. Screenshot attached.

![hl2 rendering bug its the faces](https://cloud.githubusercontent.com/assets/5528610/19857119/63776104-9f74-11e6-884f-a5626d1c25fb.jpg)

**Comment by kisak-valve** [comment] 2016-12-30 16:07
Closing as a duplicate of #1930.

**Closed by kisak-valve** 2016-12-30 16:07 UTC
