### ISSUE TITLE
[Portal] Weird keyboard key swapping

### ISSUE THREAD

**Issue by hmaarrfk** [ValveSoftware/Source-1-Games#1125] opened 2013-08-01 11:11 UTC
Hi,

I swapped my CapLock and Esc keys in Gnome-Shell and every application I can think of detects the swap accordingly. When I try to set a shortcut to be the Escape key in Portal, it detects both the [Hardware-Esc] and [Hardware-CapsLock] as CapsLock.

I believe that that the correct behaviour should be to respect the choice made in Gnome-Shell.

Fedora 19 x64.
Steam installed from repository available in http://spot.fedorapeople.org/steam/
Gnome-Shell 3.8.3
Intel HD 4000 graphics

**Comment by kisak-valve** [comment] 2016-12-24 16:23
Closing as a duplicate of #304.

**Closed by kisak-valve** 2016-12-24 16:23 UTC
Labels: Feature Request, Linux, Reviewed
