### ISSUE TITLE
[TF2 - Linux] Regular/repeated GPU lockups since early January

### ISSUE THREAD

**Issue by lycurgus** [ValveSoftware/Source-1-Games#1953] opened 2016-01-21 08:21 UTC
Since around early January, I've been getting fairly consistent GPU lockups when playing TF2. Usually on the order of 10 minutes between each lockup, though it has been as low as 5-10 seconds between one pair. The game image freezes, sound loops, and ten seconds later the screen goes black for 2 or so seconds before coming back to the game. The game runs fine both before and after a lockup.

Checking `dmesg` reveals a message from the graphics driver (I am using the open-source radeon drivers, on an R9 290) that "ring 0 stalled for more than 10000msec". A full log of what `dmesg` gets when a lockup happens is here: [GPU_lockup.txt](https://github.com/ValveSoftware/Source-1-Games/files/98867/GPU_lockup.txt)

There doesn't seem to be any rhyme or reason to the lockups; they happen in various places in various maps, with or without players nearby. They have happened under both Arch and Fedora 23.

I haven't been able to figure out what _causes_ the lockups - the dmesg log above only happens after a lockup, and there's nothing logged between the end of one such log and the next (i.e. nothing logged prior to a given lockup).

**Comment by Tele42** [comment] 2016-01-21 12:22
Duplicate of #1943 and https://bugs.freedesktop.org/show_bug.cgi?id=93649.

**Comment by lycurgus** [comment] 2016-01-22 19:50
Both of those look related, but I'm not sure if it's a duplicate - from what I'm reading 1943 seems to be an all-out crash, as does 93649. In my case I've only had 2 or 3 cases (across multiple days of play and probably ~hundreds of GPU lockups) where the system actually becomes unusable after the lockup. In most cases it just locks up for ~15 seconds and then continues as if nothing had happened. I guess it might be a different symptom of a similar issue, rather than a different issue altogether.

Is there anything else I should get in terms of logging to try and narrow down what's happening?

**Comment by Tele42** [comment] 2016-01-22 22:35
As this is most likely a driver issue, I would reach out to the mesa devs and see what they think.

**Comment by ElectricTriangle** [comment] 2016-01-28 15:14
possibly also related to https://bugs.freedesktop.org/show_bug.cgi?id=92912

**Comment by Lukypie** [comment] 2016-03-14 00:14
Also affects amdgpu, AMD r9 380 video card with powerplay enabled

**Comment by kisak-valve** [comment] 2016-12-30 18:30
Closing as a duplicate of #1943.

**Closed by kisak-valve** 2016-12-30 18:30 UTC
