### ISSUE TITLE
Windows resets TF2 sound since 64 bit update

### ISSUE THREAD

**Issue by Context-Clues** [ValveSoftware/Source-1-Games#5971] opened 2024-05-04 21:25 UTC
Every time I open tf2 it is on max volume and I have manually turn it down to where I want it to be. 
I tried searching around and it seems I'm not the only one having this issue but I could not find it reported on here.

https://www.reddit.com/r/tf2/comments/1ccihke/windows_resets_tf2_sound_since_64_bit_update/

**Comment by Context-Clues** [comment] 2024-05-04 21:25
![sound](https://github.com/ValveSoftware/Source-1-Games/assets/168936868/b1fe27c2-cd59-4f5b-b236-9eab2d143b75)

**Comment by NULLYUKI** [comment] 2024-05-04 21:26
Duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/5894

**Comment by kisak-valve** [comment] 2024-05-04 21:46
Hello @Context-Clues, as @NULLYUKI noted, this issue is already being tracked at #5894.

Closing as a duplicate.

**Closed as not planned by kisak-valve** 2024-05-04 21:46 UTC
