### ISSUE TITLE
[Tf2] being able to see BLU team in weapon loadout.

### ISSUE THREAD

**Issue by condor00fr** [ValveSoftware/Source-1-Games#5533] opened 2024-02-23 06:19 UTC
Out of all of the great features available in our inventory, we can't see what our loadouts look like on BLU, only on RED. Being able to swap out from one team to the next in our inventory would be a much needed change that's been requested many times in the past and has become a standard in custom huds.

Here's a simple exemple 
![image](https://github.com/ValveSoftware/Source-1-Games/assets/71549583/8bdec501-0c40-4c84-a9a5-9c7caaf75d16)

**Comment by JoriKos** [comment] 2024-02-23 12:09
Duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/2109

Also, you've uploaded a thumbnail, rather than the actual screenshot.

**Comment by kisak-valve** [comment] 2024-02-23 14:16
Closing as a duplicate.

**Closed by kisak-valve** 2024-02-23 14:16 UTC
