### ISSUE TITLE
[Linux, AMD, Portal, Portal2, TF2, HL2:LC] Game fails to set high resolution properly on launch in fullscreen or borderless modes

### ISSUE THREAD

**Issue by that-guy-melvin** [ValveSoftware/Source-1-Games#1682] opened 2014-03-07 21:04 UTC
### Summary

---

Across all source games I've tested on, the game fails to set high resolution properly on launch in either fullscreen or borderless window mode.
### System info:

---

```
     *-cpu
          product: AMD FX(tm)-8350 Eight-Core Processor 'Vishera' @4000Mhz

     *-memory
          RAM: 32GiB (4x8GiB) @1333MHz

    *-os version
          name: Linux Mint 16 Petra (64 bit) KDE
          kernel: Linux 3.11.0-12-generic
          x server release: 11405000
          x window manager: KWin

    *-display
          product: Pitcairn XT [Radeon HD 7870 GHz Edition]
          primary VRAM: not detected     [GDDR5 1200MHZ 2048MB]
          driver packaging version: 13.101-130523a-15767E-ATI
          RandR version: 1.3
          OpenGL shading language version: 4.3

      *-monitors
        *-display 1: IPS234 DisplayPort (via active DVI adapter)
            rotation: 90
            resolution: 1080x1920
            virtual location: 2160,0
        *-display 2: IPS234 DVI-SL
            rotation: 90
            resolution: 1080x1920
            virtual location: 1080,0
        *-display 3: IPS234 DVI-SL
            rotation: 90
            resolution: 1080x1920
            virtual location: 0,0
        *-desktop resolution: 3240x1920

[addn'l info omitted due to relevance]

Again, the line that should be important here is "-Desktop Resolution, 3240x1920"

```
# The Problem

---

Three screens joined together via AMD's RandR implementation (1) form a desktop area of 3240x1920. Source games using default settings launch as fullscreen on a single monitor, at 1080x1920 while leaving the rest of my screen real estate untouched. 

![portalproblem1](https://f.cloud.github.com/assets/6886413/2379665/f1050006-a89d-11e3-9431-250123631036.jpg)

This is, essentially, expected behavior(2), and I expected to work around it. The first workaround I attempted to use was manually overridding the games graphics settings from KDE's built-in window rules settings. I've done this successfully in other games to produce a borderless window effect, but the source games don't allow this to alter their actual rendering resolution, resulting in unpleasant stretching. 

![portalproblem2](https://f.cloud.github.com/assets/6886413/2379668/fefe61e8-a89d-11e3-9cf5-6899682b3f87.jpg)

I then attempted to use the [source engine's command line options](https://developer.valvesoftware.com/wiki/Command_Line_Options) to run the game in borderless window mode. `-windowed -noborder -w 3240 -h 1920 -x 0 -y 0` This produced results highly similar to the original attempts to run the game, but the game window could be moved freely via the OS's alt-click drag functionality. 

![portalproblem3](https://f.cloud.github.com/assets/6886413/2379670/034a441a-a89e-11e3-960c-5845b75b15f2.jpg)

Further experimentation showed that tags such as `-windowed -noborder -w 840 -h 840` which measure less than a single screen in width, are parsed properly, but I don't have a picture of that.
#### Footnotes:

---

(1)...which is a tad bit touchy and irritating when compared to the open version which doesn't require a reboot for every setting change, but the open driver doesn't support 3d acceleration for Pitcairn cards as of last time I checked (two weeks ago).
(2)...though it can cause some problems in games like Portal2 where the UI is set up horizontally so that things like 'Graphics Options' and 'Quit' fall off the edges of the screen.

**Comment by that-guy-melvin** [comment] 2015-03-06 18:24
Still not working...

Can't set resolution arbitrarily via config files, game ignores launch options, and attempting to use kde's arguments to force resolution stretches the image, badly mangling aspect ratio.

**Comment by kisak-valve** [comment] 2016-12-28 19:30
Closing as a duplicate of #1525.

**Closed by kisak-valve** 2016-12-28 19:30 UTC
Labels: AMD/ATI Driver, Source 1 Engine
