### ISSUE TITLE
[TF2] [L4D2] [Linux] Severe framerate and frametime issues with Vulkan mode

### ISSUE THREAD

**Issue by spacebanana420** [ValveSoftware/Source-1-Games#5923] opened 2024-04-26 20:16 UTC
Just like in L4D2 with the -vulkan argument, launching TF2 in its new default Vulkan mode causes severe issues with the game's framerate and frametime.
At any seemingly random point during gameplay, the framerate will drop significantly and stay low, and the frametime stays extremely inconsistent, until you restart the game. This does not happen if I launch TF2 in legacy OpenGL mode, just like how the issue doesn't happen with L4D2 in its default OpenGL mode.

### System specs:

* NixOS 23.11 (Tapir)
* Kernel 6.8.1
* X11
* Xfce 4.18

### Hardware specs:
* Intel core i7-1165G7
* Intel TigerLake-LP GT2 [Iris Xe Graphics]
* 16GB RAM

My machine's NVIDIA dGPU is not in use.

**Comment by daigennki** [comment] 2024-04-27 13:32
Same issue here (although I haven't tested it in L4D2), except it happens with the following specs:

- Kernel: 6.8.7-arch1-1
- DE/WM: KDE Plasma/KWin 6.0.4-1 (Wayland)
- CPU: AMD Ryzen 9 7900X
- GPU: AMD Radeon RX 5700 XT (radv)
- System memory: 64GB

The issue (severe stuttering) started occurring after about 30 minutes, although I only measured it once, so it could vary. I also monitored the system memory and video memory usage throughout the session, and it didn't increase very much. At the time the stuttering started to occur, TF2 memory usage was about 1.9 GiB, and total video memory usage across all processes was about 5.5 GiB. The issue persists across level changes.

**Comment by eeceebee** [comment] 2024-04-27 19:31
I also have this issue.  

For the first 30ish minutes of gameplay I have constant framerates of 144, but then suddenly I start to get evenly-spaced stutters whenever I am moving the mouse or pressing/holding keys.  

The stutters do NOT occur if I am not moving the mouse or pressing keys, even if my character/view is moving in game. This leads me to believe that it might be connected to input processing. 

![Here is a screenshot from Mangohud](https://github.com/ValveSoftware/Source-1-Games/assets/168303259/569d38c3-118e-457b-88cc-44874b410483) showing the evenly-spaced stutters. 

For specs I have:

- OpenSUSE Tumbleweed
- Kernel: 6.8.7-1-default 
- DE: GNOME 46.0 (Wayland)
- CPU: AMD Ryzen 5 5600X
- AMD Radeon RX 6750 XT
- Memory: 32 GB

**Comment by kisak-valve** [comment] 2024-04-27 19:36
Hello, this issue is already being tracked at #5785.

Closing as a duplicate.

**Closed by kisak-valve** 2024-04-27 19:36 UTC
Labels: Team Fortress 2, Linux, Left 4 Dead 2

**Comment by NULLYUKI** [comment] 2024-04-27 19:43
@kisak-valve How is this issue a duplicate if the described has also been noticed in "Left 4 Dead 2" ?

**Comment by kisak-valve** [comment] 2024-04-27 19:48
Hello @NULLYUKI, `This does not happen if I launch TF2 in legacy OpenGL mode, just like how the issue doesn't happen with L4D2 in its default OpenGL mode.` The issue is with games rendering to Vulkan and having the Steam overlay in the disabled configuration, not game specific.

**Comment by NULLYUKI** [comment] 2024-04-27 19:50
Ah ok, I understand now. Thank you for the explanation!
