### ISSUE TITLE
[TF2] [Audio] Memory leak in soundsystem when BSP-packed mp3s/wavs overriding existing content such as voicelines play

### ISSUE THREAD

**Issue by pivotman319-owo** [ValveSoftware/Source-1-Games#4813] opened 2023-03-02 16:09 UTC
Maps with packed MP3 files that override the original game sound files (such as Bread Space) are likely to cause a bug that corrupts the currently-loaded sounds by clashing with that of both the packed sound file and the one from the tf2_sound_misc/vo VPK, in turn presenting a constant 2-3 MB/s memory leak upon attempting to play the affected sound file unless snd_restart is invoked through the console, although this is a temporary workaround. This bug eventually leads to an out-of-memory crash within the engine.

<video src="https://user-images.githubusercontent.com/15126754/222484091-da207b6b-624c-439e-8074-17a40d604f02.mp4"></video>
![hl2_2023-03-02_16-43-54](https://user-images.githubusercontent.com/15126754/222484347-558f6585-c007-4885-9e95-2bd62cc76d9d.png)

**Comment by worMatty** [comment] 2023-03-03 17:55
Does this also happen when sounds are overridden using a soundscript?

**Comment by Jgr9** [comment] 2023-03-08 05:22
Can confirm having played on Bread Space does end up causing a crash either during the map or sometime later

The audio issues on this map can also sometimes cause loud screeching noises.  
At first I thought this noise was the halloween voices, but no I'm pretty sure it's this map.  Or combined?

**Comment by pivotman319-owo** [comment] 2023-03-08 08:16
> The audio issues on this map can also sometimes cause loud screeching noises. At first I thought this noise was the halloween voices, but no I'm pretty sure it's this map. Or combined?

it's the map itself, the zipfile within overrides existing announcer lines

**Comment by EnderGamerXP** [comment] 2023-05-04 00:58
hope this whil be fixed soon, but it's weird that does't with the older version of this map

**Comment by aarmastah** [comment] 2023-07-16 22:37
Just opened another case of what appears to be the same issue due to a reoccurrence on the new VSH maps.

When maps with packed audio files are updated several times, audio files with the same names (even when identical) eventually fail to play over and over and lead to a memory leak. This is currently occurring on the new VSH maps in the game and previously occurred on cp_gravelpit_snowy, but I was able to work around the issue simply by renaming the folder the sounds were in every time I updated said map.

I have provided a video of me replicating the issue:
https://www.youtube.com/watch?v=OYCWkvUWmIs

Reproduction steps:

1. Decompile vsh_distillery and unpack its assets
2. Rename the vmf file to vsh_distillery_dev.vmf
3. Rename any applicable soundscapes, sound scripts, etc to match the name of the vmf
4. Compile the map (fast is fine) and pack the content afterward
5. Play the map in game
6. Make a minor change to the map and repeat steps 4-5
7. Make a minor change to the map and repeat steps 4-5
8. Make a minor change to the map and repeat steps 4-5 (in the video, this specific step was accomplished with a simple bspzip.exe -repack -compress)

If done correctly, the sounds will eventually fail to play altogether and the game will crash due to being out of memory.

LizardOfOz (one of the developers of VSH) has been notified of the workaround.

**Comment by Ashetf2** [comment] 2023-07-25 23:49
Maybe related to a fix in today's update: Fixed a crash that can occur related to MP3s on VSH maps. Please retest

**Comment by aarmastah** [comment] 2023-07-26 14:49
Issue behaves a little differently after the patch. Now every time a packed audio file tries to play, it only fails once (and doesn't play, as expected), but the game does not crash. I created a logic_timer entity on the map that attempts to play "saxton_hale.jump" over and over to simulate the previous behavior, but was unable to replicate the "out of memory" crash. It seems that the workaround is still necessary in order to ensure that sounds continue to play properly, but at least the game no longer crashes.

New behavior:
![image](https://github.com/ValveSoftware/Source-1-Games/assets/1887380/0b7c5031-0ef3-4378-a6a6-0783881c6368)

Simulation:
![image](https://github.com/ValveSoftware/Source-1-Games/assets/1887380/3e3887b3-732c-425b-b0ff-ada0ee00e2a8)

**Comment by kisak-valve** [comment] 2023-09-08 22:48
Closing per the last couple comments.

**Closed by kisak-valve** 2023-09-08 22:48 UTC
Labels: Team Fortress 2, Audio, Need Retest
