### ISSUE TITLE
[TF2] Issue with uploading Replays on YouTube

### ISSUE THREAD

**Issue by AndreyHas** [ValveSoftware/Source-1-Games#4917] opened 2023-04-23 10:07 UTC
At the moment, the game has a problem with Replays, they cannot be uploaded to YouTube. This problem could be not big, if they wouldnot hits the Achievements which is about the Views on your "Replay". So at this moment the achievements cannot be obtained in the fair way.
(I'm not good at English, so i hope i describe problem accesibly)

**Comment by JoriKos** [comment] 2023-04-23 10:12
Duplicate of https://github.com/ValveSoftware/Source-1-Games/issues/2277

**Comment by kisak-valve** [comment] 2023-04-23 12:43
Closing as a duplicate.

**Closed by kisak-valve** 2023-04-23 12:43 UTC
