### ISSUE TITLE
[TF2] Graveyard is still broken.

### ISSUE THREAD

**Issue by gdfsgdfg** [ValveSoftware/Source-1-Games#6388] opened 2024-10-01 16:32 UTC
Current issues in casual is error texture in hud, ghosts aren't replaced by the custom ones and people can't seem to be able to spawn into the map being stuck in spectator mode.

![Untitled](https://github.com/user-attachments/assets/4662b827-95da-467a-8971-6bfc02dff2c5)

**Comment by JoriKos** [comment] 2024-10-01 17:45
Duplicate of #5257

**Closed as not planned** 2024-10-01 17:49 UTC
Labels: Team Fortress 2
