### ISSUE TITLE
[TF2] Allow players to customize viewmodel sway

### ISSUE THREAD

**Issue by pitbullnamed1** [ValveSoftware/Source-1-Games#6048] opened 2024-06-05 02:19 UTC
cl_wpn_sway_interp and cl_wpn_sway_scale are console commands that control weapon sway in TF2, and it looks so good it's weird it's a devonly client cheat? why can't it be an allowed console command for players? There seems to be no bugs related to this feature, and it fits TF2 so well, but can only be used on sv_cheats 1 sessions.

**Comment by dandongus** [comment] 2024-06-05 04:18
Duplicate of #2120 and #4007

**Comment by kisak-valve** [comment] 2024-06-05 12:22
Hello @pitbullnamed1, as @dandongus noted, this issue is already being tracked at #2120.

Closing as a duplicate.

**Closed as not planned by kisak-valve** 2024-06-05 12:22 UTC
