### ISSUE TITLE
Cannot change spoken language in TF2 without changing the whole language.

### ISSUE THREAD

**Issue by Shished** [ValveSoftware/Source-1-Games#203] opened 2013-03-13 13:34 UTC
http://steamcommunity.com/app/221410/discussions/2/846939071070407465/

You said that this bug added to bug DB but it still not fixed.

**Comment by kisak-valve** [comment] 2016-12-21 13:54
Closing as a duplicate of #37.

**Closed by kisak-valve** 2016-12-21 13:54 UTC
Labels: Reviewed, Team Fortress 2
