### ISSUE TITLE
Game not launching on steam deck with 64 bit

### ISSUE THREAD

**Issue by snowandco** [ValveSoftware/Source-1-Games#5719] opened 2024-04-19 09:36 UTC
So i tried launching the game normally, with both the default option and the legacy option, but the game won't even boot up. I tried switching over to proton and the game did launch however i wasn't allowed to join into any casual games.

**Comment by JoriKos** [comment] 2024-04-19 10:04
Dupe of #5621

**Comment by kisak-valve** [comment] 2024-04-19 13:46
Hello @snowandco, as @JoriKos noted, this issue is already being tracked at #5621.

Closing as a duplicate.

**Closed by kisak-valve** 2024-04-19 13:46 UTC
