### ISSUE TITLE
[ALL?] func_rotating stops rotating

### ISSUE THREAD

**Issue by squimball** [ValveSoftware/Source-1-Games#1143] opened 2013-08-13 07:33 UTC
I'm not sure if this was by design, but I have not seen this behavior until after several updates ago.  I didn't know what was happening at the time, but now I do.

The angle values in m_angRotation do not wrap around and the map gives up on rotating it any further once they overflow.  The only way to make it spin again is to set the angles back to 0 (or teleport it back to a 0 angle).  I don't have the exact angle at which it stops, but it is something close to this value...

Bad SetLocalAngles(0.000000,360093.000000,0.000000) on func_rotating

The game I play is HL2DM, but I assume this would apply to all games that use func_rotating entities (perhaps just SteamPipe versions..).

**Comment by kisak-valve** [comment] 2016-12-24 17:00
Closing as a duplicate of #517.

**Closed by kisak-valve** 2016-12-24 17:00 UTC
