### ISSUE TITLE
[TF2] Sometimes persistent very low FPS until game restart

### ISSUE THREAD

**Issue by Lysius** [ValveSoftware/Source-1-Games#1759] opened 2014-06-22 10:13 UTC
Sometimes (or rather "often") when I connect to a TF2 server, I get really low FPS (<5) and sound stuttering when connecting to a server. This is visible already in the welcome and team selection screen. When this happens, the only way to return to normal seems to be to restart TF2. As far as I can remember, it only happens on the first server I connect to. If that goes well, all further connects don't show the problem. Also I have never seen it happen when I connect to a server running koth_nucleus as the first server (using that as a workaround for now).

Since I started playing TF2 again this week (have not played for a few months), I'm seeing it very often. I only remember one or two occurrences from before.

console output from when this happened after connecting to pl_hoodoo_final:
https://gist.github.com/Lysius/08d9631918d54f56621e
console output when this not happened after connecting to koth_nucleus first and then pl_hoodoo_final:
https://gist.github.com/Lysius/1ed23cb756b5b60e944a

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3700 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux 3.10 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.14.6-200.fc20.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11404000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2014-04-15

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 460/PCIe/SSE2

    Driver Version:  4.4.0 NVIDIA 337.25
    OpenGL Version: 4.4
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0xe22
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1680 x 1050
    Desktop Resolution: 3360 x 1050
    Primary Display Size: 17.05" x 10.67"  (20.08" diag)
                                            43.3cm x 27.1cm  (51.0cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: SigmaTel STAC9750,51

Memory:
    RAM:  15994 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  563214 Mb
    Largest Free Hard Disk Block:  107623 Mb

Installed software:

Recent Failure Reports:

```

**Comment by volca02** [comment] 2016-11-15 22:01
I have this kind of issue on linux. I've a strong feeling it is caused by misbehaving material loading thread (at lest perf showed it running constantly and hogging the cpu).

I can reproduce it by going to a community server (via server browser) and then switching to casual. It happens probably 100% of the time when doing that.

**Comment by kisak-valve** [comment] 2016-12-29 15:12
Closing in favor of #23.

**Closed by kisak-valve** 2016-12-29 15:12 UTC
