### ISSUE TITLE
[TF2] Performance Issues

### ISSUE THREAD

**Issue by alkaris2** [ValveSoftware/Source-1-Games#3874] opened 2022-03-21 10:02 UTC
Some issue started happening with Team Fortress 2 when I tried to load it up, an issue caused by a recent update perhaps.

So the issue is that when loading up Team Fortress 2, the first thing I notice is that the [ Loading...] bubble that displays in the bottom-right corner the text is all low resolution and blurry. Getting into the main menu of the game I notice right off the bat that everything is super low resolution and blurry, and running at 5-10 FPS, on top of that unusually large CPU usage maxing out all cores of an i7-7700K.

I've used the same settings for Team Fortress 2 that I've always had for many years with no issues at all.

![image](https://user-images.githubusercontent.com/73155407/159238366-33dd5039-af14-4c10-a660-466836a4831b.png)
![image](https://user-images.githubusercontent.com/73155407/159238413-a82d2530-0ac3-415e-a6e9-a661525e8509.png)

And here's the CPU usage of TF2

![image](https://user-images.githubusercontent.com/73155407/159238551-3a5708b2-a0d4-4d9e-8ac0-0237900a32d4.png)
![image](https://user-images.githubusercontent.com/73155407/159238579-2acdd656-56de-4820-b2af-5b97ca418c2e.png)

You can clearly see from the TF2 screenshots there that the resolution is blurry and text is blurry looking also, I've never had this issue before until now. I shouldn't be seeing 5-10 FPS with blurry and low resolution along with stutters. Because typically on these settings I've used for a very long time average me of around 80-120 FPS, and CPU usage never being 595.% across all cores. I'm typically use to seeing TF2 using around 60% at most across 2 cores.

```BASH
Graphics:
  Device-1: NVIDIA GP104 [GeForce GTX 1070] vendor: ASUSTeK driver: nvidia
    v: 510.54 bus-ID: 01:00.0
  Device-2: Logitech HD Pro Webcam C920 type: USB
    driver: snd-usb-audio,uvcvideo bus-ID: 1-5.3:8
  Device-3: AVerMedia Live Gamer Portable 2 Plus type: USB
    driver: snd-usb-audio,uvcvideo bus-ID: 3-2:3
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: nvidia
    gpu: nvidia resolution: 1920x1080
  OpenGL: renderer: NVIDIA GeForce GTX 1070/PCIe/SSE2
    v: 4.6.0 NVIDIA 510.54 direct render: Yes
```

```
5.15.28-1-MANJARO
```

Steam System Information:

Gist: https://gist.github.com/alkaris2/77b362d5ee9f43e7eb8703d04641115d

**Comment by kisak-valve** [comment] 2022-03-21 12:19
Hello @alkaris2, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by jspspike** [comment] 2022-03-25 01:53
Hello, I have a very similar setup to @alkaris2 and believe we have a similar issue.

[Steam Information Gist](https://gist.github.com/jspspike/445d928c8992937abc97f46d0a608cbb)

`Manjaro 21.2.5` `x86_64 Linux 5.16.14-1-MANJARO`

I think the root of the problem is that TF2 (and also the steam client it seems from the Steam Information) is using `llvmpipe` as the rendering driver instead of the proprietary NVIDIA one. You can see this when using the `mat_info` command and the driver is `llvmpipe`. In another source game where I don't have any performance issues like CSGO you can see that it's using NVIDIA drivers.

TF2:
```
Driver : OpenGL Mesa/X.org (llvmpipe (LLVM 13.0.1, 256 bits)) Version : 0
Driver Description :  Mesa/X.org (llvmpipe (LLVM 13.0.1, 256 bits)) 4.5 (Compatibility Profile) Mesa 21.3.7 - 2560x1440
Chipset version 1 1 0 0
```

CSGO:
```
Driver : OpenGL NVIDIA Corporation (NVIDIA GeForce GTX 780 Ti/PCIe/SSE2) Version : 0
Driver Description :  NVIDIA Corporation (NVIDIA GeForce GTX 780 Ti/PCIe/SSE2) 4.6.0 NVIDIA 470.103.01 - 2560x1440
Chipset version 1 1 0 0
```

Despite the system OpenGL renderer being set to Nvidia drivers as shown below, TF2 and Steam seem to use llvmpipe. 
```
jspspike@jspspike:~ % glxinfo | grep -i "renderer"
OpenGL renderer string: NVIDIA GeForce GTX 780 Ti/PCIe/SSE2
```

@alkaris2 also has llvmpipe as his renderer in his team gist so that is why I'm assuming he's facing a similar issue

**Comment by kisak-valve** [comment] 2022-03-25 02:07
Looking at the system information, yes, that assessment is accurate. It's most likely caused by missing the 32 bit userspace libraries for NVIDIA's driver.

@alkaris2, please check if you have the `lib32-nvidia-utils` system package installed and install if it is missing.
@jspspike, I'm guessing you're using an AUR managed NVIDIA driver, and `lib32-nvidia-470xx-utils` is what you should check.

**Comment by jspspike** [comment] 2022-03-25 02:29
That was it! Thanks for your help

**Comment by kisak-valve** [comment] 2022-04-29 14:46
Closing because this issue was a general system configuration issue, not game-specific.

**Closed by kisak-valve** 2022-04-29 14:46 UTC
Labels: Team Fortress 2, Linux, Need Retest
