### ISSUE TITLE
[HLDMS] Improved HLDMS Player Model Physics, Along with Further Data Player models

### ISSUE THREAD

**Issue by Theuaredead** [ValveSoftware/Source-1-Games#1473] opened 2013-10-12 00:26 UTC
Download:
http://puu.sh/4NN8e

If you want Source files Alfred, post a comment and I'll send them via your "@valvesoftware.com" account if you have one.

Known Bugs,
Walking, Running, and Jumping animations do not load correctly.

**Comment by kisak-valve** [comment] 2016-12-27 19:19
Closing as a duplicate of #1219.

**Closed by kisak-valve** 2016-12-27 19:19 UTC
Labels: Half-Life Deathmatch: Source, Reviewed
