### ISSUE TITLE
[TF2] Mismatched map thumbnails

### ISSUE THREAD

**Issue by FindTheBorealis** [ValveSoftware/Source-1-Games#2051] opened 2017-01-04 18:34 UTC
A few map thumbnails show the wrong map. Pass Time maps District and Timbertown show as
Player Destruction map Watergate, and Payload map Swiftwater shows as the King of the Hill map Highpass.

**Comment by kisak-valve** [comment] 2017-01-04 19:33
Closing as a duplicate of #2024.

**Closed by kisak-valve** 2017-01-04 19:33 UTC
