### ISSUE TITLE
Did valve know your L4D2 matchmaking system was cracked and hijacked ?

### ISSUE THREAD

**Issue by GameRookies** [ValveSoftware/Source-1-Games#5323] opened 2023-11-22 01:04 UTC
(Just in China)

Each connection request from players would be redirected to the cracker's server through your damned matchmaking system. These servers pretend to be the offical server and add many payment options in order to earn money. Can valve's development team stop just stand by and pay high attention to this sitiuation?

**Comment by kisak-valve** [comment] 2023-11-22 01:08
Hello @GameRookies, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #5297.

**Closed by kisak-valve** 2023-11-22 01:08 UTC
